### ISSUE TITLE
How to solve installation error?

### ISSUE THREAD

**Issue by gnh1201** [NuSkooler/enigma-bbs#100]
I tried install enigma-bbs, but occurred a lots of error.
please check this error messages.

Thanks

```
> 
> [root@localhost misc]# ./install.sh
>                                                                      ______
> _____________________   _____  ____________________    __________\_   /
> \__   ____/\_ ____   \ /____/ /   _____ __         \  /   ______/ // /___jp!
>  //   __|___//   |    \//   |//   |    \//  |  |    \//        \ /___   /_____
> /____       _____|      __________       ___|__|      ____|     \   /  _____  \
> ---- \______\ -- |______\ ------ /______/ ---- |______\ - |______\ /__/ // ___/
>                                                                        /__   _\
>        <*> ENiGMA½ // https://github.com/NuSkooler/enigma-bbs <*>        /__/
> 
> ENiGMA½ will be installed to /root/enigma-bbs, from source https://github.com/NuSkooler/enigma-bbs.git.
> 
> ENiGMA½ requires Node, v4.4 will be installed via nvm. If you already have nvm installed, this install script will update it to the latest version.
> 
> If this isn't what you were expecting, hit ctrl-c now. Installation will continue in 10 seconds...
> 
> 2016-09-30 13:38:46 Checking git installation
> 2016-09-30 13:38:46 Checking curl installation
> 2016-09-30 13:38:46 Checking Python installation
> 2016-09-30 13:38:46 Installing nvm
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 10250  100 10250    0     0  22465      0 --:--:-- --:--:-- --:--:--  139k
> => nvm is already installed in /root/.nvm, trying to update using git
> => => Compressing and cleaning up git repository
> Counting objects: 5484, done.
> Compressing objects: 100% (5453/5453), done.
> Writing objects: 100% (5484/5484), done.
> Total 5484 (delta 3529), reused 0 (delta 0)
> 
> => Source string already in /root/.bashrc
> => Close and reopen your terminal to start using nvm or run the following to use it now:
> 
> export NVM_DIR="/root/.nvm"
> [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm
> 2016-09-30 13:38:46 Installing Node 4.4 via nvm
> v4.4.7 is already installed.
> Now using node v4.4.7 (npm v2.15.8)
> Now using node v4.4.7 (npm v2.15.8)
> 2016-09-30 13:38:46 ENiGMA½ is already installed in /root/enigma-bbs, trying to update using git
> 2016-09-30 13:38:46 Installing required Node packages
> 
> > farmhash@1.2.1 install /root/enigma-bbs/node_modules/farmhash
> > node-gyp rebuild
> 
> gyp ERR! configure error
> gyp ERR! stack Error: EACCES, mkdir '/root/enigma-bbs/node_modules/farmhash/build'
> gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
> gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
> gyp ERR! cwd /root/enigma-bbs/node_modules/farmhash
> gyp ERR! node -v v0.10.46
> gyp ERR! node-gyp -v v0.10.6
> gyp ERR! not ok
> 
> > ptyw.js@0.5.0 install /root/enigma-bbs/node_modules/ptyw.js
> > node-gyp rebuild
> 
> gyp ERR! configure error
> gyp ERR! stack Error: EACCES, mkdir '/root/enigma-bbs/node_modules/ptyw.js/build'
> gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
> gyp ERR! command "node" "/usr/bin/node-gyp" "rebuild"
> gyp ERR! cwd /root/enigma-bbs/node_modules/ptyw.js
> gyp ERR! node -v v0.10.46
> gyp ERR! node-gyp -v v0.10.6
> gyp ERR! not ok
> 
> > spawn-sync@1.0.15 postinstall /root/enigma-bbs/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> > node postinstall
> 
> -
> module.js:340
>     throw err;
>           ^
> Error: Cannot find module '/root/enigma-bbs/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync/postinstall'
>     at Function.Module._resolveFilename (module.js:338:15)
>     at Function.Module._load (module.js:280:25)
>     at Function.Module.runMain (module.js:497:10)
>     at startup (node.js:119:16)
>     at node.js:945:3
> 
> > sqlite3@3.1.4 install /root/enigma-bbs/node_modules/sqlite3
> > node-pre-gyp install --fallback-to-build
> 
> node-pre-gyp ERR! Tried to download(undefined): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.1.4/node-v11-linux-x64.tar.gz
> node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.4 and node@0.10.46 (node-v11 ABI) (falling back to source compile with node-gyp)
> gyp ERR! configure error
> gyp ERR! stack Error: EACCES, mkdir '/root/enigma-bbs/node_modules/sqlite3/build'
> gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v11-linux-x64"
> gyp ERR! cwd /root/enigma-bbs/node_modules/sqlite3
> gyp ERR! node -v v0.10.46
> gyp ERR! node-gyp -v v0.10.6
> gyp ERR! not ok
> node-pre-gyp ERR! build error
> node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v11-linux-x64' (1)
> node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
> node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
> node-pre-gyp ERR! stack     at maybeClose (child_process.js:766:16)
> node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:833:5)
> node-pre-gyp ERR! System Linux 2.6.32-573.3.1.el6.x86_64
> node-pre-gyp ERR! command "node" "/usr/bin/node-pre-gyp" "install" "--fallback-to-build"
> node-pre-gyp ERR! cwd /root/enigma-bbs/node_modules/sqlite3
> node-pre-gyp ERR! node -v v0.10.46
> node-pre-gyp ERR! node-pre-gyp -v v0.6.30
> node-pre-gyp ERR! not ok
> Failed to execute '/usr/bin/node /usr/lib/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v11-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v11-linux-x64' (1)
> npm ERR! Linux 2.6.32-573.3.1.el6.x86_64
> npm ERR! argv "/root/.nvm/versions/node/v4.4.7/bin/node" "/root/.nvm/versions/node/v4.4.7/bin/npm" "install"
> npm ERR! node v4.4.7
> npm ERR! npm  v2.15.8
> npm ERR! code ELIFECYCLE
> 
> npm ERR! farmhash@1.2.1 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the farmhash@1.2.1 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the farmhash package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs farmhash
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls farmhash
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/enigma-bbs/npm-debug.log
> 2016-09-30 13:38:46 ERROR: Failed to install ENiGMA½ npm packages. Please report this!
```

**Comment by NuSkooler** [comment]
Hi @gnh1201! 

Take a look at some of the errors you're getting. For example:
```gyp ERR! stack Error: EACCES, mkdir '/root/enigma-bbs/node_modules/sqlite3/build'```

This is a bit odd seeing that you appear to be running as root. In any case, looks like you're getting a lot of `EACCES` errors from your system.

Question: What flavor of *nix is this? (`uname -a`)

Some suggestions:
1. Delete the existing `enigma-bbs` directory. 
2. If you have Node.js installed *outside of NVM* remove it. Let NVM manage it (e.g. what the install script is attempting to do)
3. Really, you shouldn't be running a service -- especially a Internet facing service such as a BBS -- as root. Try creating a new user on your system (you can add it to your sudoers file so you have `sudo` access) and running the `install.sh` script there.

If you still have issues please post back. We'll get you going!

**Comment by gnh1201** [comment]
Thanks for your answer.
I retry install nvm/npm and node-gyp.

First, It is result of execute command 'uname -a':
> [root@localhost enigma-bbs]# uname -a
> Linux localhost.localdomain 2.6.32-573.3.1.el6.x86_64 #1 SMP Thu Aug 13 22:55:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Second, Try check command 'node' and 'node-gyp' and 'npm install'
> [root@localhost enigma-bbs]# node
> > .exit
> [root@localhost enigma-bbs]# node-gyp
> 
>   Usage: node-gyp <command> [options]
> 
>   where <command> is one of:
>     - build - Invokes `make` and builds the module
>     - clean - Removes any generated build files and the "out" dir
>     - configure - Generates a Makefile for the current module
>     - rebuild - Runs "clean", "configure" and "build" all at once
>     - install - Install node development files for the specified node version.
>     - list - Prints a listing of the currently installed node development files
>     - remove - Removes the node development files for the specified version
> 
> node-gyp@3.4.0  /root/.nvm/versions/node/v4.4.0/lib/node_modules/node-gyp
> node@4.4.0
> [root@localhost enigma-bbs]# npm install
> 
> > farmhash@1.2.1 install /root/enigma-bbs/node_modules/farmhash
> > node-gyp rebuild
> 
> sh: node-gyp: command not found
> 
> > ptyw.js@0.5.0 install /root/enigma-bbs/node_modules/ptyw.js
> > node-gyp rebuild
> 
> sh: node-gyp: command not found
> \
> > spawn-sync@1.0.15 postinstall /root/enigma-bbs/node_modules/inquirer/node_modules/external-editor/node_modules/spawn-sync
> > node postinstall
> 
> sh: node: command not found
> 
> > sqlite3@3.1.4 install /root/enigma-bbs/node_modules/sqlite3
> > node-pre-gyp install --fallback-to-build
> 
> /usr/bin/env: node: Permission denied
> npm ERR! Linux 2.6.32-573.3.1.el6.x86_64
> npm ERR! argv "/root/.nvm/versions/node/v4.4.0/bin/node" "/root/.nvm/versions/node/v4.4.0/bin/npm" "install"
> npm ERR! node v4.4.0
> npm ERR! npm  v2.14.20
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> 
> npm ERR! farmhash@1.2.1 install: `node-gyp rebuild`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the farmhash@1.2.1 install script 'node-gyp rebuild'.
> npm ERR! This is most likely a problem with the farmhash package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs farmhash
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!
> npm ERR!     npm owner ls farmhash
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/enigma-bbs/npm-debug.log

How can I do?

**Comment by NuSkooler** [comment]
@gnh1201 I should have asked before - what distro of Linux is this? 

Did you try steps 1-3 above? Your logs do not indicate that + you appear to still be root and getting permission issues. I'll try to make better steps -- including manual installation:

1. *delete* your current `enigma-bbs` directory
2. If you've installed Node.js via a package manager (e.g. `apt-get` please remove it. For apt, it would be `sudo apt-get remove node` generally)
3. Create yourself a new user to run under (depending on your distro this may vary)
4. Log out of root and log in to this new user from step (3)
5. Run `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash`
6. Run `nvm install 4` (this should give you the latest 4.x)
7. Validate node install: `node --version` (again, should be 4.x)
8. `cd` to the directory you want to place ENiGMA½ such as `/home/yournewuser/`
9. Run `git clone https://github.com/NuSkooler/enigma-bbs.git`
10. `cd enigma-bbs`
11. Run `npm install`

Please capture the log from the above commands. If something goes wrong, perhaps we can find more details that way.

**Comment by NuSkooler** [comment]
Marking closed due to inactivity + previous notes about root permissions. Feel free to create a new issue if future problems occur.
