### ISSUE TITLE
FTN PKT files need to be uppercase

### ISSUE THREAD

**Issue by XBessa** [NuSkooler/enigma-bbs#103]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
I am experiencing issues with my FIDONET hub. He runs an old Fastecho system with original PKZIP, hence he supports only packet files into uppercase. Enigma is sending files using lowercase, therefore he rejects the packets when using PKUNZIP. 

Can we have a switch to generate the .PKT files (and its bundles *.TU?, *.WE?, etc) into uppercase?

**Environment**
- [X] I am using Node.js v4.x or higher
- [X] `npm install` reports success
- Actual Node.js version (`node --version`): v4.4.0
- Operating system (`uname -a` on *nix systems): Linux ip-172-31-26-239 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`):0a98ce6

Please let me know if further information is required.

**Comment by NuSkooler** [comment]
@XBessa Sounds reasonable and should be fairly easy to achieve. I'll look into this hopefully tonight.

**Comment by NuSkooler** [comment]
This should be resolved @ 6f3fe7c52de27bdcbc40275f1165de875cc60ee7. I don't have a way to fully test this at the moment, but I stepped through the code and it seems good. Can you give it a try and let me know if this works for you?

The default remains to create lower case filenames (I don't want to break anyone). To override this, set `fileCase` to `upper` in a node's configuration. Example:

```
scannerTossers: {
	ftn_bso: {
		// ...
		nodes: {
			"46:1/100" : {
				archiveType: ZIP
				fileCase: upper
			}
		}
	}
}
```

**Comment by XBessa** [comment]
Sure! I'll test tonight and let you know. Thank you!

2016-12-07 1:54 GMT-02:00 Bryan Ashby <notifications@github.com>:

**Comment by NuSkooler** [comment]
@XBessa Did this work for you? I'm assuming no response is good...

**Comment by XBessa** [comment]
It worked flawlessly! Many thanks!!

Em seg, 13 de fev de 2017 às 22:20, Bryan Ashby <notifications@github.com>
escreveu:
