### ISSUE TITLE
Crash on Telnet Bridge connecting to Tradewars server

### ISSUE THREAD

**Issue by apamment** [NuSkooler/enigma-bbs#105]
I've fixed this bug, and will attach a patch. Not sure if it's correct or not, but it works.
[areyouthere.txt](https://github.com/NuSkooler/enigma-bbs/files/795251/areyouthere.txt)

For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
Enigma crashes when trying to connect to a tradewars server
**Environment**
- [X] I am using Node.js v6.x or higher
- [X] `npm install` reports success
- Actual Node.js version (`node --version`): v6.10.0
- Operating system (`uname -a` on *nix systems): Linux zatanna.andrew.homeunix.org 3.10.0-514.6.1.el7.x86_64 #1 SMP Tue Jan 17 11:12:41 CST 2017 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`): 3f873f5

**Expected behavior**

Should connect to TWGS

**Actual behavior**

Crashes

**Steps to reproduce**
Attempt to connect to tradewars game server

**Comment by NuSkooler** [comment]
Thanks for the patch! Merged @ 9bb28b36cd8e48dae133005157d68cb52c3792be
