### ISSUE TITLE
How to customize ANS?

### ISSUE THREAD

**Issue by gnh1201** [NuSkooler/enigma-bbs#112]
Hello. enigma-bbs is so good project.

I want customize enigma-bbs's theme. but I do not know how to write new ANS file.
Can I get hints?

**Comment by NuSkooler** [comment]
@gnh1201 Thanks for trying out ENiGMA!

The best way to go about customizing your board's theme(s) is to create a new theme. You can start out by copying the directory `mods/themes/luciano_blocktronics` to a new directory, e.g. `mods/themes/my_board_theme`. From there, use a ANSI editor such as PabloDraw (Windows) or ACiDDraw (DOS) to create/edit the ANS files. You'll also want to adjust the `theme.hjson` file in the same directory to reflect the name of your theme and other theme-related options.

You can also disable the `luciano_blocktronics` theme if you only want yours to show/be available.

Poke around in the enigma `docs` folder for a little more info. Themes is definitely something that needs some good docs :)

**Comment by gnh1201** [comment]
Thanks for your answer.

I have additional question. PabloDraw does not support 'draw by pen(or similar) tool'.
so, I think try convert image to ansi tool.

but, I do not know properly canvas size for draw ANSI art.
What is properly canvas size for draw ANS?

**Comment by gnh1201** [comment]
I did try ANS editing [tools.](url)
It have a little bugs. I want find stable editor. Can I find it?

**Comment by NuSkooler** [comment]
@gnh1201 Did you try PabloDraw? That's probably the most popular for Windows. For DOS or DOS emulation, try ACiDDraw. There are also some online tools.

Generally 80x25 max, 79x24 to be safe for "DOS" screens.
