### ISSUE TITLE
Content Server Crash on this.accessDenied

### ISSUE THREAD

**Issue by apamment** [NuSkooler/enigma-bbs#117]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
When trying to access the content server it crashes saying "this.accessDenied" is not a function
**Environment**
- [X] I am using Node.js v6.x or higher
- [X] `npm install` reports success
- Actual Node.js version (`node --version`): 6.11.0
- Operating system (`uname -a` on *nix systems): Linux vps74123 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`): d92b8e6

I've moved my enigma bbs over to an Ubuntu VPS and I've been trying to set up the password forgot feature, I've got it to send the email, but when I click the link, I get this:
```
/home/andrew/enigma-bbs/core/servers/content/web.js:161
                return route ? route.handler(req, resp) : this.accessDenied(resp);
                                                               ^

TypeError: this.accessDenied is not a function
    at Server.routeRequest (/home/andrew/enigma-bbs/core/servers/content/web.js:161:50)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:546:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
```

**Comment by NuSkooler** [comment]
I'll try to look at this tonight. Another where I'm not sure how I haven't seen it, but I see the issue. We probably just need to `.bind(this)` the routeRequest() handler.

**Comment by NuSkooler** [comment]
Are you accessing this via HTTPS?

**Comment by apamment** [comment]
yes

**Comment by NuSkooler** [comment]
If you don't mind, try changing line ~119 from this:
```this.httpsServer = https.createServer(options, this.routeRequest);```

to this:
```
this.httpsServer = https.createServer(options, (req, resp) => this.routeRequest(req, resp));
```

**Comment by apamment** [comment]
it worked ! thanks :D

**Comment by NuSkooler** [comment]
Sweet, pushed to master @ https://github.com/NuSkooler/enigma-bbs/commit/7c81cbed515c55686ffd33c224465c625993e716
