### ISSUE TITLE
Add support for NetMail

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#121]
Meta issue for NetMail and related (AreaFix, Nodelists, etc.)

**Current thoughts**:
* User to user NetMail will utilize the internal "private" message area tag
* When sending a private mail, if the user type a username@FTN_style_address, the system will validate that the address appears sendable and moves on
* An explicit "Send NetMail" option will allow for entering in a user name, then search for an address. Search will span across board names, addresses, sysop names, etc. -- information found in nodelists
* Configuration for nodelists will be put in place. The system will merge in nodelists / diffs to the internal SQLite DB for searches / resolution

**Various specs**:
* [FTS-5000: The Distribution Nodelist](http://ftsc.org/docs/fts-5000.005)
* [FTS-4009: Netmail tracking (Via)](http://ftsc.org/docs/fts-4009.001)
* [FTS-5002: Pointlist Formats](http://ftsc.org/docs/fts-5002.002)
* [FTS-5000.002: The Distribution Nodelist](http://ftsc.org/docs/old/fts-5000.002)
* [FTS-5001: Nodelist flags and userflags](http://ftsc.org/docs/fts-5001.006)
* [FTS-5004: DNS Distributed Nodelist](http://ftsc.org/docs/fts-5004.001)
* [FSC-0055: Security Passwords in Nodelist Update Files](http://ftsc.org/docs/fsc-0055.001) (Proposal)
* [FSC-0076: NetMail Area Tags](http://ftsc.org/docs/fsc-0076.001) (Proposal)

**AreaFix & FileFix**:
* http://www.skepticfiles.org/moretext/areamgr.htm

**Comment by davestephens** [comment]
Sounds pretty sane to me!

Nice to have, but it would be good to be able to browse and search nodelists from a specific menu command.

**Comment by NuSkooler** [comment]
> Nice to have, but it would be good to be able to browse and search nodelists from a specific menu command.

Can you elaborate? What what purpose(s)?

**Comment by davestephens** [comment]
Nothing fancy, just the ability to browse and search the nodelist. E.g, I'd have a main menu idem "NODE", when pushed takes me to a scrolly thing that lets me browse up/down through the list, and allows a keyword search.

Ideal for moments when you know a BBS name but not the FTN address!

**Comment by NuSkooler** [comment]
This is now partially in:
* oputil.js mb areafix ... for sending AreaFix to a HUB
* Can send directly from personal box by addressing to a foreign user and <address>, e.g. "Joe User <1:123/123>" or "Joe User @ 1:123/123"

Currently there are some bugs with non-HUB NetMail that are being worked out in 0.0.9-alpha & may end up being backported. Will likely include the explicit "Send NetMail" type option and Nodelist browsing in this version as well.

**Comment by NuSkooler** [comment]
NetMail that is routed through another node (e.g. a HUB) is now fixed. Nodelist browsing is still on the list for 0.0.9-alpha.

**Comment by NuSkooler** [comment]
Nodelist browser specifics @ #221. Closing this as NetMail is usable.
