### ISSUE TITLE
ENiGMA ignores mail watch file if it existed before ENiGMA was started

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#122]
**Short problem description**
ENiGMA doesn't start processing mail in the incoming directory, if the mail watch file existed before ENiGMA was started

**Environment**
- I am using Node.js v6.11.3
- `npm install` reports success
- Linux pi-bbs 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux
- Revision bbd5ff7

**Expected behavior**
ENiGMA should start processing when it starts up, if a toss.now/watch file file exists

**Actual behavior**
ENiGMA starts processing mail when you touch the watch file, ie `touch /<path_to_watch_file>'

**Steps to reproduce**
- Stop ENiGMA
- Run binkd to import some mail and generate a watch/toss.now file
- Start ENiGMA
- Wait....

**Comment by NuSkooler** [comment]
Thanks for the report -- I'll look into this a bit tonight.

**Comment by NuSkooler** [comment]
Switched to sane over gaze for watch files. Gaze was not picking up any file additions (e.g. if watch file didn't exist at startup, or was ever removed, it would not trigger when (re)created). Also added in functionality to check for file @ startup. If it's there, the event will fire.

**Comment by NuSkooler** [comment]
(You'll need to run yarn or npm install after pulling)

**Comment by davestephens** [comment]
Nice one, will test ASAP!
