### ISSUE TITLE
Terminal emulation recognition 

### ISSUE THREAD

**Issue by danger89** [NuSkooler/enigma-bbs#131]
**Short problem description**
I would like to see that the terminal emulation is recognized, when ASNI is not possible or limited, to switch over a good working alternative (eg. ASCII).

**Expected behavior**
Always a working BBS

**Actual behavior**
Login screens unusable/hangs/slow in Shellinabox with qodem. 
Using telnet Enigma not useful at all.

**Steps to reproduce**
Just use telnet. Or syncterm/qodem while using Shellinabox (I need Shellinabox to work around a proxy).

**Comment by NuSkooler** [comment]
Pure ASCII support is of course possible, but not simple at all in Enig since nearly everything relies on ANSI ESC sequences.

I've not used Shellinabox (I'll try it out), but I do regularly use `telnet`. It depends on the terminal itself though. For example on most Linux distros it's fine, but OS X Terminal.app it is not (lacks some essential ESC seqs); iTerm2 works better in that case.

**Comment by NuSkooler** [comment]
Looking at Shellinabox and closer at the description here, it sounds like this is two issues:

1.  A request for pure ASCII support
2.  A request to add support for Shellinabox et. al.

(1) Quite a bit would have to go into making Enig support pure ASCII -- not limited to creating some input handlers (Enigma uses views, but you could probably create a "dumbed" down version) to use in ASCII mode, creating an ASCII only theme, and adding a little simple logic to switch to it when ANSI is not available. Most of this is out of the current "spirit" of what I'm going for, but I'll be happy to accept PR's and help guide in development.

(2) Again around ANSI ESC sequences. ANSI-BBS compatible terminal is required. Plain ol `telnet` is fine, but you need to run it in a terminal that can handle it. I've tried Qodem and can't figure out why people use it for BBSs honestly. SyncTERM, NetRunner, EtherTerm, iTerm2 + telnet, most LInux terms + telnet, VTX, fTelnet, etc. all work fine.

**Comment by davestephens** [comment]
This isn't worth putting effort into IMO; given that BBSing is pretty niche, it's reasonably safe to say that people that are into it are going to use a proper telnet client that supports ANSI - and if they're not, they should be :-)

**Comment by danger89** [comment]
you are right.
