### ISSUE TITLE
Chat feature

### ISSUE THREAD

**Issue by danger89** [NuSkooler/enigma-bbs#132]
**Short problem description**
I like to have a chat feature and instant messaging.

**Expected behavior**
Chat with people via BBS. And send messages (PMs), also directly to SysOp in in case of emergency.
See Mystic BBS for what I mean.

**Actual behavior**
No chat or PM's possible afaik.

**Comment by NuSkooler** [comment]
RE Chat: You're talking group chat? There is a mod that allows this for between Enig boards. Mystic Relay Chat (MRC) would be easy to port to allow between the two. The problem I see with both is they are board specific. Building one based on IRC, Discourse, or Slack may be an option. Or better (IMO) a fully decentralized.

For user-to-user messaging: This would be slick and easy to do!

**Comment by danger89** [comment]
Yea first begin with user to user. Later you can add group chat within 1 board. And finally decentralized /multi board..

**Comment by NuSkooler** [comment]
I'm considering a simple user-to-user "Instant Message" for users on the board. Any group chat (chat rooms) will be implemented via mods.

**Comment by NuSkooler** [comment]
Some updates:
- A [node_msg](https://github.com/NuSkooler/enigma-bbs/blob/0.0.9-alpha/core/node_msg.js) module has been added that allows to send messages to all nodes or specific users.
- The issue with "Send to +op" is there is no current WFC, so if op isn't online at the time it's currently a no-go. See #216.
- One _could_ implement a mod to send a message to +op via <fill in whatever is convenient> (Slack, Discord, whatever).

See also #217 for some updates to `node_msg`.

Closing this one now that some of the stuff is in + issues logged for specifics such as #218.
