### ISSUE TITLE
Question: Easy way to turn of the animations?

### ISSUE THREAD

**Issue by danger89** [NuSkooler/enigma-bbs#134]
Currently there are a lot of ASNI animations in between. A bit overkill sometimes. Which results is a low connection when using remote terminals....

Are there easy ways to limit the amount of ANSI arts/animations.. etc?

Regards,
Melroy

**Comment by NuSkooler** [comment]
I'm not aware of any ANSImation in the default `luciano_blocktronics` theme -- do you have specifics?

At any rate, themes are something left to the operator: You can build your own from scratch or use the default `luciano_blocktronics` set as a base to modify from. All artwork, colors, placement, menu ordering, and so on is already fully configurable.

**Comment by danger89** [comment]
I think this is also related to Shellinabox. Where as I easily could create new accounts by other BBS system with syncterm within Shellinabox. In this case the default login didn't work as expected.

Like arrow up/down didn't work well. And the text (login/apply/..) not always put correctly on the right location etc.

**Comment by davestephens** [comment]
PabloDraw is definitely the ANSI editor of choice on Linux, works pretty well for me.

I'm not familiar with syncterm or shellinabox, but I use Netrunner or the vtx web client and both work perfectly. Check out my vtx setup (https://bbs.force9.org/vtx/force9.html) or @nuskooler's one at https://l33t.codes/vtx/xibalba.html

**Comment by davestephens** [comment]
I've just looked at shellinabox, what problem are you trying to solve by using it?

**Comment by danger89** [comment]
Hey Dave. Thanks for your replies.
I think PabloDraw is indeed the only way to go forward. 

@davestephens 
I can't connect to your bbs.force9.org BBS somehow. It looks like its blocking? I don't get it both my desktop as my server (2 different locations within The Netherlands). Force9 only connects on my Android phone (4G network).
See vid:
![force9_doesnt_work](https://user-images.githubusercontent.com/628926/32144933-e8bb1f8a-bcc0-11e7-9e0a-97823d03c48b.gif)

I'm trying to solve the following... This is shellinabox on my server (Debian). In Telnet the menu doesn't work:
![telnet_via_shellinabox](https://user-images.githubusercontent.com/628926/32144946-2275665e-bcc1-11e7-8f77-382f92ac416a.gif)

Shellinabox + syncterm is pretty funny (ASCII fallback?):
![lol_ascii](https://user-images.githubusercontent.com/628926/32144967-4bd673ee-bcc1-11e7-914f-b1fe29530dbc.gif)

**Comment by davestephens** [comment]
Something weird happened with my dynamic DNS provider last night, not sure what, but that IP you have is not my current one. Anyway, it should be resolved soon!

Why is it that you're using shellinabox? Why not just use something like Netrunner natively on your local os? Shellinabox seems like an unnecessary layer of abstraction which is only causing you problems :-)

**Comment by danger89** [comment]
@davestephens  I'm sometimes behind proxy servers/firewalls... :rofl:  That is why..

Which wine version do you use? I have troubles using it when I press the 'edit' button.

![wine_problems](https://user-images.githubusercontent.com/628926/32145409-779430e6-bcc8-11e7-97aa-1aa080a00316.gif)

**Comment by davestephens** [comment]
Re shellinabox, I have to be honest, it seems like you're trying to fix a strange use case in the wrong place. 

Re PabloDraw, wine isn't required. Use mono with the windows build (it's doc'd on the PabloDraw website).

Good luck!

**Comment by danger89** [comment]
@davestephens Yea I got some problems with installing an old version of mono on Linux mint 10 (xenial based). I just switched to wine 32bit, using wine 32bit arch. And installed .NET 4.0 via winetricks:
```
WINEPREFIX="$HOME/prefix32" WINEARCH=win32 wine wineboot
env WINEARCH=win32 WINEPREFIX="$HOME/prefix32" winetricks dotnet40
```
Works very well. No ** mono. I beat the documentation on their site..
![working_pablodraw](https://user-images.githubusercontent.com/628926/32145763-caa631bc-bccd-11e7-8f01-b33bfd8b7f42.gif)

**Comment by davestephens** [comment]
Well it obviously doesn't work THAT well if you can't edit ANSIs :-D

I used to use PabloDraw with mono + xenial with no issues (installed mono-complete from the Ubuntu repos, mono on its own didn't work from memory) - so not sure what issue you're running into. I'm now on zesty and that also works fine with no wine.

**Comment by NuSkooler** [comment]
@danger89 As Dave said, PabloDraw works in Linux with Mono. I don't know the specifics of installing Mono for your particular Linux, but I'm sure it's possible -- just Google around.

RE ANSI issues: You need an ANSI-BBS compatible *terminal*. It appears that Shellinabox is not. Your funny characters are probably just the wrong emulation (I bet Shellinabox is set to UTF-8 but being detected as CP437). Look for a `TERM` environment variable/setting and try setting it to `xterm` or `utf8` for example, or alternatively, set the terminals encoding to `cp437`.

In the end you need an ANSI-BBS terminal. There are plenty to choose from. If you need a proxy, I'm sure there are alternatives there as well.

**Comment by danger89** [comment]
It's already set on `xterm`, and it the other settings don't make it really better. Well forgot about shellinabox, I think I'm the only one using it to pass around proxy/firewalls.

**Comment by NuSkooler** [comment]
@danger89 I think this issue can be closed then, is that right?

**Comment by danger89** [comment]
Yea I think so, if you don't find ascii support important or needed.
