### ISSUE TITLE
Migrate to Node 8.x

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#139]
Given the advances in Node 8.x and the level of coverage supported for ES2017 already available (async functions, etc), how do you feel about updating some of the modules... was thinking on working through some of this if you'd be agreeable to it.

Namely pulling out a lot of the use of the async library in favor of async functions, promises etc... also as a path towards bumping out a web client.

**Comment by NuSkooler** [comment]
Node.js 8.x LTS is in my sights for `0.0.9-alpha` or higher. However, `async` and waterfalls/similar will probably stay for quite some time. The state of async/await and promises is *still* a bit in flux, not all libraries support them yet, etc. 

async/await is not too bad. Promises however, are a hack in my opinion.

What do you mean by web client? A lot of "web" proposals seem very out of scope for a BBS.

**Comment by tracker1** [comment]
async/await rely on promise behavior under the covers... async functions return a promise, and await will await resolution of a promise.  Most behaviors can be wrapped, and *many* libraries now have "async" interfaces that use promises.

I mean exposing enough of the system via API for being able to sign up, login and access at the very least message bases, and/or eventually be able to use a web terminal to go straight into a door.

**Comment by NuSkooler** [comment]
> async/await rely on promise behavior under the covers.

Right, I'm referring to `then()...then()...` hell vs modern `async` and `await`.

> I mean exposing enough of the system via API for being able to sign up, login and access at the very least message bases, and/or eventually be able to use a web terminal to go straight into a door.

You can do this now. https://xibalba.l33t.codes/. Have you tried it? This keeps it as a BBS, but adds some modern tweaks such as hyperlinks. You've asked before about furthering a web interface (e.g. web message access), but that remains outside the scope of ENiGMA. You're of course welcome to either a) fork, or b) create *modules* that add support for such things and submit PR's

**Comment by tracker1** [comment]
Will try it when I get home, most websockets are blocked at work.

**Comment by NuSkooler** [comment]
0.0.9-alpha is now on 8.x LTS
