### ISSUE TITLE
Corrupt display of many .txt files

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#14]
Display of .txt files can be broken. For example, Amiga Collys's do not wrap properly.

**Comment by tracker1** [comment]
Set your `.gitattributes` so that txt and ans files are set to PC crlf, that's probably the issue... Check that config into the project and fix the line endings and check in the changes...

https://github.com/bbs-io/synchronet-simplicity-shell/blob/master/.gitattributes

**Comment by NuSkooler** [comment]
@tracker1 Good point about the LF's. My tests fail with files that have not yet been processed by Git, but it's from Linux so still likely a issue. In any case, .gitattributes for proper CRLF sound like a good idea.

**Comment by NuSkooler** [comment]
I think this is/was just a line ending issue. I snagged a couple collys from textmod.es + set the font in `menu.hjson` and they look great:

![colly1](https://cloud.githubusercontent.com/assets/1509339/11319770/d44b0092-903f-11e5-882c-044cfc03d691.png)

![colly2](https://cloud.githubusercontent.com/assets/1509339/11319771/d9a48310-903f-11e5-91e1-2096a6d01b5b.png)

Leaving open until I create a proper `.gitattributes` to keep files safe.

**Comment by NuSkooler** [comment]
Added `.gitattributes`. Closing as this appears to be OK
