### ISSUE TITLE
Extended pipe code backgrounds don't work (|24 -  |31) as expected

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#146]
Colour codes |24-|31 display the "normal" colours and not the brighter iCE colours

Running latest ENiGMA as of last night (commit 7555233)

**Expected behavior**
Would expect |24-|31 to set the background to the brighter iCE background colours 

**Actual behavior**
|24-|31 behave the same as |16-|23 - ie not iCE colours, just 'normal' background colours. Is it setting the text foreground in error?? Difficult to test all combos - blue certainly seems to do that (see screenie below)

**Steps to reproduce**
Load the new rumour screen, type in |25DAVEDAVEDAVE and observe how the background is dark blue in the preview below, not light blue as expected. :)

![image](https://user-images.githubusercontent.com/668464/35833506-7fcca9f6-0ac9-11e8-87de-a39280b929da.png)

**Comment by NuSkooler** [comment]
I should really drink more caffeine or something. Was sure I tested it, but the code clearly shows I did not. Now properly setting the 'blink' attribute which in iCE mode, shows bright backgrounds.

**Comment by davestephens** [comment]
Boom! I can finish the colour code docs in working on now :-)
