### ISSUE TITLE
Databases not initialized on first run

### ISSUE THREAD

**Issue by mattkammersell** [NuSkooler/enigma-bbs#15]
I got it going but had to read through the source a bit to see the folder, just had to create the db folder (also the logs folder) but the db part wasn't super-clear when the error was thrown.  

coruscant:enigma-bbs matt$ node main.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_CANTOPEN: unable to open database file
    at Error (native)

**Comment by NuSkooler** [comment]
Is this just a case of the directories not existing then?

First startup should probably attempt to create everything in Config.paths if they don't already exist.

**Comment by NuSkooler** [comment]
Should now be resolved with 4d40fe0
