### ISSUE TITLE
Message counter broken in message list

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#150]
Am happy to fix this one...just logging so it's here! :)

**Short problem description**
Message counter in message area list (ie 46 / 500) doesn't display

**Environment**
Enigma latest, although has been broken for a while

**Expected behavior**
To see something like 50/500 and update live when scrolling through messages

**Actual behavior**
Nothing displays

**Steps to reproduce**
View a list of messages in a message area

**Comment by NuSkooler** [comment]
FWIW, it the default `MSGLIST.ANS` just has the wrong MCI. However, this should be fixed using the newer `populateCustomLabels()` method and "custom ranges" (search code for `customRangeStart` for examples) vs the current system in place. That way, it's not a message counter, it's just a custom formatted MCI that can be whatever the op wants (or at least that is allowed via the format object)

**Comment by davestephens** [comment]
Thanks, will check out the code. 

The correct MCI codes don't work either - it doesn't work even with the correct codes!

**Comment by davestephens** [comment]
See #151 :+1:

**Comment by davestephens** [comment]
Fixed in #153 and merged.
