### ISSUE TITLE
Crash on configuration when theme no longer exists

### ISSUE THREAD

**Issue by Jasin2069** [NuSkooler/enigma-bbs#157]
I renamed a theme I am working on. I changed the default and prelogin themes to match. I logged in fine and was able to use the theme. When I press c to configure the user and switch themes it instantly crashes. Most likely trying to set the theme from the users database. If it isn't found it should show one of the available themes.

I fixed this by making a copy of the directory with the old name so I could switch my user to something else first then removing the copy.

assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at SpinnerMenuView.updateSelection (D:\enigma\core\spinner_menu_view.js:31:3)
    at SpinnerMenuView.setFocusItemIndex (D:\enigma\core\spinner_menu_view.js:70:7)
    at populateViews (D:\enigma\core\user_config.js:199:18)
    at D:\enigma\node_modules\async\dist\async.js:3866:24
    at replenish (D:\enigma\node_modules\async\dist\async.js:998:17)
    at iterateeCallback (D:\enigma\node_modules\async\dist\async.js:983:17)
    at D:\enigma\node_modules\async\dist\async.js:958:16
    at D:\enigma\node_modules\async\dist\async.js:3871:13
    at prepareAvailableThemes (D:\enigma\core\user_config.js:181:7)
    at D:\enigma\node_modules\async\dist\async.js:3866:24

**Expected behavior**
revert to default or first found theme
**Actual behavior**
crahes
**Steps to reproduce**
Rename a folder in art that a user has selected then login with them and go to config menu

**Comment by NuSkooler** [comment]
@Jasin2069 Thanks for reporting this and the others you're finding - this is very helpful. I'll try to get some of these crashes cleaned up tonight.

**Comment by NuSkooler** [comment]
Fixed in `0.0.9-alpha` branch. Let me know if you need this immediately in `0.0.8-alpha`.

**Comment by Jasin2069** [comment]
No, I don't. Planning to upgrade to 0.0.9 anyways. Thanks!
