### ISSUE TITLE
Suggestion - Break up Menu file

### ISSUE THREAD

**Issue by SemperFu** [NuSkooler/enigma-bbs#158]
The menu file being 3800 lines I think it would be better to split them out a little bit and call them like you do the menu file from options "general: { menuFile: "sick_board.hjson" } "

This would be a little easier to work with and update the various changes as new versions come. Suggest something like this

```
Mainfile - Just a Skeleton 
     -Login/Matrix
     -MainMenu
     -Doors
     -Messages/Mail
     -Filebase
```

**Comment by NuSkooler** [comment]
Current plan for this on my ToDo has been to create a include system. I think it may be discussed in some issues here as well. I'll let this become the official ticket for that.

The general idea is to have e.g. `myboard.hjson` which can include others:
```
{
  include: [
    "login.hjson"
    /* ... */
  ]
}
```

**Comment by NuSkooler** [comment]
See #220. Leaving this issue as the work do actually break up appropriately once it's possible.

**Comment by NuSkooler** [comment]
To be tracked in  #280
