### ISSUE TITLE
DOS Door Support

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#16]
Door support is an essential feature... I've looked into it a little bit... My plan was to make a separate door runner server... But worth mentioning dosemu for Linux and dosbox/vdos for elsewhere.

Glad to see you working in this... My efforts aren't as far along at all.

**Comment by NuSkooler** [comment]
Door support works already via DOSEMU in Linux. I haven't yet looked into DosBox or the like under other platforms -- as long as they can support a virtual COM port, it should be OK.

Here is a menu.hjson entry for LORD:
doorLORD: {
			desc: Playing L.O.R.D.
			module: abracadabra
			config: {
				name: LORD
				dropFileType: DOOR
				cmd: /usr/bin/dosemu
				args: [
					"-quiet", "-f", "/home/nuskooler/DOS/X/LORD/dosemu.conf", "X:\\LORD\\START.BAT {node}"
				]
			}
		}

**Comment by NuSkooler** [comment]
Closing this bug since there already is door support. Please open bugs for specifics (Door support on Windows, other systems besides DOSEMU, etc. if any are found to not already function or need work)
