### ISSUE TITLE
Windows door support (Question)

### ISSUE THREAD

**Issue by SemperFu** [NuSkooler/enigma-bbs#163]
I see #30 was closed. Is QEMU the only way to run a door game in windows? I have a Windows 10 x86 box since it can run 16bit programs natively. With MysticBBS it uses a windows fossil driver netfoss (http://pcmicro.com/netfoss/). 

You send the node, handle, and port. I tried using the same setup with socket but there is no handle tag stried using  the port. I just get a black screen for a little bit. I see netfoss running during that time too. 
If it's not possible this can be closed but would be nice to see if I can use doors natively.

**Comment by NuSkooler** [comment]
Under Windows you have pretty much the same options as Linux:

- Run something native (e.g. 32 or 64 bit Windows binary) that can read/write stdio (console app essentially)
- Again native, but something that can do I/O over a socket (in which you use the socket option mentioned in #30)
- Use DOSBox, QEMU, etc. 
- Older 32bit Windows can run 16 bit executables
- Not sure if this ever made it anywhere: https://hackernoon.com/win3mu-part-1-why-im-writing-a-16-bit-windows-emulator-2eae946c935d

See also https://www.hanselman.com/blog/RunningBBSDoorGamesOnWindows10WithGameSrvDOSBoxPlusTelnetFunWithWSL.aspx

**Comment by Jasin2069** [comment]
So I am running a 32 bit windows that has 16 bit support and am using netfoss for the fossil driver over socket. This is working fine with Mystic BBS. I'm just getting a black screen and I wanted to make sure that engima should be able to support it as well.

**Comment by NuSkooler** [comment]
It should work fine - are you using the `socket` option in ENiGMA for your abracadabra config? If also using `DOOR32.SYS` dropfile type, I may need to resolve a TODO there for you.

**Comment by Jasin2069** [comment]
I am using the socket. Using DOOR.SYS since it's 16 bit. Netfoss and Mystic also output a handle which may be the issue. Not sure if this is something simple. 

```
c:\path\nf.bat /n&n /h&h c:\path\bbs.bat -N&n -C1 -B38400
      |            |    |       |           |    |   |
  NetFoss-loader   node handle  bbs-loader  parameters sent to bbs.bat
```

> When used in Telnet mode, NetFoss requires that each node use a unique WinSock handle..

**Comment by NuSkooler** [comment]
ENiGMA supports a socket that can be connected to or stdin/stdout.

The idea of _sharing_ a socket _descriptor_ (aka handle) is a bit anti-node, though according to https://github.com/nodejs/node/issues/7627 I see two things:

1. Node guys appear to be softening a bit to the idea ever so slightly (was flat NO for a long time)
2. Someone appears to have done what I planned on doing as a test here: https://github.com/clshortfuse/node-getsockethandleaddress

I'll try to carve out some time to set up a Windows environment again and try the socket sharing. I'd love to be able to support `DOOR32.SYS` and other socket sharing scenarios.

**Comment by Jasin2069** [comment]
Since this would benefit me. If you would like the time saved or don't want to deal with it. I would be willing to give you access to the windows 10 vm I have already set up and running in my DMZ. It's not on the domain and only has the bbs so I am not worried about it. Or I can spin up another VM in since I want to go through the node install on windows and update your documentation. 

I can give you access either by vmware horizon client or direct rdp locked down to only your ip from the outside.

**Comment by Jasin2069** [comment]
Not a problem. Let me know if I can help test anything.

**Comment by NuSkooler** [comment]
After some more research on this, I created #175. Since this is likely blocking you from doing a lot of Win32 doors, I'll start looking into implementing it after my vacation.

**Comment by Jasin2069** [comment]
Thanks, I'm actually not worried about Win32 at the moment. Just trying Win16 with DOOR.SYS for LORD.

**Comment by Jasin2069** [comment]
@tracker1  From their wiki http://wiki.synchro.net/howto:door:index they state to use a fossil. I have netfoss and it works with mystic. Engima doesn't have support for a handle yet so I can't use netfoss. He is working on it.

**Comment by tracker1** [comment]
@Jasin2069 Synchronet comes with its' own fossil (`DOSXTRN.EXE`) you can use that... it includes support for time slice optimizations and other parameters that can be useful.

**Comment by NuSkooler** [comment]
See bivrost! info in #175.
