### ISSUE TITLE
Crash with color differences in same variable 

### ISSUE THREAD

**Issue by Jasin2069** [NuSkooler/enigma-bbs#164]
Working on modifying themes and it keep crashing as I went into area change. Switched themes and it worked fine. I found the issue is that I had the %VM1 different colors. I get that it wasn't right but can this be handled in some way so it doesn't crash if the mistake is made?

**Environment**
0.0.9

**Expected behavior**
Use colors from first block? or default colors?
**Actual behavior**

TypeError: Cannot read property 'setItems' of undefined
    at populateAreaListView (D:\enigma9\core\msg_area_list.js:143:20)
    at D:\enigma9\node_modules\async\dist\async.js:3866:24
    at replenish (D:\enigma9\node_modules\async\dist\async.js:998:17)
    at iterateeCallback (D:\enigma9\node_modules\async\dist\async.js:983:17)
    at D:\enigma9\node_modules\async\dist\async.js:958:16
    at D:\enigma9\node_modules\async\dist\async.js:3871:13
    at startingViewReady (D:\enigma9\core\msg_area_list.js:134:8)
    at complete (D:\enigma9\core\view_controller.js:802:5)
    at D:\enigma9\node_modules\async\dist\async.js:473:16
    at next (D:\enigma9\node_modules\async\dist\async.js:5315:29)

**Steps to reproduce**
https://imgur.com/a/TLSTG

**Comment by NuSkooler** [comment]
The problem here is the the way the MCI code was entered in the failed case is invalid and the particular menu module (`msg_area_list.js`) didn't enforce that it was required.

I've pushed a small change to require the MCI value. However, know that there are a lot of these in various views. I've created #165 for this.
