### ISSUE TITLE
Add default login settings to config new

### ISSUE THREAD

**Issue by SemperFu** [NuSkooler/enigma-bbs#169]
I think it would be helpful to include this block right before messageConferences in config.hjson when using 'oputil config new'.

Users will instantly see these options and are able to change them without going into the documentation. Telnet doc is empty and the websocket doc doesn't say what file to modify. I'll submit a pr for that soon.  Leaving the ssh and websocket in disabled state doesn't cause any issues.

```
  loginServers: {
	telnet: {
		enabled: true
		port: 8888
	}   
	//For SSH options see https://nuskooler.github.io/enigma-bbs/servers/ssh.html		
	ssh: {
		enabled: false
		port: 8889
		privateKeyPem: /path/to/ssh_private_key.pem
		privateKeyPass: YOUR_PK_PASS
	}   
	//For webSocket options see https://nuskooler.github.io/enigma-bbs/servers/websocket.html
	webSocket : {
		 enabled: false
		 port: 8810
		 securePort: 8811
		 certPem: /path/to/https_cert.pem
		 keyPem: /path/to/https_cert_key.pem
	 }                     
  }
```

**Comment by Jasin2069** [comment]
That would be great. I'll close this. Thanks

**Comment by NuSkooler** [comment]
Probably put some of this together soon. The plan right now:

- `oputil.js config new` will produce a much more complete configuration .hjson file
- Attempts will be made to sort more important items to the top
- Comments will be inline showing optional keys/objects, various notes, configuration examples, and so on.

The file will not contain everything as some stuff is very rarely overridden from `config.js`. Also note that when doing a upgrade from one version to the next, new entries will not be present (You'll have to RTFM or peek at `config.js` to see what is available in these cases).

Am I missing anything?

**Comment by SemperFu** [comment]
That should do well. Thanks!

**Comment by SemperFu** [comment]
I upgraded my env to node 10 but couldn't get past where the oneliners should be, just sits there blank and can't do anything. I imagine too many changes so I prob should start over anyways. I'll copy my stuff over and try it here soon.

**Comment by SemperFu** [comment]
Ok just tested it. Missed you said it wasn't done but yes that looks great and will be extremely helpful for making quick changes without having to go to the docs.

**Comment by NuSkooler** [comment]
OK, I'll continue down this path. Thanks!

**Comment by NuSkooler** [comment]
@SemperFu I think you're just asking for the login server ports to be at top? Latest push should address this.

**Comment by SemperFu** [comment]
Yeah, just the SSH to match telnet, it was hidden below all the algorithms. Thanks!.

**Comment by NuSkooler** [comment]
More is going to be added to default config over time, but all this stuff and more is there now.
