### ISSUE TITLE
pty.js fails to build on Windows

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#17]
The dependency `pty.js` fails to build on Windows due to binding errors. A updated `ptyw.js` @ https://github.com/iiegor/ptyw.js may resolve some of these issues with some work.

First pass using Visual Studio 2012 results compilation errors as well.

**Comment by M-griffin** [comment]
You might look into:  https://github.com/yaronn/blessed

**Comment by NuSkooler** [comment]
@M-griffin I've looked @ https://github.com/chjj/blessed before (which yaronn's is forked from). Had I known about it (and it was more mature) before I first wrote a lot of the terminal code I'd likely used it. Right now all the stuff works pretty well, pty.js is simply used for `forkpty(3)` (http://linux.die.net/man/3/forkpty) related things when spawning doors and the like.

**Comment by NuSkooler** [comment]
Resolved by using https://github.com/iiegor/ptyw.js
