### ISSUE TITLE
Support DOOR32.SYS style socket descriptor sharing

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#175]
Modern Win32 and Linux doors often support only [DOOR32.SYS](https://github.com/NuSkooler/ansi-bbs/blob/master/docs/dropfile_formats/door32_sys.txt) and a *shared socket descriptor* for I/O. This is currently an issue in the Node.js world as socket descriptors cannot be shared. On Windows, a socket is required to be duplicated before being sent to a process as well.

To support this, some native support will need built in most likely. Something like:

- Create socket
- `DuplicateHandle()` on Windows to dupe socket FD (WSAXXX API requires PID to share to first, which we don't have)
- Expose the duplicate handle FD to JavaScript side (e.g. to pass into `DOOR32.SYS` dropfile)
- Read data from socket handle is emitted to JS side via `data` event
- JS side can call `write`

Interesting resources:
- https://github.com/cubiclesoft/createprocess-windows
- https://github.com/vrcsix/synchronet/blob/93b01c55b3102ebc3c4f4793c3a45b8c13d0dc2a/src/sbbs3/main.cpp

**Comment by NuSkooler** [comment]
Would love any sort of help on this

**Comment by tracker1** [comment]
I really wish that I could help on this, I'm not ever sure exactly where to start... the libuv/node guys will *NOT* be exposing the socket descriptor on the API... would have to create a custom wrapper around raw sockets... I did this a long while ago, but would potentially be a fair amount of work.

I'm not even sure where that old code was... it was a C/C++ wrapper to make the calls easier to run .Net code as a door, would effectively have to do the reverse.

**Comment by NuSkooler** [comment]
@tracker1 Yeah, I think that's a dead end. Even if we have the descriptor, we can't just start doing I/O on the thing as it would throw the event system out of wack.

Perhaps a shim:
enig(stdio) <> shim.exe <> {shim.exe's shared fd} <> door

Where shim.exe would create a dropfile using enig's as a template or something.

**Comment by NuSkooler** [comment]
Finally got around to coding a solution to this. Introducing [bivrost!](https://github.com/NuSkooler/bivrost). This utility will allow "bridging" between ENiGMA½'s shared socket server and a `DOOR32.SYS` style shared socket / file descriptor.

Added initial docs @ https://github.com/NuSkooler/enigma-bbs/blob/0.0.9-alpha/docs/modding/local-doors.md#shared-socket-descriptors

See [bivrost!](https://github.com/NuSkooler/bivrost) and ArakNet hooked up boards for releases. This is intended to work under Linux as well.

Closing this issue -- this and #163 should be good to go. If this doesn't work for you please log a new ticket here or in the bivrost! repo if it's a bug around that specifically.
