### ISSUE TITLE
Websocket config should be similar to web

### ISSUE THREAD

**Issue by coolacid** [NuSkooler/enigma-bbs#176]
**Short problem description**
Currently it's not possible to disable secure web socket. I propose that the webSocket config mirror that of the Web config including different stanzas for secure and unsecure settings.

As an aside (Maybe second issue?) if you remove the secure configuration values, the default config places semi-sane defaults. However, if these are not valid (ie certs don't exist) loading fails silently with no error message. 

**Environment**
- [X] I am using Node.js v6.x or higher
- [X] `npm install` reports success
- Actual Node.js version (`node --version`): v6.14.1
- Operating system (`uname -a` on *nix systems): Ubuntu
- Revision (`git rev-parse --short HEAD`): a0f0353

**Expected behavior**
Run webSocket without secure ports

**Actual behavior**
Does not start module, silently fails to start

**Steps to reproduce**
Implement the webSocket loginServer with the following config - make sure the default files do not exist. 

```
        webSocket: {
            enabled: true
            port: 8810
        }
```

I suspect any config with missing certs will fail the same way.

**Comment by coolacid** [comment]
NOTE: I guess errors show up in the log - one would expect major errors like the above to show up in the console when something breaks.

**Comment by NuSkooler** [comment]
@coolacid Thanks for the report. Configuration for WebSocket is much more akin to that of the Web server.

Note that module loading failures are by design sent to the log vs stdout. Not much goes there. When a WFC type set up is created, I expect module status could be available there as well.
