### ISSUE TITLE
Webserver Crashes accessing Directory

### ISSUE THREAD

**Issue by coolacid** [NuSkooler/enigma-bbs#177]
**Short problem description**
If a user attempts to access a directory within the static webpage route, Enigma will crash

**Environment**
- [X] I am using Node.js v6.x or higher
- [X] `npm install` reports success
- Actual Node.js version (`node --version`): v6.14.1
- Operating system (`uname -a` on *nix systems): Ubuntu
- Revision (`git rev-parse --short HEAD`): a0f0353 (Also manually validated code in .9-Alpha)

**Expected behavior**
Should report error, or better yet, have a "default page" config for "index.html" if not found, return access denied. 

**Actual behavior**
```
System started!
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
```

**Steps to reproduce**
Configure webserver, access `/static/`

**Comment by coolacid** [comment]
Confirmed with 695e84e

**Comment by NuSkooler** [comment]
Created small fix for this. Webserver may  get a revisit sometime soon anyway.
