### ISSUE TITLE
Provide better quick start & basic information in documentation

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#18]
Need more documentation, and perhaps one full example of the HJSON file. After running `npm install`, and running `node main.js` it will not print anything, and I would not know what to do, or where to check a telnet connection, as I could not find the port to connect to.

Anyway, alpha stage, I guess. Work on it! :-)

**Comment by NuSkooler** [comment]
Thanks for your input! I have some **very early** documentation I've been working on with mkdocs. I will try to update them with some better quick start information.

For now, perhaps this will help you get started:
* Default ports are 8888 (telnet) and 8889 (ssh)
* Default configuration can be found in `core/config.js`. The *~/.config/enigma-bbs/config.hjson* file overrides any values here & provides additional configuration such as message groups and the like.
* You can use Bunyan + tail to follow the generated .log file. For example: `tail -F ./logs/enigma-bbs.log | ./node_modules/bunyan/bin/bunyan`

**Comment by NuSkooler** [comment]
I changed the title to reflect the lack of documentation. If this doesn't sound right, feel free to change it back or to something else.

**Comment by Fastidious** [comment]
@NuSkooler, thanks for the information.

Is there any reason why `~/.config/` is being used? I run VPSs, and normally run Node apps from `/usr/local/nodeapps/`. It would be nice to keep all configuration contained within the application directory.

If using telnet, do I need the `openssl` step? Thanks again!

**Comment by NuSkooler** [comment]
@Fastidious, you can use the `--config` parameter when invoking main.js to point to an alternate location. If you do not wish for SSH, you can skip the step and disable the SSH server in your config:
```hjson
servers: {
  ssh: {
    enabled: false
  }
}
```
I'll likely set SSH to disabled by default in the near future to help with better works out of the box experience.

**Comment by NuSkooler** [comment]
The quick start now has relevant information for new users & links to the more detailed configuration document. Both are evolving & will have lots of information added to them as things mature.
