### ISSUE TITLE
Support read-only ACS check for message conferences & areas

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#193]
Allow ACS to mark message conferences and/or areas read-only.

**Comment by NuSkooler** [comment]
Is there anyone using ENiG immediately wanting this?

**Comment by swarmdog** [comment]
> Is there anyone using ENiG immediately wanting this?

I'd use it to filter which of my users were allowed to post on a networked conference, while still allowing everybody to read the messages.

**Comment by NuSkooler** [comment]
@swarmdog Thanks!

**Comment by NuSkooler** [comment]
This was added a bit back: https://github.com/NuSkooler/enigma-bbs/blob/0.0.10-alpha/docs/messageareas/configuring-a-message-area.md#acs

Feel free to re-open with comments if this doesn't do the trick!
