### ISSUE TITLE
Hash/checksuming large files can be slow

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#195]
When processing (uploads, imports, etc.) a file entry, hash/checksuming can be slow especially for large files.

Look into ways to speed this up.

**Comment by tracker1** [comment]
Is this on HDD only, or SSD as well?

Maybe implement a checksum that does the first 1mb, last 1mb and filesize in bytes?  as a secondary, with a sysop option to use the slow method or the "faster" option?

**Comment by NuSkooler** [comment]
@tracker1 Hashing only a portion(s) of a file invalidates the purpose of hashing.

I very briefly looked at this a while back, and IIRC the issue was Node refused to use large read buffers.

**Comment by NuSkooler** [comment]
Made a few changes tonight that sped up the processing significantly:
* Don't use read stream, but manually process chunks from fs.read()
* No async iteration across hashes - plain ol' for loop

On a very slow test machine, this changed from ~92s -> 60s for a 4.5 GiB file
