### ISSUE TITLE
Graphics/Description Display Upon Viewing File Area

### ISSUE THREAD

**Issue by realwarmfuzzy** [NuSkooler/enigma-bbs#196]
It would be very well received if you would make an ansi displayed upon listing a file area, each file area would have its own specific ansi graphic for each file area.  It would display a 25x79 ANSI graphic that has pictures and a description of the contents.  It would pause in such a way that the graphic will display the full 25 rows, and would only display the file listing after the user presses enter (after viewing the file area information screen (ansi)).  There would be no tag at the end of the ANSI, but rather the *full* 25 rows would display without a line or two of generic information being displayed.

**Comment by NuSkooler** [comment]
I'm not sure why this is entered so very specifically ?!

An option to display art when selecting an area to browse sounds reasonable. How that art is displayed, if it pauses, etc. would remain up to the +op.

**Comment by NuSkooler** [comment]
This can how be achieved in the `0.0.9-alpha` branch with the new `show_art.js` module. This module allows a few new "advanced" ways (more to come later) to display art. For this specific issue:
By file base area tag: Define a `art` member in file base area and set this module as a "proxy" to the file listing. `extraArgs` are used to look up the art and display then forward on to the file list module/target. Example:

```
fileBaseListEntriesPreArt: {
	module: show_art
	next: fileBaseListEntries
	config: {
		method: fileBaseArea
		key: filterCriteria.areaTag
	}
	options: {
		pause: true
		cls: true
		menuFlags: [ "forwardArgs", "noHistory" ]
	}
}
```

One would set `fileBaseListEntriesPreArt` as the handler in `fileBaseBrowseByAreaSelect`'s config:
```
config: {
  fileBaseListEntriesMenu: fileBaseListEntriesPreArt
}
```


Documentation will be added for this before `0.0.9-alpha` is wrapped up.

**Comment by NuSkooler** [comment]
Initial stab at all of this is in and documented @ https://github.com/NuSkooler/enigma-bbs/blob/0.0.9-alpha/docs/modding/show-art.md
