### ISSUE TITLE
Leaving feedback to Sysop

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#20]
Notice the strings on screenshot.

![screen shot 2015-11-20 at 12 28 42 pm](https://cloud.githubusercontent.com/assets/8352292/11306923/e42c4b5a-8f82-11e5-8a75-f6982cecf41d.png)

**Comment by NuSkooler** [comment]
I *believe* this should only occur during the initial SysOp creation. Assuming that's the case, `menu.hjson` should be able to skip this step via an ACS check.

**Comment by NuSkooler** [comment]
This should now be resolved with 839ab8f
