### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by mjohnson90** [NuSkooler/enigma-bbs#204]
2018-11-13 20:35:33 Checking git installation
2018-11-13 20:35:33 Checking curl installation
2018-11-13 20:35:33 Checking Python installation
2018-11-13 20:35:33 Installing nvm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13235  100 13235    0     0  61558      0 --:--:-- --:--:-- --:--:-- 61558
=> Downloading nvm from git to '/root/.nvm'
=> Cloning into '/root/.nvm'...
remote: Enumerating objects: 267, done.
remote: Counting objects: 100% (267/267), done.
remote: Compressing objects: 100% (242/242), done.
remote: Total 267 (delta 31), reused 86 (delta 15), pack-reused 0
Receiving objects: 100% (267/267), 119.47 KiB | 7.03 MiB/s, done.
Resolving deltas: 100% (31/31), done.
=> Compressing and cleaning up git repository

=> Appending nvm source string to /root/.bash_profile
=> Appending bash_completion source string to /root/.bash_profile
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
2018-11-13 20:35:33 Installing Node 10 via nvm
Downloading and installing node v10.13.0...
Downloading https://nodejs.org/dist/v10.13.0/node-v10.13.0-linux-x64.tar.xz...
######################################################################## 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v10.13.0 (npm v6.4.1)
Creating default alias: default -> 10 (-> v10.13.0)
Now using node v10.13.0 (npm v6.4.1)
2018-11-13 20:35:33 Downloading ENiGMA½ from git to '/root/enigma-bbs'
Cloning into '/root/enigma-bbs'...
remote: Enumerating objects: 269, done.
remote: Counting objects: 100% (269/269), done.
remote: Compressing objects: 100% (177/177), done.
remote: Total 10812 (delta 151), reused 170 (delta 81), pack-reused 10543
Receiving objects: 100% (10812/10812), 3.57 MiB | 2.79 MiB/s, done.
Resolving deltas: 100% (7799/7799), done.
2018-11-13 20:35:33 Installing required Node packages...
2018-11-13 20:35:33 Note that on some systems such as RPi, this can take a VERY long time. Be patient!
main: line 87: arch: command not found
Already on '0.0.9-alpha'
Your branch is up to date with 'origin/0.0.9-alpha'.

> dtrace-provider@0.8.6 install /root/enigma-bbs/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Linux 4.17.8-1-ARCH
gyp ERR! command "/root/.nvm/versions/node/v10.13.0/bin/node" "/root/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/enigma-bbs/node_modules/dtrace-provider
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

> node-pty@0.7.4 install /root/enigma-bbs/node_modules/node-pty
> node scripts/install.js

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:606:12)
gyp ERR! System Linux 4.17.8-1-ARCH
gyp ERR! command "/root/.nvm/versions/node/v10.13.0/bin/node" "/root/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/enigma-bbs/node_modules/node-pty
gyp ERR! node -v v10.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-pty@0.7.4 install: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-pty@0.7.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-13T19_36_00_510Z-debug.log
2018-11-13 20:35:33 ERROR: Failed to install ENiGMA½ npm packages. Please report this!

**Comment by mjohnson90** [comment]
This might be because of Arch linux actually, will run the same on a fresh install of CentOS

**Comment by mjohnson90** [comment]
Now i get: 

27 error Error while executing:
27 error /usr/bin/git ls-remote -h -t ssh://git@github.com/NuSkooler/node-buffers.git
27 error
27 error fatal: Could not change back to '/root/enigma-bbs': Permission denied
27 error
27 error exited with error code: 128
28 verbose exit [ 1, true ]


even though its being ran as root.

**Comment by mjohnson90** [comment]
Ok did a manual install.. however, doing the config create, didn't create the config files with the right names, i had to rename them to $bbsname_menu_prompt.hjson etc - the server starts, but when i connect it just gives me: 

[michael@bifrost ~]$ telnet localhost 8888
Connected to ENiGMA½ BBS version 0.0.9-alpha
Copyright (c) 2014-2018 Bryan Ashby - http://l33t.codes/
Updates & source - https://github.com/NuSkooler/enigma-bbs/
An unrecoverable error has been encountered!
This has been logged for your SysOp to review.

Goodbye!

and the logs show:

{"name":"ENiGMA½ BBS","hostname":"bifrost","pid":7772,"clientId":0,"sessionId":"EMf8QvlN9Wg","level":50,"err":{"message":"Object does not exist: No menu entry for \"telnetConnected\"","name":"EnigError","stack":"EnigError: Object does not exist: No menu entry for \"telnetConnected\"\n    at Object.DoesNotExist (/home/michael/enigma-bbs/core/enig_error.js:31:52)\n    at locateMenuConfig (/home/michael/enigma-bbs/core/menu_util.js:30:40)\n    at nextTask (/home/michael/enigma-bbs/node_modules/async/dist/async.js:5324:14)\n    at Object.waterfall (/home/michael/enigma-bbs/node_modules/async/dist/async.js:5334:5)\n    at getMenuConfig (/home/michael/enigma-bbs/core/menu_util.js:23:11)\n    at getMenuConfiguration (/home/michael/enigma-bbs/core/menu_util.js:58:17)\n    at nextTask (/home/michael/enigma-bbs/node_modules/async/dist/async.js:5324:14)\n    at Object.waterfall (/home/michael/enigma-bbs/node_modules/async/dist/async.js:5334:5)\n    at loadMenu (/home/michael/enigma-bbs/core/menu_util.js:55:11)\n    at MenuStack.goto (/home/michael/enigma-bbs/core/menu_stack.js:122:9)","code":-33002},"msg":"Object does not exist: No menu entry for \"telnetConnected\"","time":"2018-11-13T20:07:14.860Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"bifrost","pid":7772,"level":30,"connectionCount":0,"clientId":0,"msg":"Client disconnected","time":"2018-11-13T20:07:14.861Z","v":0}

**Comment by mjohnson90** [comment]
When i create a config file, with all defaults i get: 

[michael@bifrost enigma-bbs]$ ./main.js ]
Error initializing: { Error: ENOENT: no such file or directory, open '/home/michael/enigma-bbs/config/new_enigma½_bbs.hjson'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/michael/enigma-bbs/config/new_enigma½_bbs.hjson' }
Error initializing: { Error: ENOENT: no such file or directory, open '/home/michael/enigma-bbs/config/new_enigma½_bbs.hjson'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/michael/enigma-bbs/config/new_enigma½_bbs.hjson' }

**Comment by mjohnson90** [comment]
Ok messed around with the config a bit and got it working - issue now is, door games wont work.. just can't enter the number for the game, hitting enter just does nothing.

**Comment by NuSkooler** [comment]
@mjohnson90 Trying to parse what's going on here: I think the issue with `new_enigma½_bbs.hjson` is I need to sanatize the generated filenames for `menu.hjson` and `prompt.hjson` more. That's on my ToDo list already -- I'll try to get it finished up tonight.

RE: doors: I'm not exactly sure what you're reporting here. Did you create menu entries for the door(s) in question? What does your log say when you press enter for the command? (Note: if you just want key presses vs having to type ie: a door name, look @ examples using the key press view).

**Comment by mjohnson90** [comment]
@NuSkooler I think the doors issue was, i was expecting them to work out of the box, as in, i could press "1" and <enter> and play LORD. 

But it appears i now need to do a little bit more work, as theres some authentication to do in the config files right?

**Comment by NuSkooler** [comment]
@mjohnson90 If you're going off of the default door menu, the art is just examples. I should probably just clear those out with note to configure them.

You'll need to configure via your `config.hjson` (or probably, `yourboardname_config.hjson` / similar): Add keys/commands (or use existing defaults) to the door menu, and menu entries per-door. There are some examples in there you can follow. See docs for more details.

**Comment by NuSkooler** [comment]
I'm not seeing any real errors here, but perhaps a couple improvements that:

1. Better sanitize generated `menu.hjson` / `prompt.hjson`
2. Update the default door menu removing listings of doors & instead have a "configure me" type of note.

Feel free to re-open if you think there are some bugs here.
