### ISSUE TITLE
Import messages to point address

### ISSUE THREAD

**Issue by ToTAL-zz** [NuSkooler/enigma-bbs#207]
Unable to import messages when Engima is set as a network point using Enigma version "0.0.9-alpha"
Trying to send netmail from 21:4/136 (Mystic) to 21:4/136.1 (Enigma)

Error messages:
```
{"name":"ENiGMA½ BBS","hostname":"hidden","pid":28692,"level":40,"areaSuccess":{},"areaFail":{},"otherFail":0,"packetPath":"/tmp/enigftnimport-28692d3fb26eefchYFldM1KdGSj7hZ/0b8c9b1f.pkt","error":"No local configuration for packet addressed to 21:4/136.1","msg":"Import completed with error(s)","time":"2018-11-19T09:28:20.443Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"hidden","pid":28692,"level":20,"path":"/tmp/enigftnimport-28692d3fb26eefchYFldM1KdGSj7hZ/0b8c9b1f.pkt","error":"Error: No local configuration for packet addressed to 21:4/136.1","msg":"Failed to import packet file","time":"2018-11-19T09:28:20.443Z","v":0}
{"name":"ENiGMA½ BBS","hostname":"hidden","pid":28692,"level":20,"origPath":"/tmp/enigftnimport-28692d3fb26eefchYFldM1KdGSj7hZ/0b8c9b1f.pkt","archivePath":"/enigma/mail/reject/reject-pkt--2018-11-19T10.28.20.443-0b8c9b1f.pkt","type":"pkt","status":"reject","msg":"Archiving import file","time":"2018-11-19T09:28:20.444Z","v":0}
```
```
config.hjson:
 messageNetworks: {
    ftn: {
      network: {
        fsxnet: {
          localAddress: "21:4/136.1"
        }
      }
   ...

```

[reject-pkt--2018-11-19T10.28.20.443-0b8c9b1f.zip](https://github.com/NuSkooler/enigma-bbs/files/2594657/reject-pkt--2018-11-19T10.28.20.443-0b8c9b1f.zip)

**Comment by NuSkooler** [comment]
@ToTAL-zz Thanks for the report + sample packet! I'll look into this tonight.

**Comment by NuSkooler** [comment]
@ToTAL-zz I was able to import your packet just fine. Upon further inspection of your config above, you have `network` (singular) where you should have `networks` (plural).

This was a big help either way, as I have not tested importing point addresses!

![image](https://user-images.githubusercontent.com/1509339/48749871-f73c1100-ec39-11e8-9eb7-be4e9528d38c.png)

Let me know if you have any other issues, otherwise this can probably be closed.

**Comment by NuSkooler** [comment]
@ToTAL-zz glad it's working for you!

BTW: If you have not, look in the docs/ folder (via GitHub will render them for you) for updated docs on the `0.0.9-alpha` branch. The dedicated document website only pulls from `master` :(
