### ISSUE TITLE
Login screen bug

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#21]
I am connecting using default OS X terminal. The first time I connect, all graphics look OK. After disconnect, and connecting again, the login screen shows as below.

![screen shot 2015-11-20 at 12 32 28 pm](https://cloud.githubusercontent.com/assets/8352292/11306954/135c0226-8f83-11e5-8979-e7142eee1f4c.png)

**Comment by NuSkooler** [comment]
Try setting the following in your `config.hjson` and see if it helps:
```hjson
preLoginTheme: luciano_blocktronics
```

**Comment by Fastidious** [comment]
I think that did it. I have connected/disconnect various times, screen looks fine.

**Comment by NuSkooler** [comment]
The default theme is now **luciano_blocktronics** and the "NU-MAYA" theme that was causing this has been removed.
