### ISSUE TITLE
Crash creating new configuration

### ISSUE THREAD

**Issue by k5jat** [NuSkooler/enigma-bbs#211]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
Crashes on each run of "./oputil.js config new"
Honestly, it looks like a wrong version in one of the scripts.

**Environment**
- [X] I am using Node.js v10.x LTS or higher
- [X] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): v6.14.3
- Operating system (`uname -a` on *nix systems): CentOS Linux release 7.5.1804 (Core) Linux enig.fireballex.com 2.6.32-48-pve #1 SMP Fri Dec 23 10:22:54 CET 2016 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`): 154beb5

**Expected behavior**
Create initial configuration
**Actual behavior**
Crashes with error in screenshot
**Steps to reproduce**
New, minimal CentOS 7.x OpenVZ VPS
run yum update
reboot
Install epel and scl repos.
Install "Development Tools"
Install node and npm
Run "curl -o- https://raw.githubusercontent.com/NuSkooler/enigma-bbs/0.0.9-alpha/misc/install.sh | bash"
Let it finish installing and whatever else is needs.
Run "./oputil.js config new" like the install script says.
Crash
![enigma-install-error](https://user-images.githubusercontent.com/764593/49333757-23388a00-f58a-11e8-9689-7995ddf0faf2.png)

**Comment by NuSkooler** [comment]
@k5jat Will need the output of the `install.sh` portion. It looks like sqlite3 did not build/install properly during that.

However, you clicked the "I am using Node.js v10.x LTS or higher" checkbox but you're running `v6.14.3` which is not supported. That will need addressed first. After fixing that, try `rm -rf node_modules` then `npm install` before trying again. If it fails, the output of `npm install` would be useful.

**Comment by k5jat** [comment]
I'm compiling node 10.x as I type this. It's taking a while because it only have 1 core available.

I thought I saw it install node.js 10.x (went by kind of quick). Is that incorrect? The error shows it's looking for v48 and v64 is in the folder.

**Comment by k5jat** [comment]
Ok, here's a copy and paste of install.sh output. I also used the SCL version of gcc/g++ 7.x. I was able to run the oputil.js (screenie) and it seems to have worked.

![enigma-conf](https://user-images.githubusercontent.com/764593/49334261-7402af80-f597-11e8-91a3-eb1d9f22e3ce.png)

`2018-12-01 19:22:23 Checking git installation
2018-12-01 19:22:23 Checking curl installation
2018-12-01 19:22:23 Checking Python installation
2018-12-01 19:22:23 Installing nvm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13235  100 13235    0     0  50871      0 --:--:-- --:--:-- --:--:-- 51100
=> nvm is already installed in /root/.nvm, trying to update using git
=> => Compressing and cleaning up git repository

=> nvm source string already in /root/.bashrc
=> bash_completion source string already in /root/.bashrc
=> Close and reopen your terminal to start using nvm or run the following to use it now:

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
2018-12-01 19:22:23 Installing Node 10 via nvm
v10.14.1 is already installed.
Now using node v10.14.1 (npm v6.4.1)
Now using node v10.14.1 (npm v6.4.1)
2018-12-01 19:22:23 Downloading ENiGMA½ from git to '/root/enigma-bbs'
Cloning into '/root/enigma-bbs'...
remote: Enumerating objects: 94, done.
remote: Counting objects: 100% (94/94), done.
remote: Compressing objects: 100% (69/69), done.
remote: Total 11547 (delta 34), reused 52 (delta 19), pack-reused 11453
Receiving objects: 100% (11547/11547), 3.83 MiB | 0 bytes/s, done.
Resolving deltas: 100% (8314/8314), done.
2018-12-01 19:22:23 Installing required Node packages...
2018-12-01 19:22:23 Note that on some systems such as RPi, this can take a VERY long time. Be patient!
Already on '0.0.9-alpha'

> dtrace-provider@0.8.6 install /root/enigma-bbs/node_modules/dtrace-provider
> node-gyp rebuild || node suppress-error.js

make: Entering directory '/root/enigma-bbs/node_modules/dtrace-provider/build'
  TOUCH Release/obj.target/DTraceProviderStub.stamp
make: Leaving directory '/root/enigma-bbs/node_modules/dtrace-provider/build'

> node-pty@0.7.4 install /root/enigma-bbs/node_modules/node-pty
> node scripts/install.js

make: Entering directory '/root/enigma-bbs/node_modules/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../src/unix/pty.cc:20:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:337:37: warning: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Local<v8::String>)’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:5053:37: note: declared here
                 static Local<Value> New(Local<String> value));
                                     ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../../nan/nan.h:1034:53: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from /root/.node-gyp/10.14.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h:1044:74: warning: ‘int v8::String::WriteUtf8(char*, int, int*, int) const’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2659:21: note: declared here
                 int WriteUtf8(char* buffer, int length = -1,
                     ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyFork(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:154:48: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::String::Utf8Value file(info[0]->ToString());
                                                ^
In file included from /root/.node-gyp/10.14.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
../src/unix/pty.cc:154:49: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   v8::String::Utf8Value file(info[0]->ToString());
                                                 ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:165:78: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     v8::String::Utf8Value arg(argv_->Get(Nan::New<v8::Integer>(i))->ToString());
                                                                              ^
In file included from /root/.node-gyp/10.14.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
../src/unix/pty.cc:165:79: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     v8::String::Utf8Value arg(argv_->Get(Nan::New<v8::Integer>(i))->ToString());
                                                                               ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:176:78: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
     v8::String::Utf8Value pair(env_->Get(Nan::New<v8::Integer>(i))->ToString());
                                                                              ^
In file included from /root/.node-gyp/10.14.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
../src/unix/pty.cc:176:79: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     v8::String::Utf8Value pair(env_->Get(Nan::New<v8::Integer>(i))->ToString());
                                                                               ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:181:48: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::String::Utf8Value cwd_(info[3]->ToString());
                                                ^
In file included from /root/.node-gyp/10.14.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
../src/unix/pty.cc:181:49: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   v8::String::Utf8Value cwd_(info[3]->ToString());
                                                 ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:186:39: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   winp.ws_col = info[4]->IntegerValue();
                                       ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:187:39: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   winp.ws_row = info[5]->IntegerValue();
                                       ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:195:26: warning: ‘v8::Local<v8::Boolean> v8::Value::ToBoolean() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   if (info[8]->ToBoolean()->Value()) {
                          ^
In file included from /root/.node-gyp/10.14.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:10034:16: note: declared here
 Local<Boolean> Value::ToBoolean() const {
                ^~~~~
../src/unix/pty.cc:230:35: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int uid = info[6]->IntegerValue();
                                   ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:231:35: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int gid = info[7]->IntegerValue();
                                   ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyOpen(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:315:39: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   winp.ws_col = info[0]->IntegerValue();
                                       ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:316:39: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   winp.ws_row = info[1]->IntegerValue();
                                       ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyResize(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:360:34: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->IntegerValue();
                                  ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:363:39: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   winp.ws_col = info[1]->IntegerValue();
                                       ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:364:39: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   winp.ws_row = info[2]->IntegerValue();
                                       ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE PtyGetProc(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/unix/pty.cc:387:34: warning: ‘int64_t v8::Value::IntegerValue() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   int fd = info[0]->IntegerValue();
                                  ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2476:46: note: declared here
   V8_DEPRECATED("Use maybe version", int64_t IntegerValue() const);
                                              ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc:389:48: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   v8::String::Utf8Value tty_(info[1]->ToString());
                                                ^
In file included from /root/.node-gyp/10.14.1/include/node/node.h:63:0,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
../src/unix/pty.cc:389:49: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
   v8::String::Utf8Value tty_(info[1]->ToString());
                                                 ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/root/.node-gyp/10.14.1/include/node/v8.h:2892:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/unix/pty.cc: In function ‘void pty_after_waitpid(uv_async_t*)’:
../src/unix/pty.cc:489:69: warning: ‘v8::Local<v8::Value> Nan::Callback::Call(v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’ is deprecated [-Wdeprecated-declarations]
   Nan::Callback(cb).Call(Nan::GetCurrentContext()->Global(), 2, argv);
                                                                     ^
In file included from ../src/unix/pty.cc:20:0:
../../nan/nan.h:1596:3: note: declared here
   Call(v8::Local<v8::Object> target
   ^~~~
  SOLINK_MODULE(target) Release/obj.target/pty.node
  COPY Release/pty.node
make: Leaving directory '/root/enigma-bbs/node_modules/node-pty/build'

> sqlite3@4.0.4 install /root/enigma-bbs/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using request for node-pre-gyp https download 
[sqlite3] Success: "/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v64-linux-x64/node_sqlite3.node" is installed via remote

> xxhash@0.2.4 install /root/enigma-bbs/node_modules/xxhash
> node-gyp rebuild

make: Entering directory '/root/enigma-bbs/node_modules/xxhash/build'
  CXX(target) Release/obj.target/hash/src/hash.o
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:203,
                 from ../src/common.hpp:6,
                 from ../src/hash_32.hpp:4,
                 from ../src/hash.cc:3:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::StringObject>::return_t Nan::imp::Factory<v8::StringObject>::New(v8::Local<v8::String>)’:
../../nan/nan_implementation_12_inl.h:337:37: warning: ‘static v8::Local<v8::Value> v8::StringObject::New(v8::Local<v8::String>)’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
   return v8::StringObject::New(value).As<v8::StringObject>();
                                     ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../src/hash.cc:1:
/root/.node-gyp/10.14.1/include/node/v8.h:5053:37: note: declared here
                 static Local<Value> New(Local<String> value));
                                     ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/common.hpp:6:0,
                 from ../src/hash_32.hpp:4,
                 from ../src/hash.cc:3:
../../nan/nan.h: In constructor ‘Nan::Utf8String::Utf8String(v8::Local<v8::Value>)’:
../../nan/nan.h:1034:53: warning: ‘v8::Local<v8::String> v8::Value::ToString() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
       v8::Local<v8::String> string = from->ToString();
                                                     ^
In file included from /root/.node-gyp/10.14.1/include/node/node.h:63:0,
                 from ../src/hash.cc:1:
/root/.node-gyp/10.14.1/include/node/v8.h:10040:15: note: declared here
 Local<String> Value::ToString() const {
               ^~~~~
In file included from ../src/common.hpp:6:0,
                 from ../src/hash_32.hpp:4,
                 from ../src/hash.cc:3:
../../nan/nan.h:1044:74: warning: ‘int v8::String::WriteUtf8(char*, int, int*, int) const’ is deprecated: Use Isolate* version [-Wdeprecated-declarations]
         length_ = string->WriteUtf8(str_, static_cast<int>(len), 0, flags);
                                                                          ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../src/hash.cc:1:
/root/.node-gyp/10.14.1/include/node/v8.h:2659:21: note: declared here
                 int WriteUtf8(char* buffer, int length = -1,
                     ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/hash.cc:3:0:
../src/hash_32.hpp: In static member function ‘static uint32_t Hash32::convert_seed(v8::Local<v8::Value>)’:
../src/hash_32.hpp:57:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         return seed_val->Uint32Value();
                                      ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../src/hash.cc:1:
/root/.node-gyp/10.14.1/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
In file included from ../src/hash.cc:4:0:
../src/hash_64.hpp: In static member function ‘static uint64_t Hash64::convert_seed(v8::Local<v8::Value>)’:
../src/hash_64.hpp:57:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
         return seed_val->Uint32Value();
                                      ^
In file included from /root/.node-gyp/10.14.1/include/node/v8.h:26:0,
                 from /root/.node-gyp/10.14.1/include/node/node.h:63,
                 from ../src/hash.cc:1:
/root/.node-gyp/10.14.1/include/node/v8.h:2477:47: note: declared here
   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
                                               ^
/root/.node-gyp/10.14.1/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
  CC(target) Release/obj.target/hash/deps/xxhash/xxhash.o
  SOLINK_MODULE(target) Release/obj.target/hash.node
  COPY Release/hash.node
make: Leaving directory '/root/enigma-bbs/node_modules/xxhash/build'

> node-pty@0.7.4 postinstall /root/enigma-bbs/node_modules/node-pty
> node scripts/post-install.js

added 329 packages from 300 contributors and audited 2155 packages in 15.774s
found 0 vulnerabilities

2018-12-01 19:22:23 npm package installation complete
2018-12-01 19:22:23 ENiGMA½ installation complete!

If this is the first time you've installed ENiGMA½, you now need to generate a minimal configuration. To do so, run the following commands (note: if you did not already have node.js installed, you may need to log out/back in to refresh your path):

  cd /root/enigma-bbs
  ./oputil.js config new

Additionally, the following support binaires are recommended:
  7zip: Archive support
    Debian/Ubuntu : apt-get install p7zip
    CentOS        : yum install p7zip

  Lha: Archive support
    Debian/Ubuntu : apt-get install lhasa

  Arj: Archive support
    Debian/Ubuntu : apt-get install arj

  sz/rz: Various X/Y/Z modem support
    Debian/Ubuntu : apt-get install lrzsz
    CentOS        : yum install lrzsz

  See docs for more information!`

**Comment by NuSkooler** [comment]
Awesome! Above output looks pretty normal. I'm not sure what went wrong before since we don't have the original output though.

**Comment by k5jat** [comment]
I'm gonna guess that not having the proper version of node did it. Enigma seems to be running rather well, albeit a little memory hungry for a 1GB RAM VPS. lol

**Comment by NuSkooler** [comment]
@k5jat Yeah, Node.js 8.x *probably* still works, but 10.x is what's supported for 0.0.9-alpha currently. Glad it's working!
