### ISSUE TITLE
Create a semi-traditional Waiting For Caller (WFC) System

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#216]
**Feature open for Discussion**:
Create a semi-traditional "Waiting For Caller" (WFC) system.

**Traditional**:
- A terminal driven WFC (dashboard) that can be viewed by +ops
- ACS driven: "+ops" here should be `GM[users]` by default, but could be configured. See modern features on other restrictions.
- Display of basic statistics such as active connections/nodes, last N calls, etc.
- Quick login
- Ability to receive direct (PM/IM) messages from an online user
- Ability to break break into chat with an online user
- Node spy. Essentially see what a connected user is seeing
- Some basic management
- View logs

**Some more modern features**:
- Allow remote WFC: +ops should be able to remotely connect & use the WFC
- Remove connections should work over secure channels only (Secure WebSocket or SSH)
- It _may_ even be worth **only** allowing SSH with public key authentication.
- Possible whitelist of allowed IPs
- Various `menu.hjson` / theming rules should apply to WFC
- View status -- and possibly trigger -- scheduled tasks

**Comment by cwstephenson71** [comment]
How about a log viewer and echomail polling?

**Comment by NuSkooler** [comment]
@cwstephenson71 Viewing of logs is in the list. What do you mean by EchoMail polling? An explicit "poll now" type action? Since ENiGMA currently relies on an external system for transport (e.g.: Binkd) that may not be directly possible.

**Comment by cwstephenson71** [comment]
Yeah like a "poll now" maybe add the default command syntax for bink "binkd
-p" or even let the sysOp change it if they don't use bink?

Regards

**Comment by NuSkooler** [comment]
@cwstephenson71 If that's really a desired feature I think arbitrary +op defined commands would be better.

Something like:

```
commandKey: {
  name: Poll Binkd
  cmd: /sbin/binkd
  args: [
    // ...
  ]
}
```

**Comment by SemperFu** [comment]
Since I have a scheduled task set to run a pool on binkd. Could also give the sysop the ability to see scheduled tasks and run them immediately as well.

**Comment by streaps** [comment]
why not modify the files in the outbound directory directly?

**Comment by cwstephenson71** [comment]
Yeah, me too...much better! Thanks!

Regards

**Comment by NuSkooler** [comment]
@streaps Can you elaborate?

**Comment by streaps** [comment]
http://ftsc.org/docs/fts-5005.003
http://wiki.synchro.net/ref:fidonet_files

if this is not self explanatory, I can elaborate later.

**Comment by NuSkooler** [comment]
@streaps ENiGMA already reads/writes FTN/BSO packets & control files. I'm not sure what you're getting at here -- what _feature_ are you after? What does it have to do with a WFC?

**Comment by NuSkooler** [comment]
https://github.com/NuSkooler/enigma-bbs/pull/431 is merged! Some tickets already entered, any other missing functionality/requests should be their own as well.
