### ISSUE TITLE
Configuration / Menu Include System

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#220]
**Feature**:
Allow configuration & menus (`config.hjson`, `menu.hjson`, `theme.hjson`, ...) to include other HJSON files. This would allow for breaking up large configurations (#158), easier upgrade maintenance, etc.

**Current Design Thoughts**:
Current design is something like this:
- A file could have a top-level `include` array.
- Each element in the array is a relative or full path to another .hjson file.

Example:
```
// menu.hjson
include: [
  "doors.hjson",
  "builtin-menus.hjson"
]
```

**Questions**:
- Resolution for conflicting key/paths: Should main > include or include > main?

**Comment by NuSkooler** [comment]
Related work to this, it would be nice to be able to reference other menu sections as a sort of template:

```
someSection: {
  name: Some Section
  next: fooBaz
  form: {
    // ...
  }
  // ...
}

// ...

otherSection: {
  template: someSection
  name: Other Section
  next: baz
}
```

**Comment by NuSkooler** [comment]
Updates on current design thoughts:
## General Goals
* Remain HJSON driven
* Configurations to remain hot-reload
* Self references (reference 'a.b', from 'a.d.e', etc.)
* Templates (use self ref as a template)
* Environment variable support
* Includes
* Good reporting of syntax errors

### Includes
A the very least, a top level include:
```
// my-bbs.hjson
{
  includes: [
    // default menus
    enigma-bbs-default-menus.hjson
    // others
    my-menus.hjson
  ]
}
```

### Self References
```
{
  foo: {
    bar: {
      baz: foobar!
    }
  }
  
  fubar: {
    // resolves to { baz: foobar! } above
    bar: @reference:foo.bar
  }
}
```

### Environment Variables
```
{
  foo: {
    // SOME_VAR in current process environment
    bar: @environment:SOME_VAR
  }
}
```

## Questions
* Should includes be top level only or allow for nesting?
* If includes allow for nesting, should they detect circular refs (a pain) or simply imply "once" (once a file is included, it will be ignored beyond that)
* Should includes override sections or add-to in order only?

**Comment by tracker1** [comment]
Not sure that self reference provides much value, especially considering the complexity to implement.

Other than that, looks good.

**Comment by NuSkooler** [comment]
@tracker1: They are incredibly useful. A lot of blocks are duplicated all over in a real system.

**Comment by tracker1** [comment]
@NuSkooler wouldn't being able to import a segment from another file be easier to implement? 

Such as `@include:my-config.hjson:$.some.part`

**Comment by NuSkooler** [comment]
@tracker1 You can already do that with this setup, but differently:
```
// foo.hjson
{
  bar: {
    baz: true
  }
}

// main.hjson
{
  includes: [
    foo.hjson
  ]

  bazinga: @reference:bar
}
```

As far as implementation, you can toy with it here: https://repl.it/@NuSkooler/ConfigRevampTests

**Comment by planeguy** [comment]
my gut says main overrides include if you want to think of it as chronological order. also is easier to debug since you don't have to hunt through all the includes to find out what's overriding your value since it would be the main parent doing the overriding

**Comment by NuSkooler** [comment]
To be tracked in  #280
