### ISSUE TITLE
ssh crash

### ISSUE THREAD

**Issue by k5jat** [NuSkooler/enigma-bbs#223]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
Enigma crashes with:
`/root/enigma-bbs/node_modules/ssh2/node_modules/ssh2-streams/lib/ssh.js:2056
    throw new Error('No auth in progress');
    ^
`

**Environment**
- [x] I am using Node.js v10.x LTS or higher
- [x] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): v10.14.1
- Operating system (`uname -a` on *nix systems): Linux enig.fireballex.com 2.6.32-48-pve #1 SMP Fri Dec 23 10:22:54 CET 2016 x86_64 x86_64 x86_64 GNU/Linux (CentOS Linux release 7.5.1804 (Core))
- Revision (`git rev-parse --short HEAD`): 23d7077

**Expected behavior**
Run main.js under screen and it continue to run

**Actual behavior**
Somewhere along the way it crashes with an ssh error.
![enigma-error2](https://user-images.githubusercontent.com/764593/49884302-2c332200-fdfa-11e8-9dff-908504093e75.png)

**Steps to reproduce**
Run main.js and wait.

**Comment by NuSkooler** [comment]
@k5jat Have you seen this more than once? A connection is coming in to your system, so "...and wait" is a bit off. Any idea what client(s) are causing this?

I can and probably should put some catches around the accept/reject calls, but steps to reproduce this would be good.

**Comment by k5jat** [comment]
No, I really can't tell what client it is. Is there a way to enable debug mode and it go to a log? That might catch it.

**Comment by k5jat** [comment]
Ok, I set  it up to trace for the logs. I'll check it tomorrow, and if it dies, I'll attach the log.

**Comment by k5jat** [comment]
I finally got to check the bbs and it did crash. I'm attaching the compressed log now.
[enigma-bbs.log.tar.gz](https://github.com/NuSkooler/enigma-bbs/files/2707573/enigma-bbs.log.tar.gz)

**Comment by NuSkooler** [comment]
@k5jat Thanks, I'll look into this. A quick skim reveals someone is attempting to brute force login via "root" on your system FWIW.

**Comment by NuSkooler** [comment]
@k5jat I just pushed some small changes to help with this.

You might want to look into getting a firewall or such to protect from malicious login attempts like those seen here. Someone is really trying hard to log in to your system as "root".

**Comment by k5jat** [comment]
Yeah, I see the root attempts. Actually sshd is running a non-standard port, and enigma is the only other server running on it. I'll look into it though and I'll update ASAP. Thanks!

**Comment by NuSkooler** [comment]
Going to close this one. Please feel free to re-open if it continues.
