### ISSUE TITLE
Feature Request - Auto Blocklist

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#227]
Regarding #223, might be worthwhile to setup a rate limiting scheme that will block an IP after X failed login attempts in under Y minutes for Z minutes long...

Example: 5 failed logins under 5 minutes, block the IP for 60 minutes, or until system restarts.

IE: in-memory solution to reduce complexity.

```
// on connect, all protocols
  // check block-list for IP
  // if found, check for staleness
    // if stale, remove, continue
    // if active drop connection, use appropriate error code?

// upon failed login attempt
  // check failed logins list for IP, or add array to list
  // remove stale/older than Y entries.
  // add current entry
  // if more than X entries, add IP to block-list
```

**Comment by SemperFu** [comment]
Yeah I wouldn't mind having something like this. You could have a blacklist file for permanent banned IPs it checks at startup. Too many attempts get added to perm ban.

**Comment by NuSkooler** [comment]
I've resisted adding this to ENiGMA since [fail2ban](https://www.fail2ban.org/wiki/index.php/Main_Page) already exists.

**Comment by SemperFu** [comment]
@NuSkooler I'm all for fail2ban. But how can I get ENiGMA to use it since it's the one listening on ssh?

**Comment by NuSkooler** [comment]
@SemperFu fail2ban monitors log files (ie: your ENiGMA logs) and performs actions such as setting a blocking firewall rule when criteria is met (_N_ failed login attempts, etc.)

**Comment by NuSkooler** [comment]
IMO it would be better to write up a "How to" in the docs RE fail2ban/similar. A system such as that puts in a FW rule where it belongs vs letting an application trying to handle it.

**Comment by paulchabotca** [comment]
I was about to re-setup an ENiGMA system. I can write down my process into a rough how to. If I will look at the logs as well to see about creating some enigma regex's for fail2ban if needed. Honestly, I agree with @NuSkooler in that fail2ban exists... it's amazing, no need to re-invent the wheel.

**Comment by NuSkooler** [comment]
@paulchabotca That would be great! I'm going to take a quick look at the logs around failed logins and the like and perhaps add some additional data to them. If anything is missing though, please let me know and I'll get it in there.

**Comment by NuSkooler** [comment]
@SemperFu There appear to be many alternatives to fail2ban for Windows such as [IPBan](https://github.com/DigitalRuby/IPBan). Attempting to block IP's at the application layer is really nothing more than a gimmick.

Failed login attempts already disconnect, lock the account, etc. (#'s configurable)

**Comment by NuSkooler** [comment]
Closing this as per discussion above, in addition to other issues it would bring (ie: you'd have to run ENiGMA 1/2 as root, which is even worse). 

If someone is interested in IP banning, please try the aforementioned fail2ban, IPBan, etc. I'm happy to put in additional information in the ENiGMA 1/2 logs if that would help with these tools, and would gladly accept PR's around such or documentation on using these tools with the system.
