### ISSUE TITLE
Cannot find module node-v48-linux-x64/node_sqlite3.node

### ISSUE THREAD

**Issue by KaiDream** [NuSkooler/enigma-bbs#230]
Recently have an issue on my installation after a recent pull, created a new docker of ubuntu to see if it replicated on a new install.

**Short problem description**
`root@enigmaBBS:~/enigma-bbs# ./oputil.js config new
module.js:478
    throw err;
    ^

Error: Cannot find module '/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
root@enigmaBBS:~/enigma-bbs#`

**Steps to reproduce**
Install base Ubuntu with python, build-essential
curl -o- https://raw.githubusercontent.com/NuSkooler/enigma-bbs/master/misc/install.sh | bash
cd ~/enigma-bbs
./oputil.js config new

**Comment by NuSkooler** [comment]
@KaiDream Please use the `0.0.9-alpha` branch. 
```
curl -o- https://raw.githubusercontent.com/NuSkooler/enigma-bbs/0.0.9-alpha/misc/install.sh | bash
```
(this will be marked as master in the near future)

**Comment by KaiDream** [comment]
That's the branch i am using on my deployed environment (using the non install script).
`git fetch --all
git reset --hard origin/0.0.9-alpha`

**Comment by NuSkooler** [comment]
But you didn't do it with the script, and as such have the wrong dependencies -- including the wrong Node.js version, and old `node_modules` directory, etc.

Unless you have a reason not too, delete your enigma-bbs directory and run the 0.0.9-alpha script.

**Comment by NuSkooler** [comment]
```Error: Cannot find module '/root/enigma-bbs/node_modules/sqlite3/lib/binding/node-v48-linux-x64/node_sqlite3.node'```

Looks like you still have an older Node.js version installed and set in your PATH most likely.

```
node --version
```

outputs what?

**Comment by KaiDream** [comment]
When you asked what version of node it clicked and i got it all addressed. The default install was using NODE 8 and nvm v0.33.7. (This is based on davestephens/enigma-bbs docker image). I killed the imaged and set it to NODE 10 and nvm v0.34.0 and we're back online. Sorry about the confusion (didn't realize that we'd have to swap the node install moving foward)

**Comment by NuSkooler** [comment]
@KaiDream Awesome, don't hesitate to ask if there are other issues!
