### ISSUE TITLE
change username?

### ISSUE THREAD

**Issue by Shaedax** [NuSkooler/enigma-bbs#232]
It would be nice if there were an easy way to change one's username.

**Comment by NuSkooler** [comment]
That's a easy one. Added in `0.0.10-alpha` @ f41d12c6885c68c0d4b7b5a74c9b6d4d8442fdee

**Comment by NuSkooler** [comment]
BTW: If you're asking for a user to be able to change their _own_ name, feel free to re-open. I think that would need to come with ACS support, etc.  though.
