### ISSUE TITLE
Node Version Uplift 12.x

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#237]
Was thinking, given the shift towards ESM support, and potentially WebAssembly (wasm), it might be a good time to consider bumping the vNext branch to the latest Node 12 version.  Also, adjusting the npm start script in package.json to add `--experimental-modules` and `--experimental-wasm-modules`

Node 12 already has a worker thread api, and with esm a lot of the modules could be cleaned up a bit, possibly refactored for async functions as well.  With wasm, there may be an opportunity to embed a DOS emulator for classic Door support, or maybe even other system emulators for non-win/dos platform doors.  Just wild thinking on that part.

I do think that enabling modules and wasm would generally be beneficial with a shift to Node 12 to open possibilities.

**Comment by NuSkooler** [comment]
Node 12.x could be interesting, but currently I'm mostly interested in keeping things on a LTS branch.

Cleaning up and using modern modules, async/await, etc. would be great, but I'd rather not use experimental for now.

**Comment by NuSkooler** [comment]
`0.0.11-beta` is at Node.js 12.x LTS. Modules seem to have remained experimental until at least 13+, async/await also seems to require some flags for full support (stacks/etc.) even in 12 unless I'm missing something. Closing for now due to 12.x, feel free to comment/etc.
