### ISSUE TITLE
MRC PMs don't work

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#238]
The MRC private message handler looks for `/pm` in a message then takes the next token as the message. The code means that it only takes the first word then the second is the message, meaning everything after the second word is ignored.

This line:
https://github.com/NuSkooler/enigma-bbs/blob/fdce4c939cbb093024d2134b6c88d0bce6ef6904/core/mrc.js#L429

Should probably be replaced with something better! 

Feel free to assign this to me and I'll sort it at some point soon. :+1:

**Comment by NuSkooler** [comment]
@davestephens  I can look at this when I get to it, but if you wanna fix it up I'd appreciate!

**Comment by christiansacks** [comment]
I fixed this in https://github.com/NuSkooler/enigma-bbs/pull/391 👍
