### ISSUE TITLE
Full screen ANSIs don't display properly since some point in 0.0.10-alpha

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#239]
Certain full screen ANSIs don't seem to display properly until some point in 0.0.10-alpha

**Environment**
Using latest Docker image (fdce4c9)

**Expected behavior**
![image](https://user-images.githubusercontent.com/668464/60761175-2a9da580-a03b-11e9-8169-b76acad4b92f.png)

**Actual behavior**
![image](https://user-images.githubusercontent.com/668464/60761164-d692c100-a03a-11e9-8d5d-23eb0ea33be5.png)

**Steps to reproduce**
Ignoring the fact that there are other issues with this ANSI, the line wrapping seems to be going wrong somewhere. Deleting the contents of the last column and resaving the ANSI seems to sort the issue. 

The source ANSI is https://github.com/davestephens/bbs-ansi-adverts/blob/master/adverts/ds94.ans

**Comment by NuSkooler** [comment]
Any more info on this? I haven't seen this to be an issue anywhere. Can this be done with a more simplistic ANSI so it's easier to work with when debugging?

Related to #161?

**Comment by davestephens** [comment]
I can give you a few ansis that cause the issue if that helps? Trouble is I don't know what it is in the ANSI that causes the issue, so difficult for me to produce a test case!

**Comment by NuSkooler** [comment]
@davestephens The more the better probably unless you can isolate it. Might want to try what's in #161 and see if it's the same issue.

**Comment by GettenGud** [comment]
I have a report to add to the pile...

In my case I'm having troubles making any of them work, me and my kid have both made big ansis that do not show up properly on either NR or Ether, VTX is perfect though!
![image](https://user-images.githubusercontent.com/57871248/70105718-a6fadb80-160f-11ea-962a-edc1623e6445.png)

It seems like everything is like this.
![image](https://user-images.githubusercontent.com/57871248/70105788-ceea3f00-160f-11ea-9d61-d1bca1669c9d.png)

I have just been using a web ansi editor and some pablodraw and using the files they generate.
I can get you the ANS files if they would help, but it seems almost all of the ones we've made have come out this way.

**Comment by NuSkooler** [comment]
I think the general work around is <= 79 columns (and <= 24 rows for non-scollers). I'll be re-visiting how art is handled and drawn in a future update, but even then I'm not sure this will be possible for all terminals which is why 79x24 has become such a thing in the BBS world.

**Comment by GettenGud** [comment]
> 
> 
> I think the general work around is <= 79 columns (and <= 24 rows for non-scollers). I'll be re-visiting how art is handled and drawn in a future update, but even then I'm not sure this will be possible for all terminals which is why 79x24 has become such a thing in the BBS world.

hells yes if all I have to do is keep to 79x24 to be safe, I'm cool with that!

**Comment by NuSkooler** [comment]
@GettenGud If that doesn't do the trick let me know and I'll bump up the priority of looking into this more. It's basically the rule I follow on Xibalba and seems to work for the terminals I test though.

**Comment by GettenGud** [comment]
After looking, it appears that the stock template files that come with the install are 80 cols, off by one, isn't that great? haha. As a new user I used them assuming it'd be good, so perhaps either fixing it up or creating a new screen-safe template would be worthwhile.

I'm still pretty new at all this, but I could probably cut them down one column without destroying them, I'm also making my own template so I could also make some more barebones ans files as I go.

**Comment by davestephens** [comment]
I don't think this is just a <79 columns issue - when I get some time I'll
isolate specific examples but I found simply opening and resaving the
affected ANSIs worked.

I noticed it with the ANSIs in my BBS adverts repo - some of them started
rendering incorrectly once I flipped to 0.0.10.

**Comment by GettenGud** [comment]
Here's an image for a template I tried making 79, set against the proper backdrop. it doesn't do the same things that it did before but it is still behaving strangely,
![image](https://user-images.githubusercontent.com/57871248/70149539-510d4e80-1676-11ea-80f0-2ea3da8526e6.png)

Something really weird I'm noticing here is that a bunch of my image is missing, where's all the light blue on line 2? it goes straight from the border to the shaded colors!

**Comment by GettenGud** [comment]
Here's that particular file, pardon the ZIP github demanded it of me
[WELCOME1.zip](https://github.com/NuSkooler/enigma-bbs/files/3923014/WELCOME1.zip)

**Comment by GettenGud** [comment]
I may be unrelated- I was able to fix my ANSI file by using Moebius instead of Pablo and the older version of the browser ANSI so I suspect that has been my problem. Hope that helps someone else though I'm having MUCH more consistent results.

It wasn't enough to load the file, I had to re-draw all characters that were being missed on the terminal. Black shaded blocks were a real problem too as sometimes they'd just be empty and the terminal would skip over them.

Here's a copy of the GOOD file, I know nothing about this format but I'd like to try and compare them and see if maybe there's a way of fixing files that otherwise appear fine but break like this.
[WELCOME1.zip](https://github.com/NuSkooler/enigma-bbs/files/3928439/WELCOME1.zip)

**Comment by NuSkooler** [comment]
@GettenGud  Thanks. I'll try to remember to archive up the save vs re-saved version of your original WELCOME1.zip also. I'm not yet sure if there is anything we can do about it other than perhaps some sort of pre-processing of art files.

**Comment by NuSkooler** [comment]
I think there may be a mix of issues in here, but the bit about opening and re-saving makes me think at least some of them may have been fixed along with #244. Can someone verify?

**Comment by NuSkooler** [comment]
Assuming this is not working due to inactivity. Please re-open if this is not the case!
