### ISSUE TITLE
Add auto-signure support

### ISSUE THREAD

**Issue by christiansacks** [NuSkooler/enigma-bbs#242]
how do I set my default signature in Enigma?
I wish to have a default signature set for my account so that whenever I send a netmail or echomail it automatically appends my signature to the end of the message before the origin line. It should also probably have a standards tear line too, just to separate it from the body of the message.

I'd like to set something like;

Best regards,
MeaTLoTioN

and when Enigma sends my message, it will append it to the bottom of the message, just above the origin line, like...

blah blah message blah blah

--

Best regards,
MeaTLoTioN

* origin line something blah (1:22/333.4444)

Hope this makes sense =)

**Comment by tracker1** [comment]
NOTE: signature blocks should start with `-- \r\n` note the space before the crlf... this is the convention used for detection in NNTP clients and some email clients for a very long time.  Which is different than quotes and tear lines.

**Comment by NuSkooler** [comment]
Currently ENiGMA doesn't support auto sigs. Implementing support is pretty trivial though, so I might take a look at this soon.

**Comment by NuSkooler** [comment]
Initial support added. Available by default at the messages menu. Currently enabled by default for all areas - you can set `autoSignatures: false` in an area config block to disable.

**Comment by tracker1** [comment]
@NuSkooler wish you'd include the issue number in the commit so it will link to it... :-)

**Comment by NuSkooler** [comment]
@tracker1 I generally do, especially for larger features.

**Comment by tracker1** [comment]
@NuSkooler cool... just went spelunking as I was curious about the configuration... hadn't really dug into the codebase much so far.
