### ISSUE TITLE
ANSI FILE_ID.DIZ sometimes do not display correctly

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#244]
Some ANSI `FILE_ID.DIZ` do not display correctly. While they may be _technically_ out of spec (e.g. > 45 chars in width) we should still display them reasonably.

The attached file is an example. The DIZ displays properly in e.g. Mystic BBS.

[Uploading tqwnet.zip…]()

DIZ created with Moebius @ 80 wide canvas:
![image](https://user-images.githubusercontent.com/1509339/62825219-82ad5780-bb65-11e9-9066-1b22bce8eddc.png)

![image](https://user-images.githubusercontent.com/1509339/62825237-bee0b800-bb65-11e9-84f8-1e6375c95929.png)

**Comment by cwstephenson71** [comment]
Does the same thing in PabloDraw.
