### ISSUE TITLE
Achievements sometimes display empty

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#245]
Periodically when earning an achievement, they can show up empty. See screenshot. This has been observed on a couple systems now.

![image](https://user-images.githubusercontent.com/1509339/62837087-66beba00-bc28-11e9-8060-611fad0061e2.png)

**Comment by NuSkooler** [comment]
Has anyone else ever seen this? I've yet to really repo it.

**Comment by alex-serpico** [comment]
Same problem here !

**Comment by NuSkooler** [comment]
@alex-serpico any idea on steps to reproduce this?

**Comment by alex-serpico** [comment]
It happens every time an achievement is reached ...
I'm using the user sysop.
Linux Debian 10

**Comment by NuSkooler** [comment]
I'll play around with this and see if I can get it in the state.

**Comment by NuSkooler** [comment]
This should now be resolved
