### ISSUE TITLE
Improve password hashing

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#246]
Just a suggestion, may want to make a few adjustments to password hashing.  First by using sha512 as the underlying pbkdf2 algorithm, and second by increasing the iterations. Also keeping a derivation longer than the underlying derivation algo doesn't increase security for password storage. for sha1 that'd be 20 bytes (160-bit).

Attaching two files for how I have v1 hashing on an authentication applications I'm working on.  You'd probably need to adapt the detection so that if it doesn't have a v# prefix it uses the current method to validate, then update in the db as a workflow.

Note: hash.js is index, so need to update/adjust the test case(s) for it.

[hash.js.txt](https://github.com/NuSkooler/enigma-bbs/files/3507468/hash.js.txt)
[hash.spec.js.txt](https://github.com/NuSkooler/enigma-bbs/files/3507469/hash.spec.js.txt)
[hash-v1.js.txt](https://github.com/NuSkooler/enigma-bbs/files/3507470/hash-v1.js.txt)
[hash-v1.spec.js.txt](https://github.com/NuSkooler/enigma-bbs/files/3507471/hash-v1.spec.js.txt)

**Comment by NuSkooler** [comment]
@tracker1 I've considered updating this at some point. When I do, I may also consider moving to e.g. Argon2 over PBKDF2.

**Comment by davestephens** [comment]
We should also ensure that with whatever we use, the hashing doesn't murder the RPi when it initially hashes passwords / checks password attempts.

**Comment by tracker1** [comment]
@davestephens that's fair and I hadn't considered the issue... 10k is probably a better iteration level.  Probably reasonable in an rpi3b.

**Comment by NuSkooler** [comment]
Any changes also need to come with making the password data include the hash information such that multiple types can easily be supported.

**Comment by tracker1** [comment]
@NuSkooler yeah... The attached files, have support for versioned hashing... I tend not to make it too flexible, just enough to go from v1 to v2, etc.  Since it's not likely to change too often.   If relaxed hashing, such as for an rpi is needed, then may be an idea to have them (such as bcrypt).

On Argon2 vs PBKDF2 would prefer something baked into node vs. an external compiled module myself.  Just my own $.02

**Comment by NuSkooler** [comment]
I haven't looked at the attachments, but yeah it's not a complicated thing to do. Just wanted it noted. Agree on baked in. The current Argon2 modules are C-wrappers which I'd prefer to avoid. SQLite3 and such is already enough of a headache.

**Comment by tracker1** [comment]
Yeah... not sure if it would be possible for a webassembly build of sqlite to work with the node FS interfaces... Might be slightly slower than native module, but much easier to load/port if so.

Have you considered a switch to [better-sqlite3](https://www.npmjs.com/package/better-sqlite3)?  Not sure how many spots it would take changing... it will download a pre-built module if available.  I just put in a suggestion to switch from travis to github actions so that windows can be included.

**Comment by NuSkooler** [comment]
> Have you considered a switch to better-sqlite3? 
I've looked at it, but it's a huge change. If someone wants to give it a go, it would be great!

**Comment by NuSkooler** [comment]
This is currently such a low priority. If someone wants to take it, feel free to create a new ticket for e.g. Argon2 or re-open this one.
