### ISSUE TITLE
Installation issue - python as a dependency

### ISSUE THREAD

**Issue by ryanfantus** [NuSkooler/enigma-bbs#247]
**A fresh manual installation depends on python**

**Environment**
- [x] I am using Node.js v10.x LTS or higher
- [ ] `npm install` or `yarn` reports success
- Actual Node.js version v10.16.3
- Operating system: Ubuntu 18.04 in Windows Subsystem for Linux (WSL) - Windows 10
- Revision 3ec6cfd

**Expected behavior**
When running `npm install`, installation should complete as normal. However, python is an unlisted dependency and there should either be a check for python before installation or it should be in the documentation as a dependency.

**Actual behavior**
`npm install` fails with `gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable. `

**Steps to reproduce**
Fresh, minimal linux - follow the docs to install enigma-bbs manually without first installing python.

**Comment by NuSkooler** [comment]
Python is a particularly sticky subject with some OS's as it's part of their core & accidentally installing a different flavor can be very bad. Will look into either way.

Side note: You may want to consider the `0.0.10-alpha` branch vs current `0.0.9-alpha`.

**Comment by davestephens** [comment]
Maybe we could put down pyenv as a dependency and force a specific version?
Maybe a little heavy handed though as I'm not sure this has come up before?

**Comment by tracker1** [comment]
Worth noting, for Node Gyp, it's Python 2.7.x specifically.

**Comment by NuSkooler** [comment]
I haven't looked, but it may be possible to have a self-contained Python just for this purpose, similar to how nvm packages up stuff.

**Comment by NuSkooler** [comment]
`install.sh` now checks for various compatible Python installations and prompts if it can't find one.
