### ISSUE TITLE
Creating and replying to messages

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#25]
A few things:

- Replying to messages should only allow the new message to be entered, not edit the `from`, `to` or `subject` (perhaps this last one, subject, might be editable).
- Empty subjects should not be allowed.

**Comment by NuSkooler** [comment]
I have on my list to prevent empty subjects & messages. 

Editable to & subject is by design, though I may prevent it for direct user to user messages.

**Comment by NuSkooler** [comment]
Requires #8

**Comment by NuSkooler** [comment]
Form validation now occurs for messages when creating & replying, e.g. empty subject lines are no longer allowed.
