### ISSUE TITLE
How to use the built-in webserver?

### ISSUE THREAD

**Issue by danger89** [NuSkooler/enigma-bbs#254]
**Short problem description**

How can I use the web server/web content browser? Documented [here](https://nuskooler.github.io/enigma-bbs/servers/web-server.html).

**Expected behaviour**

I would like to get some list of files shared on the BBS or something useful..? (maybe the news?)

**Actual behaviour**

Only shows me the static index.html file that I put into the `www` folder, or do I miss something?

https://bbs.melroy.org/

**Steps to reproduce**

1. Running Enigma HTTP server (false -> true) in the `config.hjson` file
2. Running Nginx reverse proxy that listen to localhost on that web server port (reroute traffic)
3. Tada!

```
    # Pass requests to Enigma BBS (custom HTTP port 8087)
    location / {
        proxy_pass http://127.0.0.1:8087;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # enables WS support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

**Comment by NuSkooler** [comment]
@danger89 The built in web server is currently a generic-ish concept with other bits built on top. Currently this is:
* Tied in with password reset links and 2FA management/registration
* Serving of static files
* HTTP(S) downloads via the file base

There is currently _not_ a full file base exposed via a web interface. IMO that's outside the scope of a BBS so I haven't put it in. With that said, if you have interest and want to create a mod to do so it would be quite easy and I'd consider a PR for such things.

I'm not sure what you mean by "maybe news"? A mod could also show message areas if that's what you mean (see the Gopher server for an example -- you could build on top of the web server in a similar fashion)

**Comment by NuSkooler** [comment]
@danger89  are you good on this one?

**Comment by danger89** [comment]
Yea, let's park this discussion for now. I was more a question since it was for me not clearly documented.
