### ISSUE TITLE
Move the copyright info from connect.js into config.hjson?

### ISSUE THREAD

**Issue by flewid** [NuSkooler/enigma-bbs#258]
Would it be possible to move the copyright info into the configuration file, and, a flag to have it displayed or not displayed, as well as being able to configure the text through the configuration file?

**Comment by NuSkooler** [comment]
As it's a copyright banner, I don't think I'll be moving it out. That said, the license on ENiGMA 1/2 which permits you to move it (e.g. modify your `connect.js` or make your own connect module.
