### ISSUE TITLE
Change Spacing on Acheivements

### ISSUE THREAD

**Issue by flewid** [NuSkooler/enigma-bbs#259]
The achievments list isn't spaced properly, after the "8:12pm" or other entries that don't have two digits, a space should be entered 'automatically' so the spacing remains the same.

see screenshot:

[link](https://www.dropbox.com/s/h007bqitq7invo1/Screenshot%202020-02-29%2023.50.04.png?dl=0)

**Comment by NuSkooler** [comment]
I'll look at this when I get a chance, but basically just adjust the format code to adjust e.g. the date column min width in the `theme.hjson`. You can see other examples there. Accepting PRs!

**Comment by flewid** [comment]
Great thanks. Fixed it.

dateTimeFormat: MMM Do h:mma
to
dateTimeFormat: MMM Do hh:mma

Thanks!

**Comment by cognitivegears** [comment]
@NuSkooler Sounds like this was fixed quite a while ago, can this be closed?
