### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#26]
Are there plans to localize? I am not interested in any other language pack, but others might. What I am interested in is to change the prompts and other strings to ones that are more appropriate for a professional environment.

**Comment by NuSkooler** [comment]
Localization is on my list. Most of what you see currently is simply art files (including the pause prompt). Strings (e.g. that populate lightbar entries) are found in `menu.hjson` -- these will be localizable & themeable in the future.

**Comment by NuSkooler** [comment]
Some current design thoughts:

* Gettext style replacement. That is, strings will be looked up for their localized at runtime. For example, "A localized string" -> "Eine lokalisierte Zeichenfolge" if the users locale is "de"
* `strings.hjson` files can contain 1:n languages and localized strings:
```hjson
de: {
  locale_name: Deutsche
  "A localized string": Eine lokalisierte Zeichenfolge
}
```
* Standard fallback system for locales, e.g. "de_DE" -> "de" -> original string (non localized)

* `strings.hjson` can live in *mods/* and *mods/themes/themeName/*. The result will be merged with the theme taking top priority on collisions

**Comment by NuSkooler** [comment]
At this point there are **very few** strings that cannot be _themed_. Localization in it's proper form has dropped down in priority.

**Comment by cognitivegears** [comment]
Based on #478 I think we can close this? Thoughts?

**Comment by NuSkooler** [comment]
@cognitivegears #478 doesn't 100% solve localization, but leaves just a bit that would be English hard coded currently. Without activity on the ticket, I'm happy to close it though. Anyone is welcome to (re)open a ticket if they need more.
