### ISSUE TITLE
On global newscan, hitting 'M' to mark as read, still shows up on next login.

### ISSUE THREAD

**Issue by flewid** [NuSkooler/enigma-bbs#260]
I sent myself a test message, login, perform the global newscan, on the main screen I hit 'M' to mark as read, but then when I login again the next time and perform a global newscan, the message still appears as new.

**Comment by NuSkooler** [comment]
@flewid are you able to produce `trace` level logs for this?

**Comment by flewid** [comment]
This appears to be fixed or was a temporary glitch i cannot reproduce it on the latest beta source.

**Comment by NuSkooler** [comment]
@flewid Awesome thank you! If it happens again feel free to re-open.
