### ISSUE TITLE
Idle timeout kicks user when on a telnet bridge downloading files

### ISSUE THREAD

**Issue by swarmdog** [NuSkooler/enigma-bbs#262]
**Expected behavior**
Idle timeout does not disconnect user while downloading over a telnet bridge to a service such as ArchaicNET.

**Actual behavior**
After idle time is reached, user is disconnected, despite download in progress.

**Comment by NuSkooler** [comment]
Fix pushed to master. Activity timeout is updated as I/O is completed.
