### ISSUE TITLE
Broken "General Art Information" link in doc

### ISSUE THREAD

**Issue by squintgit** [NuSkooler/enigma-bbs#264]
On the documentation page https://nuskooler.github.io/enigma-bbs/configuration/menu-hjson.html

it links to a "General Art Information" page (https://nuskooler.github.io/docs/art/general.md)

but it's a broken link

**Comment by SemperFu** [comment]
https://github.com/NuSkooler/enigma-bbs/pull/277 should fix.

Don't really need multiple issues for links in the same page.

**Comment by wts42** [comment]
@NuSkooler: can be closed because of PR #287
