### ISSUE TITLE
Broken "MCI Codes" link in doc

### ISSUE THREAD

**Issue by squintgit** [NuSkooler/enigma-bbs#265]
On the documentation page https://nuskooler.github.io/enigma-bbs/configuration/menu-hjson.html

it links to a "MCI Codes" page (https://nuskooler.github.io/docs/art/mci.md)

but it's a broken link

**Comment by SemperFu** [comment]
Also fixed in https://github.com/NuSkooler/enigma-bbs/pull/277

**Comment by wts42** [comment]
Is somebody working on the broken links issue in documentation?

**Comment by NuSkooler** [comment]
>  If not, may I start to correct them and make a pull request when finished?

Please do

**Comment by wts42** [comment]
Done. Incoming Pull Request :)

**Comment by wts42** [comment]
@NuSkooler: can be closed because of PR #287

**Comment by NuSkooler** [comment]
@wts42 thank you for these fixes!

**Comment by wts42** [comment]
> @wts42 thank you for these fixes!

My pleasure. Hope I can contribute more when time comes. Until then: thank you for the work on enigma.
