### ISSUE TITLE
Broken links in System Configuration doc

### ISSUE THREAD

**Issue by squintgit** [NuSkooler/enigma-bbs#267]
On the documentation page https://nuskooler.github.io/enigma-bbs/configuration/config-hjson.html

all of these are broken links:

"File Base" - https://nuskooler.github.io/enigma-bbs/configuration/file-transfer-protocols.html
"Message Areas" - https://nuskooler.github.io/docs/messageareas/configuring-a-message-area.md
"Networks" - https://nuskooler.github.io/docs/messageareas/message-networks.md
"NetMail" - https://nuskooler.github.io/docs/messageareas/netmail.md

**Comment by wts42** [comment]
@NuSkooler: can be closed because of PR #287
