### ISSUE TITLE
Support pipe codes for colors

### ISSUE THREAD

**Issue by squintgit** [NuSkooler/enigma-bbs#268]
If ENiGMA supports Renegade pipe color codes, why do they not render in signatures in messages from other boards?

<img width="621" alt="Screen Shot 2020-04-04 at 8 00 37 PM" src="https://user-images.githubusercontent.com/11663794/78464415-fd0b8880-76ae-11ea-8f96-0367cb542715.png">

**Comment by NuSkooler** [comment]
They are not currently supported in the FSE (which is the only area they do not show). There are existing tickets about this. Basically, it's waiting on a complete re-write of the FSE.

**Comment by squintgit** [comment]
Ahh ok sorry about that

**Comment by NuSkooler** [comment]
@squintgit No prob at all, please keep the reports flowin! I'll try to get some of the smaller ones addressed soon.
