### ISSUE TITLE
"os" on System Stats page shows as "Linux" when running on macOS

### ISSUE THREAD

**Issue by squintgit** [NuSkooler/enigma-bbs#269]
**Short problem description**
When running ENiGMA on macOS, the "os" shows as "Linux" on the **System Stats** page.

<img width="752" alt="Screen Shot 2020-04-04 at 8 25 00 PM" src="https://user-images.githubusercontent.com/11663794/78464795-2f1ee980-76b3-11ea-8e30-622fb2e865e2.png">

**Expected behavior**
Not sure if this is expected.

**Actual behavior**
Would like to see it list "macOS".

**Steps to reproduce**
See above.

**Comment by NuSkooler** [comment]
From your screen shot: You're running under a Docker container. So you have a containerized Linux.

**Comment by squintgit** [comment]
Ahh ok thanks
