### ISSUE TITLE
Document customization & modding

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#27]
What can be used to customize the .ANS files? Can they be replaced by simple text files? What is the content in them?

**Comment by NuSkooler** [comment]
Changed the title to reflect need to documentation on customization / modding.

**Comment by NuSkooler** [comment]
For now, some tips:
`menu.hjson` menu entries can contain `art` members. The system uses a fallback approach to find the supplied file: current theme -> mods/art. References to this can include an file extension (e.g. MYART.ANS) or without (MYART). If you do not supply an extension, the system will look for any match (MYART.ANS, MYART.ASC, ...). Note also that randomization will occur if you create files such as MYART1.ANS, MYART2.ANS, etc.

**Comment by NuSkooler** [comment]
Started documenting some things... **much** to go, but check out the docs folder.

**Comment by NuSkooler** [comment]
Please see [MCI](https://github.com/NuSkooler/enigma-bbs/blob/master/docs/mci.md), [Menu System](https://github.com/NuSkooler/enigma-bbs/blob/master/docs/menu_system.md), etc. Needs a lot of work (input *very much wanted* and/or PRs!) but there is something there :)

**Comment by NuSkooler** [comment]
Some areas needing attention -- not limited to:

- Some more general `menu.hjson` and `theme.hjson` information & examples
- Custom MCI labels controlled via `theme.hjson`
- Various menu flags, linking between menus, common `MenuModule` methods

**Comment by danger89** [comment]
Yea now you touch the part that needs some work.. I don't want to ask questions like 'sex', 'birthdate', affitation' etc. etc. from the user registration page. I think I can edit the NUA.ANS file, and remove those for example. However afaik I don't see any defaults values for those fields in nua.js:
```
					sex					: formData.value.sex,
					location			: formData.value.location,
					affiliation			: formData.value.affils,
					email_address		: formData.value.email,
```

Bottom-line: make your system more generic, so I can more easily configure my board, make fields optional or not visible at all without BBS core application impact.

**Comment by danger89** [comment]
So how to change the theme to my theme in the config.hjson file? It's guessing again..

https://github.com/NuSkooler/enigma-bbs/blob/master/core/config.js#L121

**Comment by NuSkooler** [comment]
@danger89 You can create your own `nua.js` type file and use it to do whatever you like for the new user application. If you just want them to default to blank, a ` || ''` would work -- then you can use the existing `nua.js` and just allow empty values by modifying what your `menu.hjson` does with it (currently it complains if some fields are empty)

Changing the default theme and/or pre-login theme (before a user is selected) is covered [in the config docs](https://github.com/NuSkooler/enigma-bbs/blob/master/docs/config.md). Accepting PR's to make clearer to new users!

**Comment by NuSkooler** [comment]
[A LOT of new docs](https://github.com/NuSkooler/enigma-bbs/tree/0.0.9-alpha/docs) have gone in covering modding, art/theming, etc. More are to come, but I think this can be considered complete.

Please open specifics for missing/confusing/whatever docs.
