### ISSUE TITLE
Add Ability to Import All File Areas at Once

### ISSUE THREAD

**Issue by flewid** [NuSkooler/enigma-bbs#271]
It would be cool if we could import all files at once, instead of per area

fb scan --full --all 

or similar

**Comment by NuSkooler** [comment]
What do you think of `./oputil.js fb scan PATTERN`. Scan can take e.g. `--tags`, so you could do something like:
```
./oputil.js fb scan --tags warez,retro '*retro*'
```

**Comment by flewid** [comment]
Yeah, I think that would work.

**Comment by NuSkooler** [comment]
You should now be able to do as prescribed above. Please let me know if you have issues!

**Comment by cwstephenson71** [comment]
Yes!! Thank you!
