### ISSUE TITLE
Suggestion:   option to trigger List of pending users.

### ISSUE THREAD

**Issue by dcialdella** [NuSkooler/enigma-bbs#272]
Not a BUG, a suggestion

define an option to see users pending to be activated.
./oputil.js user pending (or something similar)

**Comment by NuSkooler** [comment]
You can now:
`./oputil.js user list [all|disabled|inactive|active|locked]` (`all` is default). This just provides a simple list of user ID and username. Use `./oputil.js user info USERNAME` for user details.
