### ISSUE TITLE
Idle Timeout Logoff during long file transfers

### ISSUE THREAD

**Issue by phenomprod** [NuSkooler/enigma-bbs#275]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

Idle Timeout Logoff during long file transfers.

**Environment**
- [x] I am using Node.js v10.x LTS or higher
- [x] `npm install` or `yarn` reports success
- Node v10.20.1
- OS: Linux Mint 4.15.0-91
- Revision (`git rev-parse --short HEAD`):

Expected Behavior:
Transfers all files (regardless of how long).

Actual Behavior:
I get timed out and logged off towards the end of my transfer if I exceed the set idle timout.

Steps to reproduce:
Upload large files that will take more then the set idle timeout for a users login session.

**Comment by NuSkooler** [comment]
Note: `0.0.10-alpha`

**Comment by NuSkooler** [comment]
Should now be fixed with 387dfb3b5dfbb7ce3a4a976bc1f6f56d6f86cc07
