### ISSUE TITLE
Theme creation

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#28]
Is there a template somewhere which will help with the creation of a theme? Some information on this would be great.

**Comment by Fastidious** [comment]
This might relate to #27.

**Comment by NuSkooler** [comment]
Take a look at mods/themes/luciano_blocktronics. There is a `theme.hjson` and related art files.

**Comment by NuSkooler** [comment]
BTW: If you give theme creation a try, please add comments / suggestions / etc. It's not considered complete by any means, but also I need ideas from outside my own mind :)

**Comment by danger89** [comment]
Well...

I think this is still redudant. Which one should I pick for creating my own theme?
```
defaults: {
    theme: super-fancy-theme
}
preLoginTheme: luciano_blocktronics
```

The defaults or preLoginTheme?

**Comment by NuSkooler** [comment]
@danger89 Not redundant, they represent different things:

* `defaults.theme` is the default-assigned theme (for new users)
* `preLoginTheme` is the theme used before a user logs in (matrix, NUA, etc.)

**Comment by danger89** [comment]
Aha! Maybe I will update the docs again with this info. 

I didn't found it yet, but I guess it's then also possible to change the theme used for an individual user?

**Comment by NuSkooler** [comment]
@danger89 Yes, users can change their themes from available themes in their configuration. `defaults.theme` is simply assigned to them at creation.

Each theme is it's own directory (`luciano_blocktronics` for example) that includes a `theme.hjson`. This file aligns with your `menu.hjson` (look at some examples in the two by matching up keys). 

Definitely needs docs... it's on my list :)

**Comment by NuSkooler** [comment]
Still needs a lot of TLC: https://github.com/NuSkooler/enigma-bbs/blob/0.0.9-alpha/docs/art/themes.md

**Comment by danger89** [comment]
Its  a start :)

**Comment by NuSkooler** [comment]
More updates. More to come...

**Comment by NuSkooler** [comment]
Closing this one. The docs can always use more love, PR's welcome.
