### ISSUE TITLE
Configuration File Revamp

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#280]
Configuration files (`config.hjson`, `menu.hjson`/`prompt.hjson` and friends, `theme.hjson`, etc.) could use a revamp.

Creating this ticket to replace some existing so we have a little better organization:
* Configuration / Menu Include System #220
* Suggestion - Break up Menu file #158

Updates on current design thoughts:
## General Goals
* Remain HJSON driven
* Configurations to remain hot-reload
* Self references (reference 'a.b', from 'a.d.e', etc.)
* Templates (use self ref as a template)
* Environment variable support
* Includes
* Good reporting of syntax errors

### Includes
A the very least, a top level include:
```
// my-bbs.hjson
{
  includes: [
    // default menus
    enigma-bbs-default-menus.hjson
    // others
    my-menus.hjson
  ]
}
```

## Self References
```
{
  foo: {
    bar: {
      baz: foobar!
    }
  }
  
  fubar: {
    // resolves to { baz: foobar! } above
    bar: @reference:foo.bar
  }
}
```

## Environment Variables
```
{
  foo: {
    // SOME_VAR in current process environment
    // if no type is supplied, the value is a string
    bar: @environment:SOME_VAR
    
    // see notes on types below
    barBoolean: @environment:BOOL_VAR:boolean

    // arrays
    barNumberArray: @environment:NUM_VAR:number:array
  }
}
```
As shown above, environment variables default to strings. An optional type suffix can be supplied to coerce to a particular type (if the conversion is not possible, the full spec will remain). An additional `array` suffix can be supplied to convert to an array (think `export FOO="1,2,3"` -> `[ 1, 2, 3 ]`).

## Notes
* Main file (that is, where `includes` reside) override any configuration from included files
* For simplicity, `includes` will be main/top-level only (no nesting)

Feedback is of course very welcome! If you're like to play with a toy implementation that illustrates some of the above follow this link: https://repl.it/@NuSkooler/ConfigRevampTests

**Comment by planeguy** [comment]
I looked around a bit, and there's a small community using this syntax for includes:

```json
{
    "property": { "...":"file-to-include.json"}
}
```

a thought about this is if we merge at load time (it looks like we reload the config with file watch?), then we could do double-duty on includes and self-references eg:

```
{
   a: {...: thing.hjson}
   b:{...:thing.hjson}
   c: {
     art: CONNECT
     ...:thing.hjson
   }
}
```

**Comment by davestephens** [comment]
> Remain HJSON driven

What's the thinking behind this? IDE support is bad, and whilst it's supposedly a "relaxed" version of JSON, I personally think that makes it more annoying to use as you can use JSON or HJSON, and the ENiGMA configs reflect that.

What about:
- TOML
- YAML

TOML is very similar to ini syntax that people are used to from BBS days of yore, and it's also typed - fixing the problems with ini. Editor support is decent too. 

YAML is also a good choice, also has good editor support - but the strict whitespacing will hurt the heads of those that aren't used to it.

**Comment by NuSkooler** [comment]
@planeguy Can you point to where this is being used? It seems... odd. RE: self references, ENiG configs already use the "@foo" type system for other parts of the config, so it remains consistent that way.

**Comment by NuSkooler** [comment]
@davestephens I guess I disagree on the IDE support. There is a plugin for most of the popular editors. If there is a mix of JSON and HJSON in the config that's probably a goof.

I'm honestly very happy with HJSON the the config setup.

**Comment by planeguy** [comment]
> @planeguy Can you point to where this is being used? It seems... odd. RE: self references, ENiG configs already use the "@foo" type system for other parts of the config, so it remains consistent that way.

there were only a couple of links about it mostly in Python and PHP. should probably keep using @blah.

hmm maybe @include:filename?

**Comment by NuSkooler** [comment]
@planeguy The problem is we need _1:n_ includes where `@include:filename` would only allow for one (since in *JSON that is name:value).

**Comment by NuSkooler** [comment]
If anyone is interested in playing around with the WIP it can be found here: https://github.com/NuSkooler/enigma-bbs/tree/280-config-revamp

A PR will be opened for anyone interested once it's in with menu/theme support. I also plan on breaking up some of the existing configurations slightly which should make management of updates easier in the future.

**Comment by NuSkooler** [comment]
Merged in. Please see the `UPGRADE.md` document.
