### ISSUE TITLE
Address for WebSockets *localhost/127.0.0.1*

### ISSUE THREAD

**Issue by flewid** [NuSkooler/enigma-bbs#285]
per discord discussion;

I think I may need a fix in for WebSockets [so you can use 127.0.0.1 as 'address']
 It doesn't have an address member currently, I forget why (or if it's just a oversight)

**Comment by NuSkooler** [comment]
Thank you for the reminder! I will take a look at this soon

**Comment by NuSkooler** [comment]
@flewid Apparently I had already fixed this and just didn't yet document. Did you try this in your config?
```
webSoccket: {
  ws: { // or wss for secure
    enabled: true
    port: 8810
    address: 127.0.0.1
  }
}
```

This works for me:
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:8810          0.0.0.0:*               LISTEN      92838/node 
```

**Comment by NuSkooler** [comment]
Closing due to the above. PR's welcome for improved WebSocket docs. If this doesn't work feel free to re-open this ticket.

**Comment by flewid** [comment]
Yep - it listens fine - I can connect locally as well - but if I point VTX to it, it fails to connect (maybe i'm confused how VTX works though and it needs something public facing?)

**Comment by NuSkooler** [comment]
@flewid Web browsers won't connect to ws:// (insecure, non-TLS) sockets without hoops and shenanigans. You need to conect to wss:// (secure, TLS).

ENiGMA supports both:
* You can configure enig to listen on a secure port and use the right certs/etc. and point VTX directly to it -OR-
* You can put enigma behind a TLS terminating proxy and connect wss:// -> proxy -> enigma (non-secure). 

The 2nd option is what I do as it's more convenient to use something like Caddy to maintain ACME/Let's Encrypt certs and I use it for other purposes outside VTX/WebSockets.

**Comment by flewid** [comment]
Yep understood on the ws:// vs wss://. 

I have

```
wss: {
                port: 8812
                enabled: true
		        address: 127.0.0.1
```

then in vtx config i have

`  wsConnect:      "wss://127.0.0.1:8812",`

but this gives me 

https://www.dropbox.com/s/xny8tlz7ccjq2d3/Screenshot%202020-06-06%2019.25.55.png?dl=0

then if i change vtx config to 

`  wsConnect:      "wss://domain.name:8812",`

it works fine. 

am i misunderstanding how vtx works? I didn't want to leave 8812 open to the world if i can help it.
