### ISSUE TITLE
Consider moving away from Bunyan

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#286]
Bunyan has worked amazingly well and I'm very happy with it overall. However, it at least appears to have become a dead project. See [here](https://github.com/trentm/node-bunyan/issues/640) and [here](https://github.com/trentm/node-bunyan/issues/586], etc.

Consider moving away from Bunyan to something similar:
* JSON based logging
* Pretty-printer
* Similar enough syntax that the upgrade is minimal. The general signature for log methods is `([object], message)`
* Log rotation (may need to be separate, but should be built in to ENiGMA)

[Pino](http://getpino.io/#/) seems to be a continuation of the Bunyan spirit. One thing that is missing is log rotation, so something else would need to be created here.

Others?

**Comment by davestephens** [comment]
Funnily enough I'm working on a massive structured logging project at work
at the moment, and the general consensus is "JSON sucks for logs", mostly
because it's difficult to read without additional tooling. (Enigma docs re
logging case in point). It's fine if you're jamming everything into the
likes of ELK, but nobody running ENiG is.

We've also come to the consensus that to keep structure but whilst still
maintaining readability, logfmt is the way to go. Heroku maintain
node-logfmt and it looks pretty decent...

**Comment by NuSkooler** [comment]
> Funnily enough I'm working on a massive structured logging project at work
at the moment, and the general consensus is "JSON sucks for logs"

At my work place we just moved to JSON for a number of things for the exact opposite reason. 😆 

I'm not sure when you don't have the most basic of tooling (`tail` is a tool; piping to `bunyan` currently is part of the same pipeline). I suppose if you load a log into a text editor, but I just dump it all through the processor _first_ even if handed a .log file.  I've looked at `logfmt` a number of times. From their [main page](https://www.brandur.org/logfmt):

> In development, a log output formatter can then give the msg field special treatment by displaying it in way that a human can easily read (along with other special fields like level)

(they suggest using a formatter because this sucks):
```
level=info msg="Stopping all fetchers"
  tag=stopping_fetchers id=ConsumerFetcherManager-1382721708341
  module=kafka.consumer.ConsumerFetcherManager
```

But this is nice:
```
info | Stopping all fetchers          module=kafka.consumer.ConsumerFetcherManager
info | Performing log compaction      module=kafka.compacter.LogCompactionManager
info | Performing garbage collection  module=kafka.cleaner.GarbageCollectionManager
info | Starting all fetchers          module=kafka.consumer.ConsumerFetcherManager
```

**Comment by NuSkooler** [comment]
@coolacid This is essentially what ENiGMA already does:

Example:
```
const extra = { // usually you'd inline this, but for illustration
  foo : "bar",
  baz : 1234,
};

log.error(extra, "Something went terribly wrong!");
```

**Comment by coolacid** [comment]
@NuSkooler This is what I get for reading email and not looking at code (that I haven't looked at in a while). 

Having said that, as a part time dev, part time pipeline designer, I'd go with the last statement in your last message `Perhaps it would be nice if the log allowed backends for particular formats?`

**Comment by NuSkooler** [comment]
It looks like Pino allows for most of what is being asked for via transports/etc. E.g. one could simply plug a transport that outputs to format $foo or sends to $bar, so on.

**Comment by vordimous** [comment]
https://github.com/trentm/node-bunyan/releases/tag/2.0.4 release is out. should this ticket be closed?
