### ISSUE TITLE
Make quicklogin configurable

### ISSUE THREAD

**Issue by wts42** [NuSkooler/enigma-bbs#288]
Instead of selecting 'yes' or 'no' at the quicklogin screen it would be a Qol enhancement to make it one time selectable in the user's configuration.

**Comment by NuSkooler** [comment]
I've considered adding the ability to check arbitrary user properties via ACS. I'm not 100% sure yet what the syntax would be, but perhaps something like `PV[name,value]` would return true if property "name" was set to "value". Something like this would allow for exposing a saved property (for quick login in this example) to ACS. ACS can already drive menu decisions, so it would just fit in.

**Comment by wts42** [comment]
Sounds like a universal solution. I like it.

**Comment by NuSkooler** [comment]
ACS check `PV[name,value]` has been added to `master` as it was very trivial to implement. For this particular issue, I'd love if someone wants to take a go at it. Basically:
* Add a new user property (see user_property.js) for storing the state.
* Expose this in the user configuration. prompt | yes | no
* Now you can check ACS before the newscan module in the default login flow.

**Comment by testoverride** [comment]
I am looking at some quick login things for my bbs. I am not sure if anything will come from it as i am just learning enigma and have some questions.

**Comment by NuSkooler** [comment]
@testoverride Please ask in https://github.com/NuSkooler/enigma-bbs/discussions

**Comment by NuSkooler** [comment]
@wts42 did you ever try this? I'm going to close the ticket as it should be resolved. If someone wants to contribute the configuration in e.g. the user config screen, I'll take it :)
