### ISSUE TITLE
Missing FSE functionality

### ISSUE THREAD

**Issue by Fastidious** [NuSkooler/enigma-bbs#29]
The help on the message reading refers to commands that do not work. I am guessing it is not implemented yet. But it also breaks the screen. See attached (using iTerm2).

![help](https://cloud.githubusercontent.com/assets/8352292/11321326/09e337ea-9088-11e5-82c3-fcf5a491c698.gif)

**Comment by NuSkooler** [comment]
Screen corruption should be resolved with 87b6e24

Some of the missing functionality is WIP

**Comment by NuSkooler** [comment]
Missing functionality:

- Jump to message #

(This is a placeholder & will be edited with the complete list)

**Comment by NuSkooler** [comment]
There are a few things remaining that I may take a look at for 0.0.9-alpha. Major things are in other tickets.

**Comment by NuSkooler** [comment]
Created tickets for remaining specifics. Closing this one.
