### ISSUE TITLE
my @menu actionKey doesn't work 

### ISSUE THREAD

**Issue by planeguy** [NuSkooler/enigma-bbs#290]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
When I tried to set an actionKey to go to a particular menu of mine, it doesn't work. an actionKey to a *different* menu works and the menu I am trying to go to works independently of the screen i am trying to actionKey it into.

**Environment**
- [x] I am using Node.js v10.x LTS or higher
- [x] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): v10.20.1
- Operating system (`uname -a` on *nix systems): Linux stripittoride 4.19.97+ #1294 Thu Jan 30 13:10:54 GMT 2020 armv6l GNU/Linux
- Revision (`git rev-parse --short HEAD`): edc89ae

**Expected behavior**
When on the message list screen, using the actionKey "p" should take you to the new message post menu ("poast")

**Actual behavior**
Nothing happens

**Steps to reproduce**
1. Use this menu: https://gist.github.com/planeguy/827cb774f81473a75316276771057e85?fbclid=IwAR1FDl_sV8Du1GiMXmIgKzu-x7N6oeX8jiV9ht1g_g15c4HiLAA54C4CQBI
2. Log in and get to the main menu
3. Choose m for messages
4. Press p

For counter examples:
1. at the main menu choose p (which opens the target menu just fine)
2. at the message list press shift+c, which takes you to the main menu vai a @menu command (not @system prevMenu)

**Comment by planeguy** [comment]
### Important new info

So I was adding more stuff into the main menu while i was waiting and noticed that my user theme was NOT set to the theme I was using as my default (as sysop, of course it was set to Mystery Skull since the new one didn't exists at the time). Once I set the theme properly, the menu worked, but i don't know why the same menu code would be influenced by the art theme since i copied pasted the theme from the original blocktronics.

Anyway maybe that's another ticket. Closing this one.

**Comment by NuSkooler** [comment]
@planeguy Does that mean you figured it out?

**Comment by planeguy** [comment]
no I didn't, I **thought** i had though 😂

still having the issue.

**Comment by NuSkooler** [comment]
There is a conflict in the `msg_list` module's form data arg of `message` and what the msg display module wants to use (allowing a message to be passed in). This is fixed in code, but you'll need to change your `menu.hjson` entry's `argName: message` to `argName: messageIndex`. This will be the default in the config revamp branch.
