### ISSUE TITLE
Theme Changing..

### ISSUE THREAD

**Issue by bucko219** [NuSkooler/enigma-bbs#294]
Trying to change Theme in the config menu while online does not allow it to be changed. Maybe I am doing something wrong, but when I hit C and tab down to Theme Mystery Skull can not be changed. Even though I now have 2 themes there..

**Comment by NuSkooler** [comment]
Please provide `trace` level logs of startup (where themes are loaded) and when entering the user config.
In general you only need `art/themes/some_theme/theme.hjson` where the `theme.hjson` has a valid `info` section.

**Comment by bucko219** [comment]
Bryan, close this issue.. I never should have opened it.. It was operator error..
