### ISSUE TITLE
oputil.js config new throwing an error on raspberry pi

### ISSUE THREAD

**Issue by AndreRobitaille** [NuSkooler/enigma-bbs#296]
**Short problem description**

**Environment**
- [X] I am using Node.js v12.x LTS or higher
- [X] `npm install` or `yarn` reports success --- 408 packages; 12 funding; 0 vulns
- Actual Node.js version (`node --version`): 12.18.3
- Operating system (`uname -a` on *nix systems): 
Linux bbs-andre 5.4.51-v7+ #1327 SMP Thu Jul 23 10:58:46 BST 2020 armv7l GNU/Linux
- Revision (`git rev-parse --short HEAD`): 2496340

**Expected behavior**

Install script finishes without error.

**Actual behavior**

Install script dies.

**Steps to reproduce**
Fully updated Raspberry Pi 3b using install script, then adding all the recommended support binaries. Install script was run as standard pi user, no sudo.

pi@bbs-andre:~/enigma-bbs $ ./oputil.js config new
? Create a new configuration? (y/N) y
? Create a new configuration? Yes
? Configuration path: (./config/config.hjson) 
? Configuration path: ./config/config.hjson
? BBS name: Ham Central BBS
? BBS name: Ham Central BBS
? First message conference: (Local) 
? First message conference: Local
? Conference description: (Local Areas) 
? Conference description: Local Areas
? First area in message conference: (General) 
? First area in message conference: General
? Area description: (General chit-chat) 
? Area description: General chit-chat
? Logging level: (Use arrow keys)
? Logging level: Info
(node:918) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/home/pi/enigma-bbs/config/menus/ham_central_bbs-main.hjson'
    at Object.openSync (fs.js:462:3)
    at Object.writeFileSync (fs.js:1362:35)
    at /home/pi/enigma-bbs/core/oputil/oputil_config.js:261:12
    at /home/pi/enigma-bbs/core/oputil/oputil_config.js:212:20
    at wrapper (/home/pi/enigma-bbs/node_modules/async/dist/async.js:268:20)
    at next (/home/pi/enigma-bbs/node_modules/async/dist/async.js:4582:24)
    at /home/pi/enigma-bbs/node_modules/async/dist/async.js:321:20
    at /home/pi/enigma-bbs/core/oputil/oputil_config.js:207:28
    at /home/pi/enigma-bbs/core/oputil/oputil_common.js:123:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:918) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:918) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by NuSkooler** [comment]
I will try to look at this soon, hopefully tonight.

**Comment by AndreRobitaille** [comment]
Thanks. I'm willing to test if needed. I'm brand new to Enigma1/2 and Node.js, so I can't be much more helpful than that at the moment.

**Comment by NuSkooler** [comment]
Fixed in master. `menus` director was not being created.
