### ISSUE TITLE
Themes..

### ISSUE THREAD

**Issue by bucko219** [NuSkooler/enigma-bbs#297]
Not sure if this is a bug or maybe a mistake on my end.. I recently created a new theme, I copied the Luciano them to a new directory and named it "NewTheme" I also changed the name in the theme.hjson. My users who have the original Luciano theme, get a mix of both themes. So if they pick Luciano as their theme they will get some screens that I have created for the new theme (Which is now the default) and then it will flip back to the Luciano theme. I know the themes area is not complete and still needs work, so this is just something to look at for when work begins on the Themes area again..

**Comment by NuSkooler** [comment]
Art is selected via a fallback system - is that what you're experiencing?
https://github.com/NuSkooler/enigma-bbs/blob/master/docs/art/general.md#art-spec

**Comment by bucko219** [comment]
It's possible, he had his theme set to luciano and it was flip flopping between the new theme and the original theme, I will try to get more info...

**Comment by NuSkooler** [comment]
@bucko219  any update on this?

**Comment by bucko219** [comment]
Hi Bryan, I haven't had the user who logged on and brought it to my
attention back since then. I tried it myself and used my theme and had no
issues at all, switching to the stock blocktronics theme it seemed to work
fine.. If you want to close the ticket close it and if he comes back and
shows me (I told him to make me a video of it) I will re-open a new ticket..

Al

**Comment by NuSkooler** [comment]
Sounds good. Feel free to re-open if you see this again!
