### ISSUE TITLE
Error 401 trying to access any static resource besides index.html

### ISSUE THREAD

**Issue by blackmagic-consult** [NuSkooler/enigma-bbs#299]
I have Enigma running with an HTTPS Only web server, which I'd like to use for a static site for the bbs. Index.html can be accessed normally, but all other static resources, including Favicons, css, javascript, returns a 401 error.

File mirroring from the file base works as expected. My config file follows the documentation to the letter.

**Environment**
- Node v12.18.3
- Ubuntu 20 (5.4.0-42-generic #46-Ubuntu x86_64 GNU/Linux)
- Revision 38890b6

**Comment by blackmagic-consult** [comment]
Update; Custom error messages are also accessible.

**Comment by NuSkooler** [comment]
@blackmagic-consult  Please provide minimal configuration and trace level logs. The default location for static files is `enigma-bbs/www`

**Comment by blackmagic-consult** [comment]
As far as I can tell, trace logs aren't telling me anything. Here's one with a normal startup, and me requesting the web server - no calls to the web server appear in the logs at all?

https://pastebin.com/Wnddx1i9

The server configuration is as so:
```
web: {
            //  Set to your public FQDN
            domain: panoptic.onl

            //  Standard issue "www" folder. Place static content here
            staticRoot: /path-obscured/enigma-bbs/www

            //
            //  This block configures password reset emails. Template files
            //  support the following variables:
            //  * %BOARDNAME%       : Name of BBS
            //  * %USERNAME%        : Username of whom to reset password
            //  * %TOKEN%           : Reset token
            //  * %RESET_URL%       : In case of email, the link to follow
            //    for reset. In case of landing page, URL to POST submit reset form.
            //
            resetPassword: {
                resetPassEmailText: /path-obscured/enigma-bbs/misc/reset_password_email.template.txt
                resetPassEmailHtml: /path-obscured/enigma-bbs/misc/reset_password_email.template.html
                resetPageTemplate: /path-obscured/enigma-bbs/www/reset_password.template.html
            }
            http: {
                port: 80
                enabled: true
            }
            https: {
                port: 443
                enabled: true

                //
                //  Note that web browsers will not trust self-signed certs. Look
                //  into Let's Encrypt and perhaps running ENiGMA behind another
                //  web server such as Caddy.
                //
                certPem: /path-obscured/panoptic.onl/fullchain.pem
                keyPem: /path-obscured/panoptic.onl/privkey.pem
            }

```

**Comment by NuSkooler** [comment]
@blackmagic-consult I just double checked with a clean install by creating a `index.html` in the `www` directory and flipping HTTP to be enabled. Browsed to http://localhost:8080 and it served up.

I see that you're trying to use ports `80` and `443`. Both are privileged ports in modern operating systems. I suspect the bind is failing. I probably need to beef up the logs for the `web.js` module... there isn't much, but I'd check there first.

As for the port binding, there is a number of ways to get around this. Personally my BBS is behind a TLS termination proxy so I just route to port 8080 in the backend. See also: https://superuser.com/questions/710253/allow-non-root-process-to-bind-to-port-80-and-443

**Comment by blackmagic-consult** [comment]
Hey NuSkooler;

The ports are served up properly, using the method in your link. 

Again, the index.html always serves fine - it's any other resources served in the www/ folder that gives a 401, i.e. CSS files, Javascript, images, etc. Running the web server on higher ports results in the same issue.

**Comment by NuSkooler** [comment]
The `index.html` is not special in any way. If you can serve that, you can serve whatever. Are you sure you're pointing to them correctly? I'm serving up CSS and JS from my vanilla installation.

**Comment by blackmagic-consult** [comment]
I think you're misunderstanding me.

I'm aware index.html is not special. In fact, on my server, it has the same ownership and file permissions as everything else.

Which is why it's strange that GET requests for index.html work, but FAIL with a HTTP/1.1 401 error for every other file in the served folder.

Not a 404 error - a 401, which means the files exist, but the server is not allowing people to access them. 

See attached photo for the Network Logs - it GET's index.html, and any external resource fine - but any other resources are 401'd.

![image](https://user-images.githubusercontent.com/52931605/89826917-26806900-db14-11ea-91fd-3fdc0717d88e.png)

**Comment by NuSkooler** [comment]
Ah I see.

The default route for content is "/static/foo", so change e.g.:
```
<script ... src="vtxdata.js"></script>
```
to
```
<script ... src="/static/vtxdata.js"></script>
```

**Comment by blackmagic-consult** [comment]
This corrected it! Thanks NuSkooler;

I looked through the documentation again and I don't believe this functionality is explicitly stated; Would you like me to submit a PR with updated Docs?

Thanks again.

**Comment by NuSkooler** [comment]
@blackmagic-consult A PR to the docs would be great!
