### ISSUE TITLE
Windows door support

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#30]
Various issues exist on Windows for doors (not limited to):
1. pty.js currently crashes
2. No way to share sockets

Possible solution for (2) is to have a temporary server that spawns for communication purposes (e.g. QEMU and DOSBox can likely use this)

**Comment by tracker1** [comment]
May need a small "shim" loader that can run in DOSBox that will "answer" an immediate connection...

enigma launches dosbox/shim to port NNN where NNN is a prefix and the node number... then an outbound telnet connection to localhost:NNN is made, when the `connect` happens, the shim will then drop out and go into the door.. when the door exits the connection breaks, and the bridge to the connected user stops...

hope that workflow helps.. should be able to do a simple dos shim for the answer in freepascal or something equally simple.

**Comment by tracker1** [comment]
On a similar line, I'd been thinking of creating a door-runner that takes rlogin connections, which abuse using `<username><null><passcode><null><door-id><null>` similar to what synchronet uses to go straight into doors via the web interface.  But only with the door portion, and possibly an outbound hook to validate the passcode.

**Comment by NuSkooler** [comment]
The following solution is now implemented:
The abracadabra module `menu.hjson` door `config` block can now contain a `io` entry with a value of `stdio` or `socket` (default is `stdio`). When the value is `socket` a temporary server will be created and listen on a arbitrary port assigned by the system available as `{srvPort}` in `args`[]. This allows for example QEMU to connect up it's virtual serial port to the server for I/O.

This has been tested with QEMU on Linux, Windows, and OS X with success. It should also work with DOSBox via it's `serial` entry (note: a script/batch file will need to be used to create a dosbox.conf with `{srvPort}` resolved.

Example configuration for PimpWars under a UNIX like system:
```hjson
doorPimpWars: {
  desc: Playing PimpWars
  module: abracadabra
  config: {
    name: PimpWars
    dropFileType: DORINFO
    cmd: /usr/local/bin/qemu-system-i386
    args: [
      "-localtime",
      "/home/enigma/DOS/freedos.img",
      "-chardev",
      "socket,port={srvPort},nowait,host=localhost,id=s0",
      "-device",
      "isa-serial,chardev=s0",
      "-nographic"
    ]
    io: socket
  }
}
```

More information will be provided in the docs soon!
