### ISSUE TITLE
Add text style to Random Rumor (RR) MCI code has no effect

### ISSUE THREAD

**Issue by robbiew** [NuSkooler/enigma-bbs#300]
**Short problem description**
Adding a text style to Random Rumor (RR) MCI code in Main Menu in `theme.hjson` has no effect on rendered text.

**Environment**
- [x] I am using Node.js v12.x LTS or higher
- [x] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): `12.18.3`
- Operating system (`uname -a` on *nix systems):` Linux bbs-server 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Revision (`git rev-parse --short HEAD`): `7c304eb`

**Expected behavior**
Display themed MCI code text.

**Actual behavior**
Theme is not applied to MCI code.

Enigma Log (unclear if it's related to this issue however): 

`
{"name":"ENiGMA½ BBS","hostname":"bbs-server","pid":18565,"nodeId":1,"sessionId":"gNU8O8zgd46","username":"Alpha","level":40,"viewId":1,"msg":"Cannot find view","time":"2020-08-12T15:36:26.721Z","v":0}
`

**Steps to reproduce**

1. Create new custom theme.
2. Add `%RR1` to Main Menu ANSI art file.
3. Add to `theme.hjson` in `menu` block:

```
		menus: {
			mainMenu: {
				mci: {
					RR1: {
						itemFormat: "|10> |03{text!l33t}"
					}
				}
			}

```
4. Log in as user and view Main Menu
5. 'l33t' style has not been applied

---
Cheers,

R

**Comment by NuSkooler** [comment]
Apologies, I should have caught this before. I blame lack of sleep.

`itemFormat` is for lists such as VM/HM (aka lightbars). To apply a text style to a text view you can use `textStyle` or `focusTextStyle`:

```
mainMenu: {
  mci: {
    RR1: {
      textStyle: l33t
    }
  }
}
```

**Comment by robbiew** [comment]
Ah, excellent! Thanks!
