### ISSUE TITLE
Unable to view messages from messageBaseMessageList (List Messages) from Main Menu after hitting RETURN

### ISSUE THREAD

**Issue by robbiew** [NuSkooler/enigma-bbs#301]
**Short problem description**

Message list can be viewed from List Messages menu, but hitting RETURN on highlighted messages does nothing.

**Environment**
- [x] I am using Node.js v12.x LTS or higher
- [x] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): `12.18.3`
- Operating system (`uname -a` on *nix systems):` Linux bbs-server 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Revision (`git rev-parse --short HEAD`): `7c304eb`

**Expected behavior**

When viewing messages in the List Messages menu, I should be able to select a message using the lightbar and hit ENTER to view.

**Actual behavior**
Hitting enter does nothing.

**Steps to reproduce**

1. Install new Enigma.
2. Use default Blocktronics menu.
3. Add a couple test messages.
4. Got to List Messages (L) menu from Main Menu
5. Use lightbar, press enter

---
Cheers,

R

**Comment by NuSkooler** [comment]
Pushed fix to menu template

**Comment by robbiew** [comment]
applied fix manually in my menu file -- works perfect!
Thanks.
