### ISSUE TITLE
Local Doors (Ubuntu 18.04) - issues

### ISSUE THREAD

**Issue by robbiew** [NuSkooler/enigma-bbs#305]
**Short problem description**
I've followed the [instructions ](https://nuskooler.github.io/enigma-bbs/modding/local-doors.html) on how to setup local doors--on multiple fresh installs-- but I've been unable to get doors (like LORD) to run properly:

- using DOSEMU: door loads, but the screen displays garbled ANSI, and local machine emits a BEEP.

**Environment**
- [x] I am using Node.js v12.x LTS or higher
- [x] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): v12.18.3
- Operating system (`uname -a` on *nix systems): Linux bbs-server 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`): f558a61

**Expected behavior**

**Actual behavior**

**Steps to reproduce**

**Comment by robbiew** [comment]
@NuSkooler thanks.
I do think the trouble lies, somehow, in how dosemu is connecting w/ `$_com1 = "virtual"` that's set in the dosemu.conf file. With this set, dosemu freezes. Without it, we get all the boot-up garbage echoed to the local user screen, garbled ansi, etc.

Do you know if it's possible to use a socket connection w/abracadabra + dosemu doors instead?

**Comment by NuSkooler** [comment]
Setting COM to virtual sets DOSEMU to use standard I/O (aka `stdio`) as it's COM interface. So anything written to DOSEMU's `stdin` is available to be read from `COM1` and anything written to `COM1` is placed on `stdout` and picked up and forwarded to your client. Anything boot up that is `ECHO`'d in a batch file would display so you can `ECHO OFF` a lot of stuff.

Are you using a FOSSIL driver with this? If so, have you tried others (or without = "direct")?

**Comment by robbiew** [comment]
Yes, I've tried it with and without FOSSIL driver. @ECHO OFF is at the top of my autoexec.bat file. I'm going to try a fresh install on a fresh machine just to make sure...

**Comment by robbiew** [comment]
Apologies for posting in a closed issue, but I'm getting closer to finding the gremlins :)

Something is definitely happening w/dosemu (v1.4 installed w/ 'apt install dosemu'), and I'm getting these errors when launching a local door from both my test machines:

```
======================= ENTER CPU-EMU ===============

*       Fault out of DOSEMU code, cs:eip=33:55b19f7e4d5c, cr2=11cf, fault_cnt=1
*       Fault out of DOSEMU code, cs:eip=33:55b19f7e4d5c, cr2=11cf, fault_cnt=1
```

[This article](https://www.arcadiabbs.com/ubuntu-20-04-64-bit-dosemu-setup/) seems related, as debian-specific issue:

```
mmap_min_addr is a kernel tunable that specifies the minimum virtual addresses that a process is allowed to mmap. You can read more about this on the Debian Wiki Pages. You will need to execute the following command as root or DOSEMU will hang when calling Doors from your BBS:

# echo "vm.mmap_min_addr = 0" > /etc/sysctl.d/mmap_min_addr.conf
# /etc/init.d/procps restart
```

However, that fix doesn't work for me on either machine. 🤷 

That said, it seems it's not an Enigma (e.g. Abracadabra) issue, but I wonder if anyone else is having these problems w/ dosemu?

I'm going to give dosemu2 a try next.

**Comment by NuSkooler** [comment]
You might try building from source. Here is the version I'm using: `dosemu-1.4.0.8-180-g35054ba` (on a fully headless machine; if I want to see anything locally I have to forward to a X server)
