### ISSUE TITLE
Where to add AREAFIX password for scanner/tosser?

### ISSUE THREAD

**Issue by robbiew** [NuSkooler/enigma-bbs#306]
I see in `config.hjson` there's a way to set a PKT PASSWORD per ftn network, but where would I add a AREAFIX/FILEFIX password for each? This would then be then used in .`/optutil.js mb AREAFIX xxx` utility?

**Comment by robbiew** [comment]
Ah! I see in /core/optutil/optutil_message_base.js that the syntax is:

`oputil mb areafix CMD1 CMD2 ... ADDR [--password PASS]`

**Comment by NuSkooler** [comment]
Yeah or you can just use your personal mail box as a +op to send a AREAFIX to e.g. "AreaFix @ ADDR" (where ADDR is the FTN-style address)

**Comment by robbiew** [comment]
Awesome. Good to know!
