### ISSUE TITLE
Python string format for text/MCI code alignment?

### ISSUE THREAD

**Issue by robbiew** [NuSkooler/enigma-bbs#308]
I read [in the docs](https://nuskooler.github.io/enigma-bbs/art/mci.html) that Python string format mini language style syntax is available for widths, alignment, number prevision, etc. as well. 

I'm attempting to "align right" using the format specifier ` > ` that forces the field to be right-aligned within the available space. But I'm unclear how/if this is supported?

Here's what I'm trying to align within a prompt:

```
TL1: {
     maxLength: 43
     width: 43
     textOverflow: "..."
     text: |03|24|MC|15|24 » |11|MA
     textStyle: lower
}
```

Is this feature supported in the way I'm looking to use it? Thanks!

**Comment by NuSkooler** [comment]
> “Format specifications” are used within replacement fields contained within a format string

I don't see a field in which you're trying to apply a format to? If you just want a static alignment, just put in spaces.

**Comment by robbiew** [comment]
> > “Format specifications” are used within replacement fields contained within a format string
> 
> I don't see a field in which you're trying to apply a format to? If you just want a static alignment, just put in spaces.

I'd like to right-align the text (Message Conf & Message Area MCI codes), which will vary in length. Just not sure where to apply the python formatting.

**Comment by NuSkooler** [comment]
Ah OK, currently not supported (see TODO here actually: https://github.com/NuSkooler/enigma-bbs/blob/master/core/text_view.js#L195)

For now you can slap down more than one label though, TL1, TL2, ... so on
