### ISSUE TITLE
QWK Offline Mail Support

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#31]
Modile for generating QWK packet for user.

**Comment by NuSkooler** [comment]
Initial QWK support is in for testing. Currently this is only exposed via `oputil.js`, but module(s) will be created & a default menu with the usual options will be implemented.

Please test it out. Here are a couple examples, run with `--help` for more info. Documentation will be added in the near future as well.

Export to `/path/to/` using "XIBALBA.QWK" as a template. That is: "XIBALBA" as the BBS ID. XIBALBA.QWK, XIBALBA.QW1, etc. will be created as necessary (e.g. if there are collisions):

`./oputil.js mb qwk-export /path/to/XIBALBA.QWK`

The same thing, but for a different user, limited area tags, and only after a certain timestamp:
`./oputil.js mb qwk-export --user JoeUser --after 2020-01-01 general,fsx_general /path/to/XIBALBA.QWK`

Dump/view all the messages in a packet to stdout:
`./oputil.js mb qwk-dump /path/to/SOMEPACKET.QWK`

**Comment by NuSkooler** [comment]
The schedule for QWK related feature order is something like:

1. Testing (This phase)
2. A basic menu with download of packet
3. Reply (.REP) support
4. Configuration to the menu (QWKE toggle, format, etc.)
5. QWK-network support (#32)

**Comment by NuSkooler** [comment]
QWK packet export is in - you can play with it on Xibalba. It's been in for a quite some time, then no one talked about it any longer, so I'm not thinking it's very important currently.

**Comment by NuSkooler** [comment]
This has been in for some time.
