### ISSUE TITLE
Override HTTP requests on port 80 to automatically redirect to HTTPS on port 443

### ISSUE THREAD

**Issue by chilledtonic** [NuSkooler/enigma-bbs#310]
Hey,

Not sure if this is implemented and I just haven't seen it in the options, but It'd be nice to enable a 301 redirect so all HTTP calls are redirected to HTTPS automatically for Enigma's Web Server.

External solutions exist, of course, but they involve overriding Enigma to make them work.

**Comment by NuSkooler** [comment]
Not currently implemented no. If you're up to take a stab, the `core/servers/content/web.js` module would just need a option to enable it such as `redirectInsecure` or something and punch in some pre-route work.

**Comment by blackmagic-consult** [comment]
I just ended up using an NGINX setup to route connections to Enigma, which runs on a higher port;

I'd still like to take a stab at this, though, so I'll make a PR when I have it working.
