### ISSUE TITLE
Current datetime being used on %RESCAN of message areas instead of created datetime

### ISSUE THREAD

**Issue by louisnorthmore** [NuSkooler/enigma-bbs#313]
When requesting a rescan of messages from an FTN uplink messages are imported with the current date/time instead of the created date/time

**Environment**
- [X] I am using Node.js v12.x LTS or higher
- [X] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): `v12.18.3`
- Operating system (`uname -a` on *nix systems): `Linux bbs 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux`
- Revision (`git rev-parse --short HEAD`): `a4883f0`

**Expected behavior**
Messages/List messages - Actual date/time when message created originally should be displayed.

**Actual behavior**
Messages/List messages - Todays or imported date/time is displayed.
![image](https://user-images.githubusercontent.com/314418/92278399-0b273480-eeed-11ea-8059-6894d5cebae5.png)

**Steps to reproduce**
Rescan an area from an uplink. Eg: %RESCAN FSX_GEN
When polled and tossed/imported list the messages in the area.

**Comment by louisnorthmore** [comment]
@NuSkooler - I'll take a look at this

**Comment by robbiew** [comment]
Just to confirm, I just did a %RESCAN (moved my board to an rpi), and this was the case--old messages came in with the import date. Had to do a double-take on this one, heh:

![Capture](https://user-images.githubusercontent.com/418170/93263004-fdc64180-f759-11ea-9e4e-6e06b6c53c9b.PNG)

**Comment by NuSkooler** [comment]
@louisnorthmore Have you had a chance to look into this?

When doing a `%RESCAN` we simply ask the remote node to send us packets. When we get them, they are imported as per usual. The `modDateTime` field comes from the individual message headers within the packet.

If you @robbiew send me a few packet file(s) after doing a RESCAN I can debug this a little better.

**Comment by tonytoon** [comment]
I've attached a response to a %RESCAN request.

[0000ffe4.zip](https://github.com/NuSkooler/enigma-bbs/files/5555110/0000ffe4.zip)

**Comment by NuSkooler** [comment]
@deepthaw Thanks I'll have a look

**Comment by NuSkooler** [comment]
Oh man, there were a few bugs here actually. I'm not sure how we've managed to go so long with a couple of these. Just pushed a fix to master that:
* Correct TZUTC/TZUTCINFO offsets
* Doesn't !$@# the timestamp when inserting to the DB
* Corrects a byte offset when parsing packet files (also due to timestamp) that could prevent other messages in the packet from being imported properly or at all
