### ISSUE TITLE
Errors: unmet deps w/ install.sh on fresh Debian 10 (WSL2)

### ISSUE THREAD

**Issue by robbiew** [NuSkooler/enigma-bbs#314]
Running install.sh on clean/new Debian 10 server (running in a WSL2 VM), there are unmet dependencies that cause the install script to error/abort:

- curl
- node-gyp
- git

Errors where obvious of course, but thought I'd flag. Once installed, install completes!

**Environment**
- [x] I am using Node.js v12.x LTS or higher
- [x] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): v12.18.3
- Operating system (`uname -a` on *nix systems): 4.19.104-microsoft-standard, Debian 10 (Default)
- Revision (`git rev-parse --short HEAD`): f3d67ab

**Comment by NuSkooler** [comment]
The `install.sh` instructions start with `curl ...`, so I'm assuming you `wget`'d it down or something?

`node-gyp` should come down with the installation of Node.js and NVM. `git` should probably be marked for sure though.

**Comment by NuSkooler** [comment]
@robbiew can this be closed?
