### ISSUE TITLE
Add a way to programmatically send messages

### ISSUE THREAD

**Issue by louisnorthmore** [NuSkooler/enigma-bbs#315]
It would be useful for a way to programmatically send messages/file output.
Perhaps using oputil? I notice it already has this capability of sending AreaFix messages. 
This code could be tweaked slightly perhaps.

**Comment by NuSkooler** [comment]
@louisnorthmore Can you explain more of what you're wanting to do here? You can already programmatically send messages -- as you point out, that's what oputil does in some cases. You can also look at the [latest files mod](https://github.com/NuSkooler/enigma-bbs-latest_files_announce_evt) or [the message post mod](https://l33t.codes/outgoing/ACD/ACD-MP4E.ZIP) both of which generate mail and send it out.

**Comment by louisnorthmore** [comment]
@NuSkooler Exactly that! (Latest files) Thanks for pointing me in the right direction. Wasn't aware of those mods. I wonder if there's a suitable place in the docs to mention that functionality? Thanks so much!

**Comment by NuSkooler** [comment]
@louisnorthmore Documentation is probably quite lacking in general, but a severe gap is certainly developer/modding. I also really need to get around to at least documenting the `MenuModule` lifecycle.
