### ISSUE TITLE
Error on qwk export with oputil

### ISSUE THREAD

**Issue by robbiew** [NuSkooler/enigma-bbs#316]
**Short problem description**

Using oputil to export qwk packet results in an error...

This command:
`./oputil.js mb qwk-export /home/robbiew/test.qwk`

result:

```
/home/robbiew/enigma-bbs/core/ftn_util.js:381
    const ident = chrs.split(' ')[0].toUpperCase();
                       ^

TypeError: chrs.split is not a function
    at getEncodingFromCharacterSetIdentifier (/home/robbiew/enigma-bbs/core/ftn_util.js:381:24)
    at QWKPacketWriter._getEncoding (/home/robbiew/enigma-bbs/core/qwk_mail_packet.js:1093:24)
    at QWKPacketWriter.appendMessage (/home/robbiew/enigma-bbs/core/qwk_mail_packet.js:1029:31)
    at /home/robbiew/enigma-bbs/core/oputil/oputil_message_base.js:600:40
    at /home/robbiew/enigma-bbs/core/message.js:654:24
    at /home/robbiew/enigma-bbs/node_modules/async/dist/async.js:2955:19
    at wrapper (/home/robbiew/enigma-bbs/node_modules/async/dist/async.js:268:20)
    at replenish (/home/robbiew/enigma-bbs/node_modules/async/dist/async.js:435:29)
    at iterateeCallback (/home/robbiew/enigma-bbs/node_modules/async/dist/async.js:424:21)
    at /home/robbiew/enigma-bbs/node_modules/async/dist/async.js:321:20

```

Here's my setup in config.hjson:

```
 messageNetworks: {
        qwk: {
             areas: {
                general: {          // local ENiGMA½ area tag
                    conference: 1   // conference number to map to
                }
                fsx_gen: {          
                    conference: 2  
                }
                fsx_mys: {          
                    conference: 3  
                }
                fsx_mag: {          
                    conference: 4  
                }
                fsx_bbs: {          
                    conference: 5  
                }
                fsx_eng: {          
                    conference: 6  
                }
                fsx_ham: {          
                    conference: 7  
                }
                fsx_cry: {          
                    conference: 8  
                }
                fsx_net: {          
                    conference: 9  
                }
                fsx_bot: {          
                    conference: 10  
                }
                fsx_dat: {          
                    conference: 11  
                }
            }
        }
```

**Environment**
- [x] I am using Node.js v12.x LTS or higher
- [x] `npm install` or `yarn` reports success
- Actual Node.js version (`node --version`): 12.18.3
- Operating system (`uname -a` on *nix systems): Linux 4.15.0-115-generic #116-Ubuntu SMP Wed Aug 26 14:04:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Revision (`git rev-parse --short HEAD`): git rev-parse --short HEAD

**Expected behavior**

**Actual behavior**

**Steps to reproduce**

**Comment by NuSkooler** [comment]
@robbiew From the stack we can see that we extracted a `CHRS` kludge then attempted convert that to something more standard:
```
encoding = getEncodingFromCharacterSetIdentifier(encoding);
```

Then blew up with `chrs.split()` not being a function. `String.split()` is absolutely a function and we just checked that `encoding` as defined.

If you don't mind, can you put in a extra log in your `ftn_util.js` at the top of the `getEncodingFromCharacterSetIdentifier` function:
`console.log(chrs)`

Then run again and let's find out what's going on here.

**Comment by robbiew** [comment]
Sure -- here's the full output with the console.log added:

https://gist.github.com/robbiew/4970df355053530ff382b24e51616f0f

**Comment by NuSkooler** [comment]
@robbiew  Perfect thank you! I'll get a fix in for this soon!

**Comment by NuSkooler** [comment]
Should be good now! We'll try to pick the best possible encoding from 1:N CHRS kludges

**Comment by robbiew** [comment]
Export successful, thank you!
