### ISSUE TITLE
Tall Ansi Art Menu Alignment Problem

### ISSUE THREAD

**Issue by un-fuf-a-doo** [NuSkooler/enigma-bbs#320]
**Describe the Bug**
We actually employed (paid for) the artistic services of Luciano to design the theme for our BBS.  Using Moebius, I carefully chopped up the menus and carefully aligned everything so that it would match the original theme.hjson file.  Then came the welcome screen we chose to run our custom MATRIX.ANS as a scrolling welcome screen ending with the menu for choosing Login, Apply, Logoff options.  The resulting MATRIX.ANS file is 80 x 77 with a menu box at the bottom, and the mci code %VM1 placed so that the menu items would be displayed properly.  What actually happens, the screen scrolls to the bottom then suddenly jerks back up several rows.  When scrolling back down, the location where the mci code was placed is blank, even though the functionality is there (I can hear the clicking and hitting carriage return selects the selected option).

**To Reproduce**
I'm guessing load a tall ansi file as your matrix and it should reproduce.  Unless we are missing a configuration option somewhere, I think this is a bug.

**Expected Behavior**
Per how dialup BBS's originally worked in the 90's, a tall ansi art screen should scroll to the end, and then render mci codes where they are placed on in the art.

**Actual Behavior**
As detailed in the initial description, the screen scrolls to the bottom, then jerks back up several rows and does not render the mci code in the correct location. The functionality still works, hitting carriage return does select the selected option.

**Screenshots**
None available.

**Environment**
* [ ] I am using Node.js v12.x LTS or higher
* [X] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): `v10.22.1`
* Operating system (`uname -a` on *nix systems): `Linux dev.unfufadoo.net 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* Revision (`git rev-parse --short HEAD`): `a3ed115`

**Comment by NuSkooler** [comment]
This is actually one of the first issues entered - #5! When the art system is re-worked with #222, this and a number of other issues should be resolved. That ticket is probably sometime after the WFC work is completed which I hope to focus more on after Halloween.

For now you'll have to have a separate scroller and matrix unfortunately.

**Comment by un-fuf-a-doo** [comment]
LOL I didn't go back far enough in my search.  Thanks for replying and for the information.  We will just split things up for now. Still learning everything, but I hope to have our bbs ready soon. I can't tell you in words how awesome Enigma is and the nostalgia it has generated. My business partner and friend flipped out and didn't hesitate hiring Luciano for the art.

I'll close this one since you don't need the reminder.

**Comment by NuSkooler** [comment]
@un-fuf-a-doo Thanks for the kind words! Excited to see what you come up with!
