### ISSUE TITLE
Documentation Issue

### ISSUE THREAD

**Issue by Beanzilla** [NuSkooler/enigma-bbs#321]
**Describe the Bug**
There appears to be a issue with the markdown table in the `Defaults` section in `Themes`.

**To Reproduce**
1. Goto [https://nuskooler.github.io/enigma-bbs/art/themes.html](https://nuskooler.github.io/enigma-bbs/art/themes.html).
2. Scroll down to `Defaults`.
3. See broken Markdown table.

**Expected Behavior**
Obviously the expected behavior is a proper Markdown table...

**Actual Behavior**
Currently it's very difficult to read what all is there.

**Screenshots**
![image](https://user-images.githubusercontent.com/20930999/98162517-7d95a000-1eaf-11eb-85ff-5ad0a0b80849.png)

**Environment**
I am using Firefox to view the [Docs](https://nuskooler.github.io/enigma-bbs/)

**Comment by NuSkooler** [comment]
Should be good to go now! Thanks for the report 👍
