### ISSUE TITLE
Enigma crashes trying to write to a node when that node disconnected

### ISSUE THREAD

**Issue by Beanzilla** [NuSkooler/enigma-bbs#324]
**Describe the Bug**
While in some doors the game still tries to send stuff to the user... but what if the user has disconnected? :boom: Enigma crashes with error.

**To Reproduce**
If you have Apams For Honour, simply run that and just as you hit a key also disconnect. (Though it seems like dosdoors do not seem to have this effect)

**Expected Behavior**
I expect Enigma to still run, just understand that the user is not there so close the door.

**Actual Behavior**
:boom: an error is thrown from event.js

**Screenshots**
With loggging set to trace
```
 events.js:291
       throw er; // Unhandled 'error' event
       ^
 
 Error [ERR_STREAM_WRITE_AFTER_END]: write after end
     at writeAfterEnd (_stream_writable.js:266:14)
     at Channel.Writable.write (_stream_writable.js:315:5)
     at ClientTerminal.rawWrite (/home/enigma/bbs/core/client_term.js:164:21)
     at /home/enigma/bbs/core/abracadabra.js:194:30
     at PipeSocket.<anonymous> (/home/enigma/bbs/core/door.js:126:20)
     at Object.onceWrapper (events.js:421:26)
     at PipeSocket.emit (events.js:326:22)
     at UnixTerminal.Terminal.emit (/home/enigma/node_modules/node-pty/lib/terminal.js:134:34)
     at onexit (/home/enigma/node_modules/node-pty/lib/unixTerminal.js:90:19)
 Emitted 'error' event on Channel instance at:
     at errorOrDestroy (internal/streams/destroy.js:108:12)
     at writeAfterEnd (_stream_writable.js:268:3)
     at Channel.Writable.write (_stream_writable.js:315:5)
     [... lines matching original stack trace ...]
     at onexit (/home/enigma/node_modules/node-pty/lib/unixTerminal.js:90:19) {
     code: 'ERR_STREAM_WRITE_AFTER_END'
 }
```

**Environment**
* [x] I am using Node.js v12.x LTS or higher
* [x] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): v12.19.0
* Operating system (`uname -a` on *nix systems): Linux c7339f9a79cd 4.15.0-123-generic #126-Ubuntu SMP Wed Oct 21 09:40:11 UTC 2020 x86_64 GNU/Linux
* Revision (`git rev-parse --short HEAD`): Unkown, I know it's Enigma 0.0.12-beta
* Any additional relevant information about your setup: Yes, this is a docker container... but this bug is about doors exiting and breaking the system.

**Comment by NuSkooler** [comment]
If you can, please try this patch and report back:
```
diff --git a/core/client_term.js b/core/client_term.js
index f537c35..e961394 100644
--- a/core/client_term.js
+++ b/core/client_term.js
@@ -160,7 +160,7 @@ ClientTerminal.prototype.write = function(s, convertLineFeeds, cb) {
 };
 
 ClientTerminal.prototype.rawWrite = function(s, cb) {
-    if(this.output) {
+    if(this.output && this.output.writable) {
         this.output.write(s, err => {
             if(cb) {
                 return cb(err);
```

**Comment by Beanzilla** [comment]
Looks like this works, thank you.

**Comment by NuSkooler** [comment]
@Beanzilla  Great, just pushed that patch to master. Thanks!
