### ISSUE TITLE
Enhanced FILES.BBS

### ISSUE THREAD

**Issue by tonytoon** [NuSkooler/enigma-bbs#325]
I have downloaded the entire collection of demoscene music from hornet.org, as well as many other collections. I'd like a way to import and tag all of them easily with the information provided. Many pieces of info that can be gleaned from there (rating, year) exist within the ENiGMA file system, but I can find no way to import them automatically.

It would be nice to have an enhanced files.bbs format which can bring in additional fields. Perhaps a simple .csv with predefined headers? This could work for importing any extremely large collections of files.

**Comment by NuSkooler** [comment]
@tonytoon Did you find what you were looking for?

`oputil.js` supports `FILES.BBS` in various formats along with some other common descriptors. FILE_ID.DIZ/similar are always looked for in archives, processors can read metadata from archives/etc. as well. 

It should be easy to add processors for .mod, .s3m, so on. if that is what you're after. It's a pluggable system -- just look how some of the others work. Would love PRs!

**Comment by tonytoon** [comment]
> @tonytoon Did you find what you were looking for?
> 
> `oputil.js` supports `FILES.BBS` in various formats along with some other common descriptors. FILE_ID.DIZ/similar are always looked for in archives, processors can read metadata from archives/etc. as well.
> 
> It should be easy to add processors for .mod, .s3m, so on. if that is what you're after. It's a pluggable system -- just look how some of the others work. Would love PRs!

I did - I explored into the files.bbs options and got all the files imported. I did some massaging of data in notepad++ >> excel >> notepad++ to get them in the bbs very nicely.

It'd still be nice to have a custom files.bbs that can define fields like year, rating, etc. but I don't feel it's critical.
