### ISSUE TITLE
File Search searches long_desc even when not used.

### ISSUE THREAD

**Issue by deepthaw** [NuSkooler/enigma-bbs#326]
I imported 9,000 files using a FILES.BBS file. When I do searches, it appears to be matching based based on the long_desc brought in from the file_id.diz even though it does not show in the bbs. It's matching the short_desc just fine too.

This results in files showing up in results where you can't figure out the reason at first.

**Comment by NuSkooler** [comment]
Short descriptions (short_desc) are FILE_ID.DIZ/equiv and long descriptions (long_desc) are automatically picked up from README, README.1ST, *.NFO, and other common formats. They are both scanned by the FTS by design.

You can see long desc's in the details view when in the file browser.

**Comment by tonytoon** [comment]
Okay - I'm seeing it now. It displays the short description in the main window, and I didn't go far enough into the details to see the .NFO/Readme section. User error.

If I rerun to import the file_id.diz, will it overwrite the short description from files.bbs? I'd like to have both appear on the same screen.

**Comment by NuSkooler** [comment]
Description files like `FILES.BBS` and in-archive `FILE_ID.DIZ` serve the same purpose, so you won't get both in a short description no.

**Comment by NuSkooler** [comment]
@deepthaw I'm not sure if this is of interest, but you can also go the other way around. E.g. I use this on a weekly maintenance to keep a updated `DESCRIPT.ION` files generated: https://github.com/NuSkooler/enigma-bbs/blob/master/core/file_base_list_export.js#L253

Basically just slap it in a scheduled task.
