### ISSUE TITLE
IRC Channel

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#33]
It may be worthwhile to have/document an IRC channel for BBS support, either via freenode, irc.synchro.net or efnet.

**Comment by NuSkooler** [comment]
I completely agree. I will get a channel home shortly!

**Comment by NuSkooler** [comment]
I have set up #enigma-bbs on FreeNode. I haven't op'd a channel in a long time, so I'll leave this open until I'm happy that FreeNode is where it should live. For now, I don't see any reason why not.

**Comment by NuSkooler** [comment]
Closing, FreeNode seems like a good home.
