### ISSUE TITLE
oputil cannot remove user from group

### ISSUE THREAD

**Issue by deepthaw** [NuSkooler/enigma-bbs#331]
I have a "new" group on my bbs to which users are added. My intention is to remove them from this group after reviewing their initial message to sysop.

oputil reports: Object does not exist: No matching username
when running: ./oputil.js user group newman -new
if I run: ./oputil.js user group newman +new
it appears to work fine, and outputs: User groups modified

I have also tested with the "topmen" group, which reports the same errors.

![image](https://user-images.githubusercontent.com/1053938/100526758-941ed680-3191-11eb-847b-31af803c4e77.png)

**Comment by deepthaw** [comment]
Forgot to indicate which OS I am on:
Using bash as my shell.

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by NuSkooler** [comment]
@deepthaw Try putting single quotes around `-new`: `'-new'`

**Comment by deepthaw** [comment]
> @deepthaw Try putting single quotes around `-new`: `'-new'`

Same response: Object does not exist: No matching username

**Comment by NuSkooler** [comment]
The problem is the way "-" is handled / requires escaping dependent on the shell. Updated to allow the `~` character:
```
./oputil.js user group ~somegroup
```
