### ISSUE TITLE
Removed files not fully deleted from sqlite DB

### ISSUE THREAD

**Issue by deepthaw** [NuSkooler/enigma-bbs#333]
Removing files from system using ./oputil.js does not appear to fully remove all the data in the relevant tables. This results in files that are added later having potentially incorrect data due to linking to the previous files.

Quickest way to recreate: Import some files with given tags. Remove the files from the system, then import them with different tags. The old tags will still be on the freshly imported files.

**Comment by deepthaw** [comment]
Can verify that at least the file_hash_tag table is not getting updated when files are removed. Ran "sqlite3 file.sqlite3" and SELECT * FROM file_hash_tag has multiple entries pointing towards files that no longer exist.

**Comment by NuSkooler** [comment]
Fix + notes on manual updates merged in
