### ISSUE TITLE
VTX client html sample file 404

### ISSUE THREAD

**Issue by BrandonG777** [NuSkooler/enigma-bbs#345]
**Describe the Bug**
on the page https://nuskooler.github.io/enigma-bbs/servers/websocket.html, step 3 references https://nuskooler.github.io/misc/vtx/vtx.html which is 404.

**To Reproduce**
goto https://nuskooler.github.io/misc/vtx/vtx.html 

**Expected Behavior**
download vtx.html sample

**Actual Behavior**
404

**Environment**
any browser

**Comment by NuSkooler** [comment]
Thanks for the report - link has been updated.
