### ISSUE TITLE
Cannot run ./oputil.js config new on brand new installation

### ISSUE THREAD

**Issue by TryingEnigma** [NuSkooler/enigma-bbs#346]
Hello,

I am excited to start using Enigma 1/2.  After fighting my way through the usual dependency issues, I was able to install successfully.  Unfortunately when I run "./oputil.js config new" from the Enigma directory, as instructed, I get the following error.  Any advice is welcome.

guy@Computer:~/enigma-bbs$ ./oputil.js config new
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module '/home/guy/enigma-bbs/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node'
Require stack:
- /home/guy/enigma-bbs/node_modules/sqlite3/lib/sqlite3-binding.js
- /home/guy/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js
- /home/guy/enigma-bbs/core/database.js
- /home/guy/enigma-bbs/core/oputil/oputil_common.js
- /home/guy/enigma-bbs/core/oputil/oputil_main.js
- /home/guy/enigma-bbs/oputil.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/guy/enigma-bbs/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/guy/enigma-bbs/node_modules/sqlite3/lib/sqlite3-binding.js',
    '/home/guy/enigma-bbs/node_modules/sqlite3/lib/sqlite3.js',
    '/home/guy/enigma-bbs/core/database.js',
    '/home/guy/enigma-bbs/core/oputil/oputil_common.js',
    '/home/guy/enigma-bbs/core/oputil/oputil_main.js',
    '/home/guy/enigma-bbs/oputil.js'
  ]
}

**Comment by NuSkooler** [comment]
Looks like you're still having issues with dependency issues:
```'/home/guy/enigma-bbs/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node'```

This ticket is lacking in information - please supply Node version, if you're using Yarn, NPM, etc. If you're using Yarn, you might try `yarn` in the enigma directory. If NPM, try `npm install`

**Comment by TryingEnigma** [comment]
I originally installed NVM using the latest script on the link you provided for the creationis/nvm page under your Manual Installation page.  I then followed the provided commands on their site, successfully.  

Trying to repeat "nvm install 12" now outputs:

**v12.20.1 is already installed.
Now using node v12.20.1 (npm v6.14.10)**

Entering "npm install" from the /enigma-bbs directory outputs: 

**audited 409 packages in 10.13s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities**

However, re-running "./oputil.js config new" in the enigma-bbs directory still outputs the same lines as in my original message above.

For what it's worth, the ~/enigma-bbs/node_modules/sqlite3/lib/ directory has no "binding" subdirectory and only the following :

**index.js  sqlite3-binding.js  sqlite3.js  trace.js**

**Comment by NuSkooler** [comment]
Try this:
```
rm -rf node_modules
npm install
```

Look for any errors

**Comment by TryingEnigma** [comment]
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.

> sqlite3@4.2.0 install /home/guy/enigma-bbs/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
[sqlite3] Success: "/home/guy/enigma-bbs/node_modules/sqlite3/lib/binding/node-v72-linux-x64/node_sqlite3.node" is installed via remote
npm notice created a lockfile as package-lock.json. You should commit this file.
added 194 packages from 654 contributors and audited 195 packages in 31.614s

2 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by TryingEnigma** [comment]
i force fixed the vulnerability, and updated mkdirp...

and can now successfully access a configuration.  thank you for your help and let me know if you want the outputs for your file.

**Comment by NuSkooler** [comment]
Awesome! Enjoy!
