### ISSUE TITLE
[D]ownload message from message base calls out permission denied on directory

### ISSUE THREAD

**Issue by WestwoodBBS** [NuSkooler/enigma-bbs#347]
So I've just finished setting up my BBS for the most part. I'm struggling in one area.
If I'm in fsxNet message area and attempt to download a message, the telnet session freezes any further user input and eventually times out and drops connection.  In the event log, the following is printed:

[2021-01-28T23:46:13.116Z] TRACE: ENiGMA½ BBS/3196 on bulletin-board-system: Form submit (nodeId=1, sessionId=XEUXbXeJDmY, username=Nuke)
    formData: {
      "id": 4,
      "submitId": 1,
      "value": {
        "1": 4
      },
      "key": {
        "seq": "\r",
        "name": "return",
        "ctrl": false,
        "meta": false,
        "shift": false
      }
    }
[2021-01-28T23:46:13.116Z] TRACE: ENiGMA½ BBS/3196 on bulletin-board-system: Action match (nodeId=1, sessionId=XEUXbXeJDmY, username=Nuke)
    actionBlock: {
      "value": {
        "1": 4
      },
      "action": "@method:addToDownloadQueue"
    }
[2021-01-28T23:46:13.119Z]  WARN: ENiGMA½ BBS/3196 on bulletin-board-system: Error during handleAction() (nodeId=1, sessionId=XEUXbXeJDmY, username=Nuke, err.code=EACCES)
    Error: EACCES: permission denied, mkdir '/mnt/disks/westwoodbbs_extdrive'

Where is EACCESS getting set at? I have my filebase pointing to this area but one directory further than one is shown above. I've looked everywhere and I can't find it.  Also, the area being denied is tied to the user account - but that directory exists - so I'm not sure why MKDIR is being invoked??

R/
Nuke

**Comment by NuSkooler** [comment]
When downloading messages, a file will be placed in the "system temp download area". That is. This is `$fileBaseRoot/sys_temp_download`. mkdirs is called to ensure it exists before a file is placed there (via the `areaStoragePrefix` member inf your config).

Can you inspect/post the output of the following command?
```
./oputil.js fb info system_temporary_download
```

For reference here is mine:
```
./oputil.js fb info system_temporary_download                                                                                   
areaTag: system_temporary_download
name: System Temporary Downloads
desc: Temporary downloadables
storageTag: sys_temp_download => /home/enigma/file_base/sys_temp_download
```

>  I have my filebase pointing to this area but one directory further than one is shown above

I'm not exactly sure what you mean by this?

**Comment by WestwoodBBS** [comment]
Thanks. it is responding:
areaTag: system_temporary_download
name: System Temporary Downloads
desc: Temporary downloadables
storageTag: sys_temp_download => /mnt/disks/westwoodbbs_extdrive/file_area_public/sys_temp_download

What I was saying at the bottom is that I had my areaStoragePrefix for fileBase in config.hjson as what is listed above.
I was questioning the MKDIR permission error only calling out /mnt/disks/westwoodbbs_extdrive instead of /mnt/disks/westwoodbbs_extdrive/file_area_public.  So sounds like I just need to change areaStoragePrefix.

**Comment by WestwoodBBS** [comment]
All good now. :+1:

**Comment by NuSkooler** [comment]
@WestwoodBBS Did you just need to set the `areaStoragePrefix` or was it pointing to the wrong place by default? I want to make sure there is nothing that needs to change in enig. Thanks!

**Comment by WestwoodBBS** [comment]
All Good! That and a fat finger typo...

________________________________
