### ISSUE TITLE
Changes not properly merged when config files are re-cached

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#35]
**Problem**
When configuration files (`menu.hjson`, `theme.hjson`, ...) are re-cached due to an external modification, changes are not properly reflected back into the "live" view of the data. The system must be restarted for them to apply.

**Expected**
Changes should update in with a restart

**Comment by tracker1** [comment]
For reference:

> **fs.watch(filename[, options][, listener])**
> https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener

Though, it doesn't work consistently, you may also want to do 5-15 second polling for essential configurations, but at least with `fs.watch` you don't have to poll too frequently.

**Comment by NuSkooler** [comment]
@tracker1 ENiGMA½ is already using [Gaze](https://github.com/shama/gaze) to watch and re-cache various files (Works around some of the `fs.watch` limitation/bugs on various platforms). There is a bug(s) in the logic at re-cache time.

**Comment by NuSkooler** [comment]
This has been completely re-written and pushed to the `0.0.9-alpha` branch around https://github.com/NuSkooler/enigma-bbs/commit/4aab8224eda69431c48be37ee5714fd296d260a5 ish.

Closing this one. Any bugs with the implementation can be logged separately.

**Comment by NuSkooler** [comment]
Note: Gaze was replaced with [sane](https://github.com/amasad/sane)
