### ISSUE TITLE
Feature: MailU integration

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#352]
[MailU](https://mailu.io/1.7/) is an email server in a box solution.

I was thinking it might be an idea to generate a user for a given domain configured in MailU matching a user account created in Enigma.  Will likely require the use of Puppeteer (or similar) as the admin interface is web based, but there doesn't appear to be a clear API... otherwise can reverse-engineer the authentication and creation/update of an account and corresponding passphrase.

The other portion for integration would be to use the mail server's SMTP and IMAP for inbound/outbound mail, and sending "local"  mail to that user on the mail server directly.

This does require the use of Docker for the mail server setup, and would be rather narrow, but could be useful to jump-start pretty decent (web)mail support with somewhat minimal effort.  On the down side, integrating with the web server for HTTPS and SFTP using the same cert might take some effort in order to host on the same server.  But having them on different servers, and/or web proxy might by another option.

Thoughts?

Some details on mailu configuration... would probably just want to support the use of a docker-compose file for mailu components and enigma-bbs.

https://mailu.io/1.7/reverse.html

**Comment by NuSkooler** [comment]
@tracker1 I'm not sure what you're trying to solve here?

ENiGMA already uses node-mailer which supports many mail APIs/protocols.

**Comment by tracker1** [comment]
@NuSkooler I want for BBS users to be able to receive internet email on the BBS.

**Comment by NuSkooler** [comment]
@tracker1 Are you even using ENiGMA? node-mailer is already in. You'd need to do some plumbing to allow Internet e-mail <> users. This would be hooked up similar to NetMail which is also considered "external" to the system and mapped between.

**Comment by tracker1** [comment]
You're right, it's probably not even really needed... in my head was wanting to fast path some feature parity with SynchroNet, but realistically, hosted account emails isn't really a killer feature...  I may take some time to look at and maybe enhance the nntp support.

I've setup enigma on my local/test environment a couple times, but haven't gotten that far.. main bbs (roughneckbbs.com) still running SynchroNet.

**Comment by NuSkooler** [comment]
Again if you really want that, the basic email stuff is already there. A module to map the email<>user is what is missing.
