### ISSUE TITLE
Problems when using with Striketerm / Novaterm on C64

### ISSUE THREAD

**Issue by sreuter** [NuSkooler/enigma-bbs#365]
**Describe the Bug**

I've setup my Enigma BBS and it works awesome with SyncTerm.

Unfortunately, whenever I try to dial in via SyncTerm (in ANSI mode) on my C64, it only renders the first screen, but then does not continue to the login. I can't press enter or anything else. It's just frozen. I've tried logging into another Enigma BBS, but with the same result.

**To Reproduce**
Any relevant steps to reproduce the behavior:

Try using SyncTerm or Novaterm 9.6 on a C64, set to ANSI mode and try to login into any Enigma BBS.

**Expected Behavior**

Session should not hang after initial screen/graphic rendered.

**Actual Behavior**

It gets stuck

**Screenshots**

**Environment**
* [x] I am using Node.js v12.x LTS or higher
* [x] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): v12.22.6 
* Operating system (`uname -a` on *nix systems): Linux cybney 5.4.0-80-generic #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
* Revision (`git rev-parse --short HEAD`): 1ffbf5b
* Any additional relevant information about your setup: I'm using a Wi232 Modem in UP9600 mode.

**Comment by NuSkooler** [comment]
@sreuter it sounds like you're having the issue with Cursor Position Reports not being supported by your client. This is a known issue that I plan on tackling hopefully in the near-ish future. You can validate by using another menu in front/in place of that doesn't use MCI codes -- if it works, that's what what you're looking at.

**Comment by NuSkooler** [comment]
See https://github.com/NuSkooler/enigma-bbs/issues/222

**Comment by NuSkooler** [comment]
@sreuter This should be working now!
