### ISSUE TITLE
Files base

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#37]
**Files Base**
Meta bug for files base/area.

**Features**
Not limited to:
- Standard/expected features
- FILE_ID.DIZ & DESC.SDI support
- TBD protocol(s)
- Additional modern features such as torrent & direct downloads when servers become available
  - Short URLs with _n_ expiration time for direct downloads and/or web based auth/IP detection
- Upload processing
  - Virus scanners
  - Add NFO
- ACS controlled access
- Integration with message area such as "new files" posts

**Comment by tracker1** [comment]
I know you're probably going to wire up `SFTP` support via `ssh2`, but in case you want to do plain ftp support...

> node-ftpd
> https://github.com/sstur/nodeftpd

**Comment by NuSkooler** [comment]
Should be written in such a way to easily integration with external message networks such as FTN that support attachments.

**Comment by NuSkooler** [comment]
Starting to look into this a bit more. I'm thinking of a different than normal (as in most BBSs) file base approach & more like a lot of popular private torrent tracker interfaces such as Gazelle.

Some ramblings that may or may not make sense:
* Still have areas, but probably no conferences
* Listings are ALL in the selected area(s)
* Configurable filters (note: saved to user profile):
 * Search terms (free form FTS)
 * Tags (hashtags)
 * Areas
 * Order By: (stored as metadata values)
  * Time Added
  * Downloads
  * Size
  * Year (attempt to extract from .DIZ, .NFO, etc.)
 * Order: Ascending or Descending
* Ability to view tags (list them)
* Ability to set tags on upload/import/etc.

Protocols will initially support externals such as `sexyz` or `rz`. Additional servers HTTP (temp URLs), Torrent, and so on.

Would like full screen .NFO viewer and scrollable FILE_ID.DIZ/DESC.SDI viewer.

Thoughts / Comments / Rants?

**Comment by davestephens** [comment]
All sounds like good stuff! 

Couple of other things/rambles that spring to mind:
- ANSI support from both file_id.diz/file_id.ans 
- Ability to poke into zips, and view stuff in them (think art packs). Would need some kind of whitelist on extensions that are viewable
- New files view (similar to new messages, ie shows you "unread" files)

Maybe a bit too much to ask for beta1, but what about indexing of files (the names, not content) in archives when files are uploaded, and the ability to search for those files?

Agree re. conferences, I don't think they are necessary. When using Other BBS Software(TM) I found myself sticking areas all into one parent conference. 

Will add more if I think of it...

**Comment by NuSkooler** [comment]
@davestephens As for the index, that's along the lines of what I'm thinking for free form search: Scan within archives and build FTS for: file names, .NFO, .DIZ, and other (configurable) text files.

A pure filename/wildcard search may still make sense for filters too, e.g. `ACD-*`

**Comment by NuSkooler** [comment]
File Bases have been implemented and pushed to master. _Most_ of what is described in this thread is implemented at this point as well.

Features described here that are missing need their own issues opened (I know about many of them, but if something is important to you that isn't yet implemented please open a ticket)
