### ISSUE TITLE
Documentation not showing correctly on full_menu_view.md

### ISSUE THREAD

**Issue by cognitivegears** [NuSkooler/enigma-bbs#380]
**Describe the Bug**
I apologize, it looks like post-merge of PR #379 there is a small problem with the documentation. When expanding the collapsed "Configuration fragment (expand to view)" fragments, it looks like jekyl is failing to see the code section markdown - probably it doesn't support that within an HTML tag. I've used jekyll myself, unfortunately I couldn't test it locally however because of version compatibility problems. Frustratingly, it looks like it only happens with jekyll, it appears correctly when viewing the markdown from the code base. I'll work on a solution and post a new PR shortly.

**Comment by cognitivegears** [comment]
Created a pull request as #383

**Comment by NuSkooler** [comment]
Merged in, thank you!
