### ISSUE TITLE
automated build via docker for nightly testing

### ISSUE THREAD

**Issue by abutbul** [NuSkooler/enigma-bbs#387]
**Is your feature request related to a problem? Please describe.**
not related to a problem but rather to a staleness which often creeps up on projects. this should give at least some observations for the code state and build health

**Describe the solution you'd like**
integrate with dockerhub's opensource thingy and have nightly builds (and even as part of PRs to make sure users are always able to spin up enigma for prod or testing

**Describe alternatives you've considered**
i'm ok doing this for myself but everyone will benefit

**Additional context**
willing to assist in process.
<3

**Comment by NuSkooler** [comment]
Pushes to main should already be triggering this, though something I broken in the last few days I believe. @davestephens any insight?

**Comment by abutbul** [comment]
latest image pushed to dhub is 3 months old https://hub.docker.com/r/enigmabbs/enigma-bbs/tags
if we have a nightly, might as well tag and make it available

**Comment by NuSkooler** [comment]
This has been resolved.
