### ISSUE TITLE
mrc module private msg only transfers one word.

### ISSUE THREAD

**Issue by abutbul** [NuSkooler/enigma-bbs#388]
**Describe the Bug**
in MRC /pm nick messageword1 messgeword2 will only pass the first messageword1

**To Reproduce**
MRC-> /pm someone messageword1 messageword2

**Expected Behavior**
message should be transferred to other party - verbose in its whole to both A+B

**Actual Behavior**
one word is being transferred 

using latest docker
line 425 in mrc.js
` const cmd = message.split(' ');`

i think it needs to just split the first spacebar. i tried a few things but keep breaking other stuff (new to node-js - need to set up an env for quick testing of these things would appreciate a direction on how to set up (either windows or linux)

**Comment by christiansacks** [comment]
I think I just fixed this, I submitted a pull request; https://github.com/NuSkooler/enigma-bbs/pull/391

**Comment by NuSkooler** [comment]
Resolved w/ #391
