### ISSUE TITLE
Update ssh2 to 1.6.0+

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#399]
Update `ssh2` to version 1.6.0 or higher. Security + improved speeds. 

See https://github.com/mscdex/ssh2/issues/935

**Comment by NuSkooler** [comment]
Should be finishing this one up soon.

There seems to be a off-by-one display error with NetRunner: A wildly incorrect value is sent for term height over SSH & NR does not support our ESC seq size query hack. If anyone has ideas...

**Comment by NuSkooler** [comment]
There seems to be much bigger issue with NetRunner the updated SSH2: NR freezes if you aren't constantly giving it input.

**Comment by cognitivegears** [comment]
Note - I've updated ssh2 with #515. As far as formatting on Netrunner, I think that's probably covered in some of the recent PRs. I haven't seen the hang on Netrunner, but I'll do some more testing on this.
