### ISSUE TITLE
ES6/7 support

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#40]
May want to consider the use of [babel](http://babeljs.io/) with [gulp](http://gulpjs.com/) so that you can use ES6/7 features in the codebase.

It will mean a build step for changes, but could simply check in the built version in npm, and have the source in `core-src` building to `./bbs.js` (not checked into github) or use `babel-node` as an `npm start-dev` script that will run directly against the source.

**Comment by NuSkooler** [comment]
Node.js (Remember, this does not run in the browser so Browser support is irrelevant) has ES6 features now. See https://nodejs.org/en/docs/es6/

With runtime flags passed to `node`, one can achieve even more.

The current thought process is to start using some of the ES6 features available immediately.

**Comment by tracker1** [comment]
Understandable... just suggesting mainly because async/await support is pretty nice in terms of writing code as such.  also, rest parameters are/were behind a feature flag iirc

**Comment by NuSkooler** [comment]
I will likely be bumping Node.js version requirements to 4.2.x or higher. After such, various ES6 features can be used in thee code much easier.

**Comment by NuSkooler** [comment]
See #46

**Comment by tracker1** [comment]
Pity, destructuring assignment isn't supported yet.. :-(  though, iirc arrow functions are.

**Comment by NuSkooler** [comment]
New development is using [ES6](https://nodejs.org/en/docs/es6/) functionality available in Node 4.2.x (See #46) ES7 functionality will have to come later.

Marking this one closed.
