### ISSUE TITLE
enigma-bbs organization

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#41]
May want to create an enigma-bbs org, and re-locate the code to that org... If you're interested in using the [bbs-io](https://github.com/bbs-io) org, I invited you with full access.

It will make it easier to add contributors.

**Comment by NuSkooler** [comment]
Contributors can easily create pull requests as-is. I don't have any current plans to move the code base from where it resides... I'm not sure what it would buy with a project like this.
