### ISSUE TITLE
npm install throws a long list of warnings.

### ISSUE THREAD

**Issue by oilcan-productions** [NuSkooler/enigma-bbs#410]
**Describe the Bug**
When installing on a RaspberryPi Bullseye with Python 3.9 the 'npm install' step produces a very long list of warnings.

**To Reproduce**
Any relevant steps to reproduce the behavior:
Flash a SD card with the latest Raspian Bulleye
sudo apt-get update && sudo apt-get upgrade
Follow the installation instructions for Enigma BBS
Create a clean configuration

**Expected Behavior**
No warnings during installation.

**Actual Behavior**
Lots of warnings during npm install (see attached file) 

**Screenshots**

**Environment**
* [ X] I am using Node.js v12.x LTS or higher
* [ X] `npm install` or `yarn` reports success
[enigma_npm_install_warnings.txt](https://github.com/NuSkooler/enigma-bbs/files/8376147/enigma_npm_install_warnings.txt)

* Actual Node.js version (`node --version`): v12.22.5
* Operating system (`uname -a` on *nix systems): Linux rpi-400 5.10.63-v7l+ #1488 SMP Thu Nov 18 16:15:28 GMT 2021 armv7l GNU/Linux
* Revision (`git rev-parse --short HEAD`): 32bc2359
* Any additional relevant information about your setup

**Comment by NuSkooler** [comment]
Thanks for the report!

Most of the compiler warnings here are regarding SQLite which I plan on updating. I need to update the transaction package to work with the latest SQLite as well. 

Some of the other warnings are regarding packages that I also plan on updating. Probably after we get through this cursor position update I can look at this.

Happy to accept PRs!

**Comment by NuSkooler** [comment]
https://github.com/NuSkooler/enigma-bbs/issues/398

**Comment by NuSkooler** [comment]
The sqlite3 module was updated - it should be cleaner now.
