### ISSUE TITLE
Syntax error in core/theme.js when running main.js

### ISSUE THREAD

**Issue by Sanlys** [NuSkooler/enigma-bbs#411]
**Describe the Bug**
Whenever I run ./main.js, I get a syntax error from node.

**To Reproduce**
Installed via "curl -o- https://raw.githubusercontent.com/NuSkooler/enigma-bbs/master/misc/install.sh | bash"

ran "./oputil.js config new"
Create a new configuration? y
Configuration path: have tried default and /home/vm/config/config.hjson
BBS name: default
First message conference: default
Conference description: default
First area in message conference: default
Area description: default
Logging level: Info

Output: Configuration generated

ran "sudo apt install p7zip lhasa arj lrzsz", no errors

ran "./main.js" in "/home/vm/enigma-bbs" and got the error described below

**Expected Behavior**
According to https://nuskooler.github.io/enigma-bbs/installation/testing.html, this should be outputted instead of the error: 
<img width="637" alt="https://nuskooler.github.io/enigma-bbs/assets/images/bkg.png">

**Actual Behavior**
it crashes and this is the output:
/home/vm/enigma-bbs/core/theme.js:588
                                if(_.isNumber(options?.position?.row)) {
                                                                      ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at initMenusAndThemes (/home/vm/enigma-bbs/core/bbs.js:226:42)
    at /home/vm/enigma-bbs/node_modules/async/dist/async.js:3669:28
    at replenish (/home/vm/enigma-bbs/node_modules/async/dist/async.js:446:21)

**Screenshots**
<img width="637" alt="Screenshot 2022-04-07 at 13 27 35" src="https://user-images.githubusercontent.com/49021092/162188634-836e8070-e0c5-4fca-b71e-7707f4e03a9c.png">

**Environment**
* [Y] I am using Node.js v12.x LTS or higher
* [Y] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): v12.22.12
* Operating system (`uname -a` on *nix systems): Linux vm 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
* Revision (`git rev-parse --short HEAD`): e19d7e58
* Any additional relevant information about your setup: Running as an ubuntu server in ESXi, same problem on a local arch linux install.

**Comment by NuSkooler** [comment]
Looks like we missed the Node v14 upgrade in the `install.sh`. Should be resolved with https://github.com/NuSkooler/enigma-bbs/commit/78a24bd8c9793fc9f051c02f8f31f4ccb50e2059 now.
