### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#42]
I know there's still some firming up of the web-ui to go... but some tool suggestions for a web user interface...
- [fTelnet](https://github.com/rickparrish/fTelnet) - HTML5 Terminal
- [Material UI](http://www.material-ui.com/) - for [React](https://github.com/reactjs)
- [Redux](https://github.com/rackt/redux) - Flux-like control flow
- [Webpack](https://webpack.github.io/) - module bundler/build tool
- [Babel](http://babeljs.io/) - ES6/7 feature support and JSX
- [fetch](https://www.npmjs.com/package/isomorphic-fetch)
- [polyfills service](https://github.com/Financial-Times/polyfill-service) - browser polyfill as a service
  - Can be used to patch browser features directly, so that babel only needs to do what can't be polyfilled (generator/async/await, etc)

I'm happy to help with this, I'm planning on using my week off at the end of the month to work on a BBS ui anyways, and the wiring for services should be generic enough to reuse.  I'm planning on tightly coupling the web ui, with a node api service, but that node api service should be able to be replaced with different backends, synchronet, enigma, x84, etc.

**Comment by NuSkooler** [comment]
@tracker1 FYI, http://l33t.codes/xibalba-bbs/ has fTelnet up for Xibalba BBS running ENiGMA½. 

As far as a general solution, I've yet to do any serious design beyond jotting down ideas on this realm. ENiGMA½ uses server modules. The current idea is to have a RESTful web server module that would allow various service hookups -- which can of course include a web frontend.

The ability to login, interact with messages and file base may be nice. Beyond that, it starts become just another website and not a BBS.

**Comment by NuSkooler** [comment]
@tracker1 I guess I should add: What sort of web related features are you interested / looking for / wanting to design? You've listed some technologies, but not what your intent is at all.

**Comment by tracker1** [comment]
Mainly message forums, file download/upload, chat/irc, and going directly into a specific door via ftelnet.

**Comment by NuSkooler** [comment]
Closing this. This is not something in the ENiGMA roadmap. If anyone would like to create a web interface(s), the support -- including a webserver -- is there in the system that can be built upon as addon module(s).
