### ISSUE TITLE
Switch to Prettier

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#423]
Switch to [Prettier](prettier.io/) for formatting. This will help now that there are more contributors, etc.

Thinking the following options:
`--tab-width 4`
`--single-quote`
`--arrow-parens avoid`
`--traling-comma es5`

**Comment by cognitivegears** [comment]
Definitely +1 for this one. I don't really care what the format is, but auto formatting would save some time with trying to match styles.

**Comment by tracker1** [comment]
may, or may not be worthwhile to add a .`vscode/settings.json` that specifies the prettier extension with format on save, as well as the other settings, tab size... though not sure what editor most are using to contribute.

**Comment by NuSkooler** [comment]
@tracker1 This ticket has been closed for a bit. Also Prettier uses it's own configuration which if you look is already included: https://github.com/NuSkooler/enigma-bbs/blob/master/.prettierrc.json

**Comment by tracker1** [comment]
@NuSkooler I'm referring to a VS Code extension... you can configure it to format on save, it will use the `.prettierrc.json` and the prettier tool to do the actual formatting.

As an example...  can also set line endings and tab indentation.

```json
{
  "editor.formatOnSave": true,
  "editor.tabSize": 2,
  "files.eol": "\n",
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[typescriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascriptreact]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  }
}
```
