### ISSUE TITLE
Problems while installing

### ISSUE THREAD

**Issue by omerien** [NuSkooler/enigma-bbs#430]
I love how I ALWAYS have problem with C core files included from macOS SDK, that's so annoying

**Describe the Bug**
I cannot install enigma-bbs

**To Reproduce**
1. Run install.sh script from the docs.

**Expected Behavior**
Getting an installed version of enigma-bbs

**Actual Behavior**
Errors while compiling, [here's the full log](https://github.com/omerien/omerien/blob/main/enigmabbs.1)

**Screenshots**

**Environment**
* [x] I am using Node.js v14.x LTS or higher
* [ ] `npm install` or `yarn` reports success
npm install reports that:
```
npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/omerien/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/omerien/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/omer/.npm/_logs/2022-06-10T19_01_19_815Z-debug-0.log
```
yarn wasn't found

* Actual Node.js version (`node --version`): v18.3.0
* Operating system (`uname -a` on *nix systems): Darwin omerien.home 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64 arm Darwin
* Revision (`git rev-parse --short HEAD`): c1311f06
* Any additional relevant information about your setup : macOS Monterey (12.4), M1 Pro, Xcode CLI 13.4.0.0.1.1651278267.

**Comment by NuSkooler** [comment]
I'm just glancing through your log, but it looks like your OS is not being detected properly by one of the dependencies (https://github.com/Microsoft/node-pty) during compile time. You might need to check there and make sure your compiler is setup correctly/etc.

**Comment by NuSkooler** [comment]
Can this be closed?

**Comment by omerien** [comment]
I’m trying to recompile it, leave it open a few days I’ll close it

**Comment by NuSkooler** [comment]
[TROUBLESHOOTING.md](https://github.com/NuSkooler/enigma-bbs/blob/master/TROUBLESHOOTING.md) may help you

**Comment by omerien** [comment]
No problem now, was on my side, my C header files were a bit messed up.

**Comment by NuSkooler** [comment]
@omerien Thanks for reporting back!
