### ISSUE TITLE
New User Login...

### ISSUE THREAD

**Issue by bucko219** [NuSkooler/enigma-bbs#432]
I know you told me to put this as a feature request, but for me it was a bug.

config.hjson has access levels defined in the General Access section. 2 regular access levels, 1 new user. 

Upon a new user logging on, the BBS accepts all the info of the new user. When that info is finished being entered, the BBS says now it is time to leave a note for the sysop. You press enter and it says you do not have access to post in the section. From there it just loops. If the user logs back on, and enters the info they gave on new user registration. It allows them to log on. IF, they try to view new messages on login, the BBS drops carrier.

Log files show the following:
 Failed to perform temporary message area/conf switch. 

Unbeknownst to me, this was happening in v0.12 also, I booted up an older VM of the BBS and it did the same thing. 

The way I got around it was just Remming (//) the general access portion out as it is when you create a new configuration. Which by the way when creating a new configuration leaves that section remmed out..

Hopefully, this helps a bit. I am 99% sure it worked in 0.11 with that section not remmed out as I had new users log in with no issues...

All software is up to date as of a couple of weeks ago, I haven't added in the new updates that have been added this weekend..

**Comment by NuSkooler** [comment]
@bucko219 Sorry can you provide the configuration files or sections you are referring to? I've gone through a number of new installs lately and have not seen this issue at all.

**Comment by bucko219** [comment]
@NuSkooler Here is the section in question, when you create a new configuration it has these lined remmed out (//) I believe I started around version 0.10 and it worked fine, at some point it changed between 0.10 and 0.11 because I pulled up an old backup of 0.11 and the exact same thing happend.. If I rem out the lines everything works as should be.. 

//  General user configuration
    users: {
        //
        //  ENiGMA½ utilizes user groups similar to Windows and *nix. Built in groups
        //  include "users" (for regular users) and "sysops" for +ops. You can add other
        //  groups to the system as well by adding a 'groups' key in this section:
        groups: [
        //
            "GoldMember", "VisitingSysOp", "NewUser"
        ]
        //
        //
        //  Set default group(s) new users should automatically be assigned to:
        defaultGroups : [
         "NewUser"
         ]
        //

        //  Should new users require +op activation?
        requireActivation: false

        //  How long pre-authenticated users (have not logged in) can idle
        preAuthIdleLogoutSeconds: 180

        //  How long authenticated users (logged in) can idle
        idleLogoutSeconds: 360

        //  Usernames reserved for applying to your system
        newUserNames: [
            new
            apply
        ]

        //  Handling of failed logins
        failedLogin: {
            //  disconnect after N failed attempts. 0=disabled.
            disconnect: 3

            //  Lock the user out after N failed attempts. 0=disabled.
            lockAccount: 9

            //
            //  If locked out, how long until the user can login again?
            //  Set to 0 to disable auto-unlock
            //
            autoUnlockMinutes: 360
        }

        //  Allow email driven password resets to unlock accounts?
        unlockAtEmailPwReset: true
    }


---------------------------------------

This was the way I had it and was getting the errors, once I remmed (//) the lines in question for the default groups and groups everything worked as designed.

Hope that helps, sorry about using the term remmed I am still in the basic programming language world.

**Comment by NuSkooler** [comment]
I'm really having a hard time following what you did and what you are expecting?

* A clean / fresh install of enigma will use default groups (reg users = 'users', first user = op = 'sysops') and new users are able to send feedback to the op just fine
* If you change group memberships in your config, you'll need to update users that belong to the old groups as well. Or at least continue to keep them and only add *additions*

What exactly are you trying to achieve?

**Comment by bucko219** [comment]
I understand sometimes I don't explain fully. When you add user groups by removing the // and adding in more, it stops the new user from leaving feedback on sign in, It goes into a loop. If you leave the // and not use that section and only use users and sysops everything is fine. This option worked in I believe 0.10 because when I first put my board online, I was getting feedback from new users and had different access groups setup, but not after. I have it working. I am happy with just finding out that I fixed it so I can have new users login again.

In a nutshell, if you set up extra access groups, new users can't leave feedback and login, they get to the point where it says to leave feedback, and when they press a key it goes into a loop saying you don't have access to that message area. That is why I never noticed any new users.  I never got the feedback, and if they logged back on if they tried to scan for new messages it would drop carrier. 

This is more of a feature doesn't work properly then a bug because if you leave that section I posted above alone everything works fine.. I hope I haven't confused you more...

**Comment by NuSkooler** [comment]
OK I'm pretty sure what you're doing is removing the comment lines from the example, and said example does not include "sysops" for +ops and "users" for regular users. Both are essentially special built in groups, but this would override all of it you don't also _include_ those two sets.

Is this right? You can test it by doing e.g. this:
```hjson
groups: [
	"users", "GoldMember", "VisitingSysOp", "NewUser"
]

defaultGroups : [
	"users", "NewUser"
]
```

In other words, all users need to belong to at least the "users" group, and SysOps in the "sysops" group. They can _additionally_ belong to other group(s).

**Comment by bucko219** [comment]
Bingo! That's exactly it. I will test that tomorow night.. Took me long enough to explain it. LOL Thanks.. Will close this now...
