### ISSUE TITLE
Delete Messages in message area...

### ISSUE THREAD

**Issue by bucko219** [NuSkooler/enigma-bbs#433]
Adding support to delete messages in a message area, sort of like how it is done with email. You can do it a couple of different way, from the list hitting the DEL key on the message you want to delete or possibly wtih Sysop access group a lightbar added to the bottom where reply next is. NO rush on this one as it is not a bug fix or a big request..

**Comment by NuSkooler** [comment]
Duplicate of See https://github.com/NuSkooler/enigma-bbs/issues/74 -- see also https://github.com/NuSkooler/enigma-bbs/issues/29

I'll try to look at this fairly soon if someone else doesn't pick it up
