### ISSUE TITLE
NNTP Write Functionality

### ISSUE THREAD

**Issue by fc757** [NuSkooler/enigma-bbs#449]
It would be swell to see the circle complete and have the NNTP content server allow posts via a client.

Ticket for implementing the NNTP content server: https://github.com/NuSkooler/enigma-bbs/issues/184

I think it would be useful and allow me to keep up with BBS network mail more often.

If it isn't too much of a pain in the butt to implement. Are you a bad enough dude to do it?

![Are_You_A_Bad_Enough_Dude_banner (Custom)](https://user-images.githubusercontent.com/4654695/190890395-f65a977d-2c65-43eb-81ec-cc198d3f9d9a.png)

Also, more integrated QWK support would work too: https://github.com/NuSkooler/enigma-bbs/issues/31

If I could download a QWK packet from the message menu and upload my replies, that would work too.

**Comment by NuSkooler** [comment]
Relies on: Update nttp-server to 3.1.0+ #401

**Comment by NuSkooler** [comment]
@fc757 If you'd like to beta (alpha?) test, see the branch @ https://github.com/NuSkooler/enigma-bbs/pull/451
