### ISSUE TITLE
Update lodash to 4.0.x

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#45]
Update [lodash](https://lodash.com/) to 4.0.x

This might break things, so it will need careful inspection.

**Comment by ellisgl** [comment]
I'm pretty sure it will break things. https://www.npmjs.com/package/lodash-migrate Should help.

**Comment by NuSkooler** [comment]
I ran lodash-migrate the other day, but I'm not sure it covers everything quite yet. Some of the things that were pointed out didn't seem to sync up with the documentation.

In any case, you're probably right: things will need adjusted/fixed along with this.

**Comment by NuSkooler** [comment]
Now using v4.17.4 as of this writing
