### ISSUE TITLE
optional new user fields

### ISSUE THREAD

**Issue by AviatingPenguin** [NuSkooler/enigma-bbs#457]
Looking to make all new user fields with the exception of username and password optional, but unsure how to do this in nua.js

**Comment by NuSkooler** [comment]
I was going to do some work on this, but it's probably very easy. If you want to take a stab at it, in `nua.js` you'll find this code:

```node
newUser.properties = {
    [UserProps.RealName]: formData.value.realName,
    [UserProps.Birthdate]: getISOTimestampString(
        formData.value.birthdate
    ),
    [UserProps.Sex]: formData.value.sex,
    [UserProps.Location]: formData.value.location,
    [UserProps.Affiliations]: formData.value.affils,
    [UserProps.EmailAddress]: formData.value.email,
    [UserProps.WebAddress]: formData.value.web,
    [UserProps.AccountCreated]: getISOTimestampString(),
    ...other stuff...
};
```

To default values that are not passed in (they will be `undefined`), you can do like this:
```node
    [UserProps.Sex]: formData.value.sex || '',
    [UserProps.Location]: formData.value.location || '',
    [UserProps.Affiliations]: formData.value.affils || '',
    [UserProps.EmailAddress]: formData.value.email || '',
    [UserProps.WebAddress]: formData.value.web || '',
```

For Birthdate, you should probably just set it to either `getISOTimestampString(moment())` or a specific ate (see moment.js docs).

Then, update your art and MCI values, and you should be set.

**Comment by NuSkooler** [comment]
Looking for a tester for https://github.com/NuSkooler/enigma-bbs/pull/480

**Comment by cognitivegears** [comment]
@AviatingPenguin can you please pull the latest code and re-test? This should be fixed now.

**Comment by cognitivegears** [comment]
Closing this issue as I believe it has been addressed. @AviatingPenguin if you still have any issues please feel free to reopen.
