### ISSUE TITLE
Require Node.js 4.2.x+

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#46]
Update requirements for Node.js to v4.2.x or higher. Currently it's at v0.12.2. Using 4.2.x+ will give the ability to use newer ES6 features.

**Comment by ellisgl** [comment]
Current stable is 5.4.0 btw

**Comment by NuSkooler** [comment]
> Current stable is 5.4.0 btw

I've debated going straight to 5.4.x, but 4.2.x is LTS. If there are enough compelling arguments for 5.4, it may be worth it.

**Comment by tracker1** [comment]
5.x has started adding some of the spread/destructuring etc, but it's still incomplete in v8.

**Comment by NuSkooler** [comment]
Going with 4.2.x for now. Some new code (not yet checked in) I'm working on now relies on this.

**Comment by NuSkooler** [comment]
As of the  [msg_network](https://github.com/NuSkooler/enigma-bbs/tree/msg_network) merge @ 6f8f8f7e9d22c06d04e045ec455c344717d16f9b Node 4.2.x+ is required.
