### ISSUE TITLE
Message Area - Cancel message

### ISSUE THREAD

**Issue by nugax** [NuSkooler/enigma-bbs#47]
Ability to cancel a message without addressing the message, subject, etc.

**Comment by NuSkooler** [comment]
On my current To-Do list is to have empty name = cancel new posts. ESC could probably be added to both name & subject as well. 

ESC in in the message body already toggles the menu, which contains the "discard" option.

**Comment by NuSkooler** [comment]
Resolved with fbba2160fef38f674cb15e4c1347e7286cf0fd46 (ESC = cancels). If we really need empty names = cancel, a new issue can be opened up.
