### ISSUE TITLE
Docker QuickStart instructions fail with failed to register layer: ApplyLayer exit status 1

### ISSUE THREAD

**Issue by hackerdude** [NuSkooler/enigma-bbs#471]
**Describe the Bug**
Following the [Docker QuickStart instructions](https://nuskooler.github.io/enigma-bbs/installation/docker.html), the first step fails because enigmabbs/enigma-bbs:latest fails to build. Using Debian with Kernel 5.15.102-1, Docker v 23.0.1 build a5ee5b1

**To Reproduce**

Run the docker command on the QuickStart as is on a machine with docker and nothing else.

**Expected Behavior**

EnigmaBBS Latest docker image runs

**Actual Behavior**

````
$ docker run -it -p 8888:8888 \
--name "ENiGMABBS" \
-v "$(pwd)/config:/enigma-bbs/config" \
-v "$(pwd)/db:/enigma-bbs/db" \
-v "$(pwd)/logs:/enigma-bbs/logs" \
-v "$(pwd)/filebase:/enigma-bbs/filebase" \
-v "$(pwd)/art:/enigma-bbs/art" \
-v "$(pwd)/mods:/enigma-bbs/mods" \
-v "$(pwd)/mail:/mail" \
enigmabbs/enigma-bbs:latest
Unable to find image 'enigmabbs/enigma-bbs:latest' locally
latest: Pulling from enigmabbs/enigma-bbs
3689b8de819b: Pull complete
4178a276654a: Pull complete
7ce41f1824c5: Pull complete
a1a59a8255bd: Pull complete
d6672e85e608: Pull complete
61554675f8aa: Pull complete
8c59fec34488: Extracting [==================================================>]  68.43MB/68.43MB
c862ef99e89f: Download complete
14babd399e3a: Download complete
4f4fb700ef54: Download complete
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /tmp/v8-compile-cache-0/8.4.371.23-node.88: invalid argument.
````

It seems like the Node/V8 layer is failing to build. Perhaps it's time to upgrade the node on that Dockerfile and Image? Seems it's trying to build a 2020 8.4.371.23. Will try with a locally edited Dockerfile and report back.

**Environment**
* [x] I am using Node.js v14.x LTS or higher (I would if it would build)
* [ ] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): Node not installed on parent host. Node build fails
* Operating system (`uname -a` on *nix systems):
```` Linux myhostname 5.15.102-1-pve #1 SMP PVE 5.15.102-1 (2023-03-14T13:48Z) x86_64 GNU/Linux ````
* Revision (`git rev-parse --short HEAD`): None, using QuickStart
* Any additional relevant information about your setup
  Proxmox PVE but also fails on plain Linux.

**Comment by NuSkooler** [comment]
@hackerdude Thanks for the info! I'm just getting back from a vacation and will try and set up a test for this to take a look

**Comment by cognitivegears** [comment]
I just tried running it - seemed to work for me. (Win 11, Docker v4.22)Did you do something already @NuSkooler?

**Comment by NuSkooler** [comment]
I intended to add a note here as well -- worked for me as well. @hackerdude any info?

**Comment by cognitivegears** [comment]
This may also be corrected with PR #491

**Comment by cognitivegears** [comment]
@hackerdude can you please pull the latest and re-test? The base image has been updated.

**Comment by cognitivegears** [comment]
Closing this for now as I believe it has been addressed. If you still see any issues @hackerdude please re-open.
