### ISSUE TITLE
Implement System Log

### ISSUE THREAD

**Issue by NuSkooler** [NuSkooler/enigma-bbs#48]
**General Idea**
  * Stores time stamped log/event entries
  * Entries can be rounded to day/week/month/etc. for various stats
  * How much kept is configurable
  * Name/value pairs

**Examples**
  * This weeks callers
  * This months top posters
  * Last callers history can use this vs it's own storage mechanism

**Comment by ellisgl** [comment]
Nice!

**Comment by NuSkooler** [comment]
Setting 1.0.0-beta.1 milestone: This will be implemented to support various missing MCI

**Comment by NuSkooler** [comment]
Implemented @ 87877039899df15cf8a3ecedc97958b3c693d229. More additions based on this functionality to come soon. Currently used to populate last callers, various system/user stats, and so on.
