### ISSUE TITLE
Got an Invalid: "socket" is not a valid io type! for my door.

### ISSUE THREAD

**Issue by mkrueger** [NuSkooler/enigma-bbs#506]
Fixed that by:

```
--- a/core/door.js
+++ b/core/door.js
@@ -59,7 +59,7 @@ module.exports = class Door {
 
         if ('socket' === this.io && !this.sockServer) {
             return cb(Errors.UnexpectedState('Socket server is not running'));
-        } else if ('stdio' !== this.io) {
+        } else if ('stdio' !== this.io && 'socket' !== this.io) {
             return cb(Errors.Invalid(`"${this.io}" is not a valid io type!`));
         }
```

**Comment by cognitivegears** [comment]
Thanks @mkrueger for the report and fix!! I've gone ahead and made a PR for this. @NuSkooler can you or someone try this? I don't have any doors setup to test this with.

**Comment by cognitivegears** [comment]
@mkrueger it looks like this change has landed! If possible can you please pull the latest and verify that it is working for you?

**Comment by cognitivegears** [comment]
FYI I'm going to close this issue for now based on the code change, @mkrueger please feel free to re-open if you run into any more issues.
