### ISSUE TITLE
Message 'sort' field in config.hjson

### ISSUE THREAD

**Issue by nolageek** [NuSkooler/enigma-bbs#51]
Would be nice to be able to specify a sort order for the message areas.

```
areas: {
   area_one {
   name: area one
   desc: first area in config, but displayed second
   sort:2
   default: true
   }
area_two {
   name: area two
   desc: second area in config, but displayed first
   sort:1
   default: true
   }
}
```
etc...

**Comment by NuSkooler** [comment]
Resolved @ 0b23f0aa3b1cec50ae6e8fddb620a33446c761fb

An optional `sort` key is available in message conferences and areas. If the key is not present, the `name` key will be used instead.
