### ISSUE TITLE
User still logged-in?

### ISSUE THREAD

**Issue by melroy89** [NuSkooler/enigma-bbs#518]
**Describe the Bug**

I (DangerousI) logged-in again on your BBS (xibalba) via SSH using SyncTERM. But at some time I got automatically disconnected.. Maybe some time-out or.. That isn't the problem perse.. 

However, now the user still seems to be logged-in. And I can't login anymore. SSH doesn't work at all. Telnet will say: "that user is already logged-in".

**To Reproduce**

- Login into xibalba.l33t.codes (SSH 44511)
- Server disconnects / time-out?
- Unable to login again (user is already logged-in message)

**Expected Behavior**

Ideally do not disconnect. But once that happens, I should be able to relogin.

**Actual Behavior** / **Screenshots**

SSH:

![image](https://github.com/NuSkooler/enigma-bbs/assets/628926/022262ef-9d36-41fd-aad8-c59f9d8da4a7)

Telnet:

Error: "User is already logged-in", followed by:

![image](https://github.com/NuSkooler/enigma-bbs/assets/628926/736cf345-4e7b-4890-94c1-617b25538b7a)

**Environment**
- Linux
- using SyncTERM

**Comment by NuSkooler** [comment]
This is a known issue. Hoping when I get to upgrading Xibalba with the new SSH updates from @cognitivegears it will just go away, else will look into further. For now you should be good.

**Comment by cognitivegears** [comment]
@melroy89 if you get a chance could you try again with Xibalba? I believe @NuSkooler updated the BBS, hopefully that squashes the issue for you.

**Comment by melroy89** [comment]
Testing... 
![image](https://github.com/NuSkooler/enigma-bbs/assets/628926/74b77ade-cb78-4655-863d-d90cb2c99b1b)

 I leave the session open for tonight. Let's see whether it: 1. The server disconnect me or not. 2. Allows me to re-login in case of a time-out/disconnect.

**Comment by melroy89** [comment]
..Got timed-out now: 

![image](https://github.com/NuSkooler/enigma-bbs/assets/628926/5032ee7f-2943-4522-9d1a-961df267dcae)


I can confirm I can re-login again without issue this time! I think the issue is fully resolved now. Thanks!
