### ISSUE TITLE
Generate SSH cert with oputil

### ISSUE THREAD

**Issue by cognitivegears** [NuSkooler/enigma-bbs#519]
Now that we have upgraded the ssh2 library, it supports the ability to generate ssh certificates. We should take advantage of this to facilitate ssh setup without any external tools needed. Some thoughts below:

* Create a new core/oputil/oputil_ssh.js
* allow creation of the key with a random password or manual entered password. Add the password to the config.hjson.
* make sure the private key is saved with the minimum file permissions needed.
* update documentation (current description of running ssh-keygen etc should not be removed but changed to a secondary option.

**Comment by NuSkooler** [comment]
This could probably live under [oputil config](https://github.com/NuSkooler/enigma-bbs/blob/master/core/oputil/oputil_config.js), e.g. `oputil.js config ssh-key [options]`

**Comment by crhultay** [comment]
Raised PR https://github.com/NuSkooler/enigma-bbs/pull/578
