### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by ftoledo** [NuSkooler/enigma-bbs#52]
I just clone, npm install and create the default config (as say in the quickstart) and ssh key
i use node 4.3.1 on debian testing.

try to run and get this error:

<pre>
ragnarok@ragnarok:/tmp/enigma-bbs$ ./main.js 
Error: End of input while parsing an object (did you forget a closing '}'?) at line 26,1 >>> ...
/tmp/enigma-bbs/core/bbs.js:81
				logger.log.error(err);
				          ^

TypeError: Cannot read property 'error' of undefined
    at complete (/tmp/enigma-bbs/core/bbs.js:81:15)
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:52:16
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:696:30
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:167:37
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:1209:30
    at configInit (/tmp/enigma-bbs/core/bbs.js:64:6)
    at complete (/tmp/enigma-bbs/core/config.js:89:4)
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:52:16
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:696:30
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:167:37
</pre>

**Comment by NuSkooler** [comment]
Hey, looks like the quickstart `config.hjson` example I posted was bad. I just pushed a minor update to it. Take a look at the full [configuration docs](https://github.com/NuSkooler/enigma-bbs/blob/master/docs/config.md) as well

**Comment by NuSkooler** [comment]
BTW: One of the things I'm thinking about putting together is an option to `oputil.js` that would guide you though a basic configuration. Would be something like `./oputil.js config --new`.

**Comment by NuSkooler** [comment]
Feel free to re-open if needed

**Comment by ftoledo** [comment]
fixed thanks!.
