### ISSUE TITLE
Mysql Support and other DB options

### ISSUE THREAD

**Issue by hungry-bogart** [NuSkooler/enigma-bbs#524]
**Is your feature request related to a problem? Please describe.**
Is it possible/desirable to have another database system either built into or documented in the main reference guide? If I missed it, let me know.

I have a docker-compose file that I'm working on and I'd like to use mysql instead of sqlite for configuration and control reasons. This may be unnecessary for something like a BBS, but I thought I would bring it up anyway.

Once you move to production it seems that having a more full featured database, especially with a Docker setup would in a lot of ways be easier to work with. There are a lot more ways to backup and integrate with mysql. Postgresql would be an amazing option to have, but I don't know whether this is on the roadmap.

**Describe the solution you'd like**
My current docker-compose file is untested, so if it works, I'll share the results. The solution I would like is to see a docker-compose example in the docs that shows how to correctly incorporate an alternative database. There also doesn't seem to be a ton of good docker-compose examples out there as an aside.

**Describe alternatives you've considered**
Docker-compose with mysql is the option I'm considering presently.

**Additional context**
No additional context, but a last request is that Dockerhub include more information. It only has the name of the image and at first glance it's hard to tell if it actually belongs to the original maintainer. It's nice for folks who run this to be able to trust the image and additionally read more about what it does and does not do.

**Comment by NuSkooler** [comment]
Hi @hungry-bogart! Unfortunately there are no abstractions or adapters over the database, it's pure SQLite.
