### ISSUE TITLE
VTX Cleint Error - eason: Object does not exist: No matching art for supplied criteria: CONNECT

### ISSUE THREAD

**Issue by dguttierrez** [NuSkooler/enigma-bbs#529]
**Describe the Bug**
I have configure VTX Client and websockets. On server side everything is ok. I have turned on debug logs and I see this error, when I connect with browser:

[2024-01-18T07:24:08.579Z] DEBUG: ENiGMA½ BBS/1185784 on rpisrv01.macqo.d-mashina.net: Cannot find theme art (nodeId=1, sessionId=DwUAkoagePE)
    reason: Object does not exist: No matching art for supplied criteria: CONNECT

But I I tap enter (like login) on first screen of BBS, that I can blidly enter usernama ena password, but I don't get any graphics in browser.

**To Reproduce**
I can reproduce this on CONNECT:

**Expected Behavior**
Enigma BBS Art must been shown in browser.

**Actual Behavior**
Thare are no BBS Art.

**Screenshots**
![Screenshot 2024-01-18 at 08 40 34](https://github.com/NuSkooler/enigma-bbs/assets/18676498/2734cc0d-c411-40d4-a5a5-15f9cda9e6a9)

**Environment**
Latest Engima
Latest VTX Client
RPI4 with Debian 11.8
node --version v14.21.3

**Comment by dguttierrez** [comment]
I have now modified vtxdata.js and change it to this:

var vtxdata = {
        sysName:        "LowCrash DEV BBS",
        wsConnect:      "wss://myaddress:8811",
        term:           "ansi-bbs",
        codePage:       "CP437",
        autoConnect:    0,
        telnet:         1,
        wsProtocol:     'bbs',
        wsDataType:     'arraybuffer',
        fontSize:       '24px',
        fontName:       'UVGA16',
        crtCols:        80,
        crtRows:        25,
        crtHistory:     500,
        xScale:         1,
        initStr:        "",
        defPageBorder:  232,
        defPageBG:      0x10,
        defCrsrFG:      0x07,
        defCrsrAttr:    [ 'thick', 'horizontal' ],
        defCellFG:      0x07,
        defCellBG:      0x00,
        defCellAttr:    []
    };

now I have no problems.

**Comment by NuSkooler** [comment]
@dguttierrez Hi! If you're able to get through the WebSocket connection via VTX, the issue is more likely in your `menu.hjson` entries. The default system looks something like this:

```
telnetConnected: {
    desc: Telnet Connect
    art: CONNECT <----- note the CONNECT here specifying to load a CONNECT* art file
    next: matrix
    config: { nextTimeout: 1500 }
}
```

May be a hint in the previous log about not finding the **theme** art. What do your `config.hjson` say in the `theme` section?

Defaults are:

```
theme: {
  default: luciano_blocktronics
  preLogin: luciano_blocktronics <---- used before the user logs in
  // ...
}
```

If you're using another theme there, make sure you have a `CONNECT.ANS` for example, within that theme's folder.

**Comment by NuSkooler** [comment]
I'm puzzled what could have changed in the VTX config to make this happen though...

**Comment by dguttierrez** [comment]
Hi, conifg.hjson and menu.hjson is ok. SSH and Telnet is also ok. With modified vtxdata.js is ok.

So for now, everything is ok.
