### ISSUE TITLE
theme error on apply (signup): Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by ftoledo** [NuSkooler/enigma-bbs#53]
steps: 
start the bbs, conect via telnet, select apply, fill form and submit

<pre>
ragnarok@ragnarok:/tmp/enigma-bbs$ node main.js 
(node) Buffer.get is deprecated. Use array indexes instead.

/tmp/enigma-bbs/core/theme.js:352
    client.log.debug( { themeId : themeId, info : client.currentTheme.info }, desc);
                                                                     ^

TypeError: Cannot read property 'info' of undefined
    at setClientTheme (/tmp/enigma-bbs/core/theme.js:352:70)
    at setTheme (/tmp/enigma-bbs/core/user_login.js:64:25)
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/tmp/enigma-bbs/node_modules/async/lib/async.js:233:13)
    at _parallel (/tmp/enigma-bbs/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/tmp/enigma-bbs/node_modules/async/lib/async.js:731:9)
    at authenticated (/tmp/enigma-bbs/core/user_login.js:61:10)
    at complete (/tmp/enigma-bbs/core/user.js:181:4)
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:52:16
    at /tmp/enigma-bbs/node_modules/async/lib/async.js:1209:30

</pre>

**Comment by NuSkooler** [comment]
Can you post the contents of your `config.hjson`? I've not seen this one before - could be a bug with the new release or possibly something with the config somewhere.

**Comment by ftoledo** [comment]
i just use the defaults examples, i can not reproduce post the last commit (that fix it) and use the fixed config example: 

config.hjson:
http://paste.debian.net/419261/

now, hang on login. on the console i can read:

<pre>
ragnarok@ragnarok:~/enigma-bbs$ node main.js 
(node) Buffer.get is deprecated. Use array indexes instead.
[Error: No menu entry for 'fullLoginSequenceLoginArt']

</pre>
the log: 
http://paste.debian.net/419273/

**Comment by ftoledo** [comment]
i can reproduce now in fresh install:
git clone
npm install
create default config (copy/paste) from docs
./main.js
apply a new user with this data: 

username: ragnarok
real name: Fernando Toledo
birthdate: 1977/07/15
sex: M
location: bla
email: ragnarok@docksud.com.ar
password: pepepepe

the console output:
<pre>
ragnarok@ragnarok:~/enigma-bbs$ ./main.js 
(node) Buffer.get is deprecated. Use array indexes instead.
/home/ragnarok/enigma-bbs/core/theme.js:352
    client.log.debug( { themeId : themeId, info : client.currentTheme.info }, desc);
                                                                     ^

TypeError: Cannot read property 'info' of undefined
    at setClientTheme (/home/ragnarok/enigma-bbs/core/theme.js:352:70)
    at setTheme (/home/ragnarok/enigma-bbs/core/user_login.js:64:25)
    at /home/ragnarok/enigma-bbs/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/home/ragnarok/enigma-bbs/node_modules/async/lib/async.js:233:13)
    at _parallel (/home/ragnarok/enigma-bbs/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/home/ragnarok/enigma-bbs/node_modules/async/lib/async.js:731:9)
    at authenticated (/home/ragnarok/enigma-bbs/core/user_login.js:61:10)
    at complete (/home/ragnarok/enigma-bbs/core/user.js:181:4)
    at /home/ragnarok/enigma-bbs/node_modules/async/lib/async.js:52:16
    at /home/ragnarok/enigma-bbs/node_modules/async/lib/async.js:1209:30
ragnarok@ragnarok:~/enigma-bbs$ ./main.js 
(node) Buffer.get is deprecated. Use array indexes instead.
</pre>

the new log with the error: 
http://paste.debian.net/419276/

thanks!

**Comment by NuSkooler** [comment]
@ftoledo Thanks for the pastebin's and your patience! Here is the current problem:

The `config.hjson` example in the configuration docs is just that: an _example_. The issue is the `theme::defaults` entry specifying "super-fancy-theme" (which does not exist). When a new user is created via apply, they are getting assigned that theme.

The quick and easy fix is to comment out that line:
```hjson
defaults: {
   //     theme: super-fancy-theme
    }
```

There are probably other things in the sample config you don't want either such as AgoraNet configs and the like. I need to make it much more clear in the docs that this is an **example** only. 

I started last night on a config tool to generate a `config.hjson` file for new users. I'll try to get that wrapped up soon. In the meantime I'll update the docs slightly.

Try out this simple config:
```hjson
{
    general: {
        boardName: A Sample BBS
    }

    messageConferences: {
        local_general: {
            name: Local
            desc: Local Discussions
            default: true

            areas: {
                local_enigma_dev: {
                    name: ENiGMA 1/2 Development
                    desc: Discussion related to development and features of ENiGMA 1/2!
                    default: true
                }
            }
        }
  }
}
```

Since this started out messed up, the easiest thing for you to do is also delete your `db/user.db` file also. This will let you re-apply without it setting to a bad theme. Once I know this works for you, I'll probably change this bug to cover better handling if `defaults::theme` is set to something non-existent :smirk:

**Comment by ftoledo** [comment]
very good!.. i understand that is a sample config,, but i think that the quickstart docs should be a minimal sample and running config to start the bbs. i just update the theme_id value in the user_property table and work now! thanks you!

**Comment by NuSkooler** [comment]
@ftoledo I agree. I will get some updated documents up, and if you don't mind, ping you here to see if they make more sense than the current ones.

I made a bit of progress on the `oputil.js config --new` system as well. When complete, it should generate a good config for users (and while I'm thinking of it, I'm going to put in a bug now to track that!)
