### ISSUE TITLE
Install fails on Debian 12

### ISSUE THREAD

**Issue by minnixtx** [NuSkooler/enigma-bbs#538]
**Describe the Bug**
Install fails on Debian 12 but succeeds on Debian 11. See #537 

**To Reproduce**
Either run install scripts or try manual install on Debian 12

**Expected Behavior**
Installation succeeds

**Actual Behavior**
Installation fails
**Screenshots**

**Environment**
See #537 for relevant logs, environment and errors.

**Comment by NuSkooler** [comment]
Please try with a supported Node.js version, it should be fine. If you use `nvm` or similar tooling, you can have multiple Node versions on your box, but use e.g. 18.x for enigma

**Comment by minnixtx** [comment]
It works with version 18. See below:

<details>
<summary>Details</summary>
<br>
<pre>Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Thu May 16 19:29:29 UTC 2024 on pts/1
minnix@bbs:~$ nvm install 18
Downloading and installing node v18.20.2...
Downloading https://nodejs.org/dist/v18.20.2/node-v18.20.2-linux-x64.tar.xz...
############################################################################################################# 100.0%
Computing checksum with sha256sum
Checksums matched!
Now using node v18.20.2 (npm v10.5.0)
Creating default alias: default -> 18 (-> v18.20.2 *)
minnix@bbs:~$ nvm use 18
Now using node v18.20.2 (npm v10.5.0)
minnix@bbs:~$ git clone https://github.com/NuSkooler/enigma-bbs.git
Cloning into 'enigma-bbs'...
remote: Enumerating objects: 35560, done.
remote: Counting objects: 100% (6184/6184), done.
remote: Compressing objects: 100% (1532/1532), done.
remote: Total 35560 (delta 4839), reused 5855 (delta 4541), pack-reused 29376
Receiving objects: 100% (35560/35560), 14.53 MiB | 23.10 MiB/s, done.
Resolving deltas: 100% (26865/26865), done.
minnix@bbs:~$ cd enigma-bbs
minnix@bbs:~/enigma-bbs$ npm install
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)

added 341 packages, and audited 342 packages in 1m

50 packages are looking for funding
  run `npm fund` for details

4 moderate severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
npm notice 
npm notice New minor version of npm available! 10.5.0 -> 10.8.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.0
npm notice Run npm install -g npm@10.8.0 to update!
npm notice</pre>
</details> 

Thanks for the help.

**Comment by NuSkooler** [comment]
@minnixtx Thanks! I created a ticket to look into newer versions of Node

**Comment by crhultay** [comment]
@minnixtx Please retry, NodeJS has been moved to v22.

In addition, the ```install.sh``` has been greatly improved, so you can install on any OS.

@NuSkooler This can be closed.
