### ISSUE TITLE
ANSI art edited with PabloDraw are displayed wrong on MS-DOS terminals

### ISSUE THREAD

**Issue by dream7prod** [NuSkooler/enigma-bbs#542]
**Describe the Bug**
ANSI art edited with PabloDraw are displayed wrong on vintage terminal programs under MS-DOS, like Qmodem or Telix.
Seams ANSI file is displayed raw (see screenshots).
Syncterm or MacOs terminal works fine.

Is there any recommended ANSI editor ? As all ANSI arts from luciano_blocktronics works fine, which software was used to create that theme ?

**To Reproduce**
Open an art file like PAUSE.ANS, just save it without making any changes. (PabloDraw changes original ANSI code a lot even without editing anything...)
Use Telix or Qmodem under MS-DOS on a real vintage PC or DOSBox (tried both) to connect to EnigmaBBS.
Every screen that uses pauses are corrupted.

**Screenshots**

With PAUSE.ANS saved with PabloDraw : ("Account is locked" art is just for testing with a lightweight ANSI file)

![Capture d’écran 2024-06-20 à 20 04 10](https://github.com/NuSkooler/enigma-bbs/assets/48924192/a3b65b62-7647-4e68-8d99-b656993b88f9)

With original PAUSE.ANS

![Capture d’écran 2024-06-20 à 20 05 23](https://github.com/NuSkooler/enigma-bbs/assets/48924192/71dfc321-494d-43a2-9071-5a2e0c5ab740)

PAUSE.ANS saved with PabloDraw : 
[PAUSEPD.ANS.zip](https://github.com/user-attachments/files/15918500/PAUSEPD.ANS.zip)

Thanks !

**Environment**
* [ ] I am using enigmabbs/enigma-bbs:latest under Docker container

**Comment by NuSkooler** [comment]
@dream7prod Interesting - I likely created the original `PAUSE.ANS` with PabloDraw. I wonder if it's a difference in the hosting platform: I would have done it under Linux or Windows.

Try perhaps [IcyDraw](https://github.com/mkrueger/icy_tools/blob/master/crates/icy_draw/README.md) or [Moebius(https://blocktronics.github.io/moebius/)

**Comment by dream7prod** [comment]
That's really interesting ! I'm not ANSI expert but after looking at the new saved ANSI code with an hex editor, comparing to the original code, it looks like colors are now saved as RGB values instead of the old-school "16 values" fashion (can't find any option on PabloDraw related to this). I may be wrong... but that could explain why old terminals won't understand this. Doesn't looks like an encoding problem, though I'll try on windows tomorrow and IcyDraw as well (which seams to have option for 16 colors restriction).

Original file : 
<img width="765" alt="Capture d’écran 2024-06-21 à 00 19 36" src="https://github.com/NuSkooler/enigma-bbs/assets/48924192/2b11c57e-9864-4136-80fa-b9a287eb9da5">

New PabloDraw (3.3.13.0) saved file : 
<img width="769" alt="Capture d’écran 2024-06-21 à 00 19 48" src="https://github.com/NuSkooler/enigma-bbs/assets/48924192/0129640c-1e29-46b0-9971-e1915342c350">

**Comment by NuSkooler** [comment]
@dream7prod The 256c issue is interesting. I wonder if it's defaulting different when run under macOS.
