### ISSUE TITLE
Echomail packets rejected because "toUserName field must be 36 bytes max"

### ISSUE THREAD

**Issue by voipmeister** [NuSkooler/enigma-bbs#549]
**Describe the Bug**
While resyncing an echomail area from my hub, not all messages in a specific echomail area are imported. They exist in the hub's area though - verified by logging in and checking.

Logging shows (this is one example, I have multiple with varying `(got XX)`:
```
{"name":"ENiGMA½ BBS","hostname":"node01","pid":25750,"level":40,"packetPath":"/tmp/enigftnimport-25750379921a236NoxAFdfjNKWlha7B/0e97c569.pkt","areaSuccess":{},"areaFail":{"tqw_gen":2},"otherFail":0,"error":"Invalid: FTN packet toUserName field must be 36 bytes max (got 56)","msg":"Packet 0e97c569.pkt import reported 2 error(s)","time":"2024-08-24T12:26:44.470Z","v":0}
```
I have opened the PKT file and looked for long usernames, but there are none as far as I can tell. I have the `retain` option active so I can provide an example file.

**To Reproduce**

* Sent a AREAFIX to my hub with `=TQW_GEN R=20` to resync the last 20 messages I was missing
* Scan is performed upstream (`1337:1/100`)
* Mail is polled and consequently rejected

**Expected Behavior**
I suspect something trips the `toUserName field must be 36 bytes max` check, but I don't see it yet. Based on the contents of the PKT file I would expect the messages to be imported.

**Actual Behavior**
PKT contents are rejected, messages are not imported. In my case the PKT files are retained as I configured that, so happy to provide one on request.

**Screenshots**

**Environment**
* [x] I am using Node.js v14.x LTS or higher
* [x] `npm install` or `yarn` reports success
* Actual Node.js version (`node --version`): `v18.20.4`
* Operating system (`uname -a` on *nix systems): `Linux node01 4.18.0-553.16.1.el8_10.x86_64 #1 SMP Thu Aug 8 17:47:08 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
* Revision (`git rev-parse --short HEAD`): `9c0bc88f`
* Any additional relevant information about your setup: Basically unmodded, one FTN connected.

**Comment by voipmeister** [comment]
Example PKT files + logging sent via email as discussed 🙂

**Comment by NuSkooler** [comment]
Got the packet file, I will try to figure out this guy ASAP.

**Comment by voipmeister** [comment]
I've tested with a `=TQW_GEN R=30` Areafix message from my Mystic board after resetting the area. Mystic imports the messages (all 30 of them), without errors.

**Comment by NuSkooler** [comment]
Turns out these were in fact, corrupt packets.
