### ISSUE TITLE
yaml vs hjson

### ISSUE THREAD

**Issue by tracker1** [NuSkooler/enigma-bbs#57]
Just curious if you'd looked at YAML vs HJSON ... since YAML is pretty widely used as a similar superset to JSON... just a thought...

(though, I'm getting deja vu, and may have asked about this one already)

**Comment by NuSkooler** [comment]
@tracker1 Yes, I've looked into YAML. I'm not a huge fan of proper YAML for configurations meant for general users: HJSON is much more resilient to formatting mistakes and has a very flexible syntax.

**Comment by tracker1** [comment]
Was just a thought, suggestion... just not a fan of creating *another file format that's not widely used or understood*  ... Not that yaml is all that widely used, it is pretty commonly used as front-matter for markdown based blogging, which is used by relatively novice users.

**Comment by NuSkooler** [comment]
JSON is very widely used and understood. Feel free to encode everything in JSON as it's 100% compliant with HJSON.

There are much more pressing issues than a configuration format change.

**Comment by tracker1** [comment]
Fair enough... was just a thought...
