### ISSUE TITLE
Add support for manually activating users

### ISSUE THREAD

**Issue by nolageek** [NuSkooler/enigma-bbs#71]
make  'requireActivation' false by default in config

**Comment by NuSkooler** [comment]
Temp solution will be OP: make `requireActivation` in `config.js` `false` by default.

Better fix: Add activation support to `oputil.js`, e.g.:
`oputil.js user --username SOMEUSER --activate`

**Comment by NuSkooler** [comment]
This was resolved with a update to  #72
