### ISSUE TITLE
FTN Node 0

### ISSUE THREAD

**Issue by apamment** [NuSkooler/enigma-bbs#75]
**Short problem description**
Setting up retronet, the hub address is 80:774/0 This causes problems as Enigma doesn't like the '0' node number.

**Environment**
- [X] I am using Node.js v4.x or higher
- [X] `npm install` reports success
- Actual Node.js version (`node --version`):
4.4.7
- Operating system (`uname -a` on *nix systems):
Linux

**Expected behavior**
Enigma should treat 0 as a valid node number? Mystic does, but _is_ 0 a valid number?

**Actual behavior**
It doesn't

**Comment by NuSkooler** [comment]
Working on getting your config in place & researching the validity of 0 for a node number. Even if it's not valid enig will need to support it.

**Comment by NuSkooler** [comment]
Looks like your configuration file was bad. Entries under `messageNetworks: { ftn: { areas: { /* ...*/ } } }` need to use `network`, not `networks`. Example:

```
rtn_commodore: {
  networks: retronet
  tag: RTN_COMMODORE
  uplinks:["80:774/0"]
}
```
Should be:
```
rtn_commodore: {
  // note singular here, no 's'
  network: retronet
  tag: RTN_COMMODORE
  uplinks:["80:774/0"]
}
```

**Comment by apamment** [comment]
*blush*

**Comment by NuSkooler** [comment]
This is something that probably should be called out at least in the log file or soemthing
