### ISSUE TITLE
Config Sort > 9 Doesn't work

### ISSUE THREAD

**Issue by apamment** [NuSkooler/enigma-bbs#76]
For :bug: bug reports, please fill out the information below plus any additional relevant information. If this is a feature request, feel free to clear the form.

**Short problem description**
Using the sort config variable with a number greater than 9 doesn't work

**Environment**
- [X] I am using Node.js v4.x or higher
- [X] `npm install` reports success
- Actual Node.js version (`node --version`):
4.4.7
- Operating system (`uname -a` on *nix systems):
Linux

**Expected behavior**
sort value 10 should come after 9
**Actual behavior**
sort value 10 comes after or before 1

**Comment by NuSkooler** [comment]
Should be good to go with 985d239ab9bdbb5035dcd1acc05ffa389114f998

**Comment by apamment** [comment]
Just updated to the latest git, still not working properly with numbers. I changed to using the alphabet and that works.

**Comment by NuSkooler** [comment]
Heh, had it working then cleaned up a piece of code & broke it. Try now :)
