### ISSUE TITLE
Conference Name in Message View Header

### ISSUE THREAD

**Issue by apamment** [NuSkooler/enigma-bbs#77]
This is a feature request, I wanted to add the conference name to the message header, I've done this myself on the view header, but not on the edit header yet.

I added this function to message_area.js (it might also be useful for other things)

```
function getMessageConfByAreaTag(areaTag) {
        const confs = Config.messageConferences;
        let conf;
        _.forEach(confs, (v) => {
                        if(_.has(v, [ 'areas', areaTag ])) {
                                conf = v;
                        return false;   //  stop iteration
                }
        });
        return conf;
}
```

And edited fse.js to use it to get the conference name in the same way as the area is shown.

**Comment by NuSkooler** [comment]
@apamment This is something I was actually looking at last night. We do need a `getMessageConfByAreaTag()` API.  Also,  I'd like to add general format MCI's (3 prob) to the various message headers, e.g. `%TLx` would allow a user to put supply a format string, defaulted as such:

- `{confName}`
- `{areaName}`
- `{confName}: {areaName}`

Hopefully that makes sense. The idea is to allow users to kind of put what they want where they want it

**Comment by NuSkooler** [comment]
Actually, I think I might have a better approach than what I mentioned above. I'm toying with the following right now:

- During new scan, conf/areas will be switched temporarily (e.g. not persisted to the DB)
- No need to pass message area to the message list -- it will just use the (temp) current conf/area
- The message list will be loaded by the message list (this is normal behavior in most cases but new_scan currently does a bit of hackery)
- Finally when the new scan is complete, the previous conf/area will be restored

This should fix a few things:

1. Make standard MCI codes available in the new message list, FSE art, etc. So `%MC` and `%MA` will work as expected in those areas -- no need for special MCI codes.
2. Fix the issue of replying in a new scan message list & not seeing your reply
3. Remove some of the hacks currently in place
4. I'd like to add formatting to the `%TL` MCI, e.g. you could create TL1's 'text' as `{MC!toUpper} @ {MA}` and end up with "SOME MESSAGE CONFERENCE @ The Area"

**Comment by NuSkooler** [comment]
I'll see if I can get the above implemented tomorrow night

**Comment by NuSkooler** [comment]
The above should now be resolved.  (4) will be implemented it's own.
