### ISSUE TITLE
Message conf/area welcome art

### ISSUE THREAD

**Issue by nolageek** [NuSkooler/enigma-bbs#81]
Not sure what you'd call it, but was thinking you could have it so that if a conference or area is chosen, if specified an ansi could be shown for s specified period of time. This could be a 'welcome to suck-and-such conference' message, or something stating the purpose, etc...  This page could have an MCI code for the message base description. Perhaps configurable via config.hjson:

```
                local_general: {
                    name: Miscellaneous Debris
                    desc: General discussions, introductions. No set topic, GO NUTS!
                    sort: 2
                    art: LOCGENERAL
                    nextTimeout: 2000
                }
```

**Comment by NuSkooler** [comment]
I dig it - will be easy to implement, so I'll try to get it in with the next set of pushes

**Comment by NuSkooler** [comment]
This was easy so I put it in alongside some other changes I was working on.
Simply specify `art` as described in an area or conf block and the standard art lookup system will apply. By default, it will show with a pause prompt. If you want to override this, put a `config` block with `pause` set to false:
```
my_area: {
  // ...
  art: MYART
  config: {
    pause: false
  }
}
```
