### ISSUE TITLE
Hide "Logging In" users from Who's Online

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#84]
I get hit with a lot of telnet requests that aren't real connections as I run my BBS on port 23. When viewing "Who's Online", it's often littered with a large amount of "Logging In" connections - to see 10  or more is reasonably common.

It would be nice if these were hidden, or a config option was available to be able to hide them.

![screenshot from 2016-08-15 22-56-30](https://cloud.githubusercontent.com/assets/668464/17681114/98ee9070-633b-11e6-8a82-7463abb76bc5.png)

**Comment by tracker1** [comment]
I keep thinking that adding in a `click esc twice to enter` on connection with a 10 second timeout might be a good idea... harken back to the old frontdoor days, and deal with the bots quickly.

**Comment by NuSkooler** [comment]
@tracker1 : I'd rather not add a frontdoor ESC type system, though it would be fairly trivial to have an option to override the default idle logout for pre-logged in users (e.g. on the matrix). If you do want the ESC system on your own board it's also very simple: Route to "prematrix" or something before matrix and put the ESC logic there. If they pass, go on to matrix. Enig makes this easy.

@davestephens : Are all of these bots staying on for the default idle time (I believe it's set to 3m) or are they doing something to stay on longer?

**Comment by NuSkooler** [comment]
@tracker1 Just to clarify, this is what I mean by "route" the first menu:

In `config.hjson` you can override the telnet (and SSH if you need) `firstMenu` property:
```
// ...
servers: {
  telnet:  {
    firstMenu: frontdoor
  }
}
```

Then, in your `menu.hjson`, describe frontdoor:
```
// ...
frontdoor: {
  art: FRONTDOOR
  module: frontdoor
  // telnetConnected is the default firstMenu overridden above
  next: telnetConnected
}
```

Finally, you can create a very simple `frontdoor.js` in mods (derived from MenuModule) that sets a timeout & waits for a ESC key press. If pressed within the timeout, calls `nextMenu` else disconnects.

Hopefully that makes sense.

**Comment by tracker1** [comment]
Cool... my only thought was that would seem pretty BBS-like and would suit for more quickly dropping the scripts.

**Comment by NuSkooler** [comment]
@davestephens  Default idle timeout is 6m. I just added a `preAuthIdleLogoutSeconds` variable to the config @ 2m. If a user is not authenticated (e.g. has not logged in) they are given 2m for idle time. Once logged in, they get 6m. Note that both values can be overridden in your `config.hjson`. I think this will _mostly_ solve your issue by dumping the bots. Please confirm if this helps or not.

@tracker1 Most BBS softwares let you right in without any ESC business. Frontdoor actually did this to detect a user vs a *frontdoor* bot. This makes it similar in that it was "bot detection", but not quite the same. If you really feel strong about this, I'd accept a PR that did something like what I described above _optionally_ -- defaulting to current behavior.

**Comment by davestephens** [comment]
@NuSkooler Doesn't seem to be making a difference, unfortunately :( I wonder if the bots are doing something that mimics pushing buttons, hence the idle timeout never gets hit. 

Additionally they all seem to appear from the same IP, so I could probably do something with iptables, or perhaps Enigma could prevent multiple connections from the same IP at the same time...?

**Comment by NuSkooler** [comment]
@davestephens For now, fail2ban might be good. You can enable key tracing in your logs, we can see if they are sending input to keep from being "idle":
```
logging: {
  traceUserKeyboardInput: true
}
```

Multiple connections from the same IP could be problematic due to NAT, but it could be easy to do if it comes down to it.

**Comment by tracker1** [comment]
Just one thing regarding multiple inputs from the same IP...   If someone is allowing telnet-gateway access from a BBS this can obfuscate and lead to false positives.

May be worth considering not assigning a "node #" at all until after the successful login?

**Comment by NuSkooler** [comment]
The API `getActiveNodeList()` now defaults to *not* returning non-authenticated users. This is what the who's online module utilizes to fetch a list. You can override this in `menu.hjson` for your who's online menu via `config.authUsersOnly: false`. 

See b19d06df26490bdce52c1ab512bf70724a349102

**Comment by davestephens** [comment]
Confirmed that the 'who's online' list is now much cleaner. Thanks!
