### ISSUE TITLE
npm error(s)

### ISSUE THREAD

**Issue by ignatius333** [NuSkooler/enigma-bbs#86]
I get the following errors:

catch22bbs:~/enigma-bbs # npm install
|
> ptyw.js@0.3.8 install /root/enigma-bbs/node_modules/ptyw.js
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
make: Entering directory '/root/enigma-bbs/node_modules/ptyw.js/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/obj.target/pty.node
/usr/lib/libstdc++.so: warning: `sys_nerr' is deprecated; use `strerror' or `strerror_r' instead
/usr/lib/gcc/i586-suse-linux/6/../../../../i586-suse-linux/bin/ld: errno: TLS definition in /lib/libc.so.6 section .tbss mismatches non-TLS reference in /usr/lib/libstdc++.so
/lib/libc.so.6: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make: *** [pty.target.mk:119: Release/obj.target/pty.node] Error 1
make: Leaving directory '/root/enigma-bbs/node_modules/ptyw.js/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/.nvm/versions/node/v4.4.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.5.0-3-pae
gyp ERR! command "/root/.nvm/versions/node/v4.4.0/bin/node" "/root/.nvm/versions/node/v4.4.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/enigma-bbs/node_modules/ptyw.js
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok 
npm ERR! Linux 4.5.0-3-pae
npm ERR! argv "/root/.nvm/versions/node/v4.4.0/bin/node" "/root/.nvm/versions/node/v4.4.0/bin/npm" "install"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE

npm ERR! ptyw.js@0.3.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ptyw.js@0.3.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ptyw.js package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ptyw.js
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ptyw.js
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/enigma-bbs/npm-debug.log

Anyone know what i'm doing wrong?

**Comment by ignatius333** [comment]
Ok. I figured it out. The errors were due to an old version of libstdc++

**Comment by NuSkooler** [comment]
@ignatius333 Glad you figured it out. Is this issue OK to close then?

**Comment by ignatius333** [comment]
Yeah, it is.
