### ISSUE TITLE
Ability to exclude the SysOp from last callers list

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#88]
It would be good if it was possible to exclude the sysop from the last callers list, possibly via a config option. I call my board a lot, so the last callers just ends up being a list of my calls which reduces its worth somewhat...

![screenshot at 2016-08-28 15 39 06](https://cloud.githubusercontent.com/assets/668464/18034477/1b2bef2a-6d36-11e6-8ceb-9d767ec19b8d.png)

**Comment by NuSkooler** [comment]
I think a few people would like this -- my only concern is I (personally) would only like it about 50% of the time. I'm pondering a way to optionally do this, for example logging in with `!NuSkooler` (note the '!' prefix) or such.

What do you think?

**Comment by davestephens** [comment]
Yeah, that's a good point - I've actually had users comment that the sysop (me) never logged in, when in actual fact I had been, just invisibly. 

I'm scraping the memory banks here, was it Wildcat that had a similar feature with the exclamation mark? I think it's a nice way to do it, but I'd personally want it so that it was limited to use by the sysop/admins only.

**Comment by NuSkooler** [comment]
@davestephens It could be tied to an ACS, defaulting to `GM[sysops]`

**Comment by NuSkooler** [comment]
Resolved @ 64ded2514c9c1d93b9776f170bad0511129e4387

I started going down the path described above for a "silent" login. It's mostly working, but needs some additional areas. I've moved that code aside for now until I have some other more important things completed. In any case, you can now set an option in your `last_callers` config blocks to hide ops:
```
config: {
  hideSysOpLogin: true
}
```

I'll create a issue for the silent/stealth option.

**Comment by NuSkooler** [comment]
Reopening: The implementation I created needs some work. Currently only `height` items are retrieved from the DB then +ops are simply filtered out, which leaves the list shorter than it should be.

**Comment by NuSkooler** [comment]
Should be fully resolved now with 470897eadc1a249da1c285d1369facf03442489d:

Setting `hideSysOpLogin` to true like the comment above will filter out +ops but still show the full list if the filtered list ends up being too small to fill the view. You can fully disable +ops from ever showing by setting the value to 'always':
```
config: {
  hideSysOpLogin: always
}
```

**Comment by davestephens** [comment]
I think I'm being stupid - where does this config block go exactly?

**Comment by NuSkooler** [comment]
Sorry, I should clarify more: Any menu entry can have a `config` block with module defined options. This would go in your last callers `menu.hjson` declarions, e.g.:

```
fullLoginSequenceLastCallers: {
			desc: Last Callers
			module: last_callers
			art: LASTCALL
			options: { pause: true }
			next: fullLoginSequenceWhosOnline
			config: {
				hideSysOpLogin: true
			}
		}
```
