### ISSUE TITLE
Discuss how to distribute default menu and prompt configs

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#89]
This isn't a bug, or a feature request, but I wanted to open a discussion on how best to distribute configs (menus, prompts etc) with ENiGMA, and how to guide new users in customising their system.

Take a "standard install" as an example - user does a git pull, starts hacking on menus and prompts, then they inevitably change upstream as one would expect. User tries to update, then they get a merge conflict as they've changed it beyond where git can auto-merge. Merge ballache ensues! I get it that it's unlikely to be THAT complicated, but for a newbie...

I've personally got around this by creating force9-menu.hjson and force9-prompt.hjson, then specifying them in my config file. If they then change upstream I can copy in the bits I want, but I also don't get merge conflicts.  

I'm wondering if it makes sense to distribute the menu and prompt files as something like menu.hjson.dist/prompt.hjson.dist, then part of the initial config copy these to their proper locations. 

There are probably 100 ways to solve this, but this is one that immediately came to mind...

**Comment by NuSkooler** [comment]
@davestephens This area definitely needs work & has caused confusion with some new users at `git pull` / merge time.

I think a start would be copying `menu.hjson` to e.g. `my_board_name.hjson` when running `./optutil.js config --new`. 

I'd also like to add inclusions to `menu.hjson`, `prompt.hjson`, and `theme.hjson`. This would allow for splitting a lot of stuff off and including new features in sep `.hjson` files.

**Comment by danger89** [comment]
Some follow up would be nice.. add some explanations in the read me please.

**Comment by NuSkooler** [comment]
I'm going to add this to my list probably for the 0.0.9-alpha-ish timeframe

**Comment by NuSkooler** [comment]
Update:
`oputil.js config new` will now:

- Create a much more robust `config.hjson` with comments, examples, etc.
- Create a copy of `menu.hjson` and `prompt.hjson` based on your board name

**Comment by NuSkooler** [comment]
I think this one can be closed. Further work to allow includes (ie: splitting up the configs) is in #158
