### ISSUE TITLE
Can't run ENiGMA on a Raspberry Pi3 since addition of farmhash package

### ISSUE THREAD

**Issue by davestephens** [NuSkooler/enigma-bbs#94]
**Short problem description**
With the addition of farmhash, ENiGMA's packages now don't install on a Raspberry Pi3. Seems to be a bug with farmhash, but adding it here for tracking.

Have raised an issue on farmhash: https://github.com/lovell/farmhash/issues/12

**Environment**
- Node 4.4.7
- Operating system (`uname -a` on *nix systems): Linux raspberrypi 4.4.11-v7+ #888 SMP Mon May 23 20:10:33 BST 2016 armv7l GNU/Linux
- Revision (`git rev-parse --short HEAD`): f263847

**Expected behavior**
````npm install```` to complete successfully.

**Actual behavior**
````npm install```` fails to compile the farmhash native extensions.

**Steps to reproduce**
````git pull```` ENiGMA to a Raspberry Pi 3, run ````npm install````

**Comment by NuSkooler** [comment]
Error in https://github.com/lovell/farmhash/issues/12 seems to indicate a g++ bug. What version do you have? Does it work with Clang?

**Comment by davestephens** [comment]
OK, so  this is a known bug in gcc's CPU detection with armv7 procs (ie RPi3). It's been fixed (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132), but I have no idea if Debian Jessie will hoover up a newer version of gcc-4.9.x. It's currently gcc-4.9.2-10. The workaround suggested by the farmhash dev unfortunately doesn't work.

I'm going to test the gcc6 package from Debian Stretch and see if that sorts it. 

Soooooooo...I guess there are a few options;

1. We accept that it's broken, and will probably be broken for a while, and use something else instead

2. It seems to work OK if compiled on an RPi1 and copied across, so could potentially shonk in a tar'd up version as part of the install if we detect an RPi3 (e.g. download & unpack a custom package into node_modules directory rather than ````npm install````)

3. Come up with some convoluted instructions about setting apt sources to Debian Stretch, installing gcc6, re-pointing to Debian Jessie


None are great IMO, but if I had to pick I'd probably go with 1 or 2...

**Comment by NuSkooler** [comment]
Number (2) seems like it would work, but a hack. Number (3) kind of breaks the idea of a quick and easy run `install.sh` and move on idea.

There is xx-hash (native) and xx-hash (pure JS) as options. I'm not married to farmhash and they have (at least in the native space) similar speeds. 

Can you test the xx-hash native on your RPi3? A simple `npm install` of the package should verify if it works OK. If that works OK, I think it's a matter of replacing farmhash with xx-hash and moving on.

**Comment by NuSkooler** [comment]
Native (preferred): https://github.com/mscdex/node-xxhash
Pure JS: https://github.com/pierrec/js-xxhash

**Comment by davestephens** [comment]
xxhash works nicely, I've submitted a PR to switch over to xxhash. 

https://github.com/NuSkooler/enigma-bbs/pull/95

**Comment by lovell** [comment]
Hello, farmhash v1.2.1 is now available and should automagically fix this.

**Comment by davestephens** [comment]
Thanks @lovell, awesome turnaround :) Confirmed all is working with farmhash v1.2.1, have submitted PR #96.

**Comment by NuSkooler** [comment]
+1 thank you to @lovell! 

Pulled in and working like a champ!

**Comment by lovell** [comment]
No probs, interesting project you've got here (I spent far too long using BBSs in pre-www days).

**Comment by NuSkooler** [comment]
@lovell That makes quite a few of us :grin:
